#define DIR_TYPE models
#define INSTALL_TO models/props_spytech

#include $[THISDIRPREFIX]Sources.work_table001.pp
#include $[THISDIRPREFIX]Sources.vent_system_straight_512_small.pp
#include $[THISDIRPREFIX]Sources.vent_system_vent03.pp
#include $[THISDIRPREFIX]Sources.terminal_chair.pp
#include $[THISDIRPREFIX]Sources.outlet01.pp
#include $[THISDIRPREFIX]Sources.exit_sign01.pp
#include $[THISDIRPREFIX]Sources.fire_bell01.pp
#include $[THISDIRPREFIX]Sources.bench001b.pp
#include $[THISDIRPREFIX]Sources.vent_system_straight_256_small.pp
#include $[THISDIRPREFIX]Sources.siren001.pp
#include $[THISDIRPREFIX]Sources.doorframe004a.pp
#include $[THISDIRPREFIX]Sources.vent_system_straight_128_small.pp
#include $[THISDIRPREFIX]Sources.vent_system_corner_small.pp
#include $[THISDIRPREFIX]Sources.computer_wall05.pp
#include $[THISDIRPREFIX]Sources.computer_wall_cabinet.pp
#include $[THISDIRPREFIX]Sources.siren.pp
#include $[THISDIRPREFIX]Sources.vent.pp
#include $[THISDIRPREFIX]Sources.security_camera.pp
#include $[THISDIRPREFIX]Sources.security_camera_bracket.pp
#include $[THISDIRPREFIX]Sources.computer_wall.pp
#include $[THISDIRPREFIX]Sources.computer_wall04.pp
#include $[THISDIRPREFIX]Sources.computer_wall03.pp
#include $[THISDIRPREFIX]Sources.computer_wall06.pp
#include $[THISDIRPREFIX]Sources.vent_system_straight_512.pp
#include $[THISDIRPREFIX]Sources.vent_system_corner.pp
#include $[THISDIRPREFIX]Sources.vent_system_vent01.pp
#include $[THISDIRPREFIX]Sources.vent_system_straight_128.pp
#include $[THISDIRPREFIX]Sources.computer_low.pp
#include $[THISDIRPREFIX]Sources.control_room_console03.pp
#include $[THISDIRPREFIX]Sources.control_room_console02.pp
#include $[THISDIRPREFIX]Sources.control_room_console01.pp
#include $[THISDIRPREFIX]Sources.hanging_ceiling_lamp.pp
#include $[THISDIRPREFIX]Sources.spytech_hanging_light_52.pp
#include $[THISDIRPREFIX]Sources.wall_clock.pp
#include $[THISDIRPREFIX]Sources.watercooler.pp
#include $[THISDIRPREFIX]Sources.chair.pp
#include $[THISDIRPREFIX]Sources.desk.pp
#include $[THISDIRPREFIX]Sources.intercom.pp
#include $[THISDIRPREFIX]Sources.time_card_machine.pp
#include $[THISDIRPREFIX]Sources.time_card_rack.pp
#include $[THISDIRPREFIX]Sources.computer_printer.pp
#include $[THISDIRPREFIX]Sources.reel_rack03.pp
#include $[THISDIRPREFIX]Sources.reel_rack02.pp
#include $[THISDIRPREFIX]Sources.reel_rack01.pp
#include $[THISDIRPREFIX]Sources.reel_rack04.pp
#include $[THISDIRPREFIX]Sources.outlet.pp
#include $[THISDIRPREFIX]Sources.ceiling_conduit.pp
#include $[THISDIRPREFIX]Sources.tv001.pp
#include $[THISDIRPREFIX]Sources.corkboard01.pp
#include $[THISDIRPREFIX]Sources.pipes_wall001.pp
#include $[THISDIRPREFIX]Sources.vent002.pp
#include $[THISDIRPREFIX]Sources.bench001a.pp
#include $[THISDIRPREFIX]Sources.vent_system_straight_256.pp
#include $[THISDIRPREFIX]Sources.doorframe002a.pp
#include $[THISDIRPREFIX]Sources.doorframe003c.pp
#include $[THISDIRPREFIX]Sources.spytech_railing02.pp
#include $[THISDIRPREFIX]Sources.spytech_railing04a.pp
#include $[THISDIRPREFIX]Sources.spytech_railing04b.pp
#include $[THISDIRPREFIX]Sources.spytech_railing01.pp
#include $[THISDIRPREFIX]Sources.spytech_railing03a.pp
#include $[THISDIRPREFIX]Sources.railing_stairs001b.pp
#include $[THISDIRPREFIX]Sources.railing_stairs001c.pp
#include $[THISDIRPREFIX]Sources.railing_stairs001a.pp
#include $[THISDIRPREFIX]Sources.spytech_railing01b.pp
#include $[THISDIRPREFIX]Sources.doorframe004c.pp
#include $[THISDIRPREFIX]Sources.control_room_console04.pp
#include $[THISDIRPREFIX]Sources.fire_bell02.pp
#include $[THISDIRPREFIX]Sources.satellite_dish001.pp
#include $[THISDIRPREFIX]Sources.exit_mounted.pp
#include $[THISDIRPREFIX]Sources.glass_door_handle001a.pp
#include $[THISDIRPREFIX]Sources.vent_system_vent02.pp
#include $[THISDIRPREFIX]Sources.radar001.pp
#include $[THISDIRPREFIX]Sources.radar_top002.pp
#include $[THISDIRPREFIX]Sources.binder001.pp
#include $[THISDIRPREFIX]Sources.radio_tower_skybox001.pp
#include $[THISDIRPREFIX]Sources.doorframe002c.pp
#include $[THISDIRPREFIX]Sources.doorframe004d.pp
