#define DIR_TYPE models
#define INSTALL_TO models/props_2fort

#include $[THISDIRPREFIX]Sources.window004d.pp
#include $[THISDIRPREFIX]Sources.window004c.pp
#include $[THISDIRPREFIX]Sources.nail002.pp
#include $[THISDIRPREFIX]Sources.wastebasket01.pp
#include $[THISDIRPREFIX]Sources.oildrum.pp
#include $[THISDIRPREFIX]Sources.miningcrate001.pp
#include $[THISDIRPREFIX]Sources.miningcrate002.pp
#include $[THISDIRPREFIX]Sources.blue_window001.pp
#include $[THISDIRPREFIX]Sources.mop_and_bucket.pp
#include $[THISDIRPREFIX]Sources.fire_extinguisher.pp
#include $[THISDIRPREFIX]Sources.tire002.pp
#include $[THISDIRPREFIX]Sources.tire001.pp
#include $[THISDIRPREFIX]Sources.trainwheel003.pp
#include $[THISDIRPREFIX]Sources.groundlight001.pp
#include $[THISDIRPREFIX]Sources.lightbulb001.pp
#include $[THISDIRPREFIX]Sources.telephonepole001_skybox.pp
#include $[THISDIRPREFIX]Sources.coffeemachine.pp
#include $[THISDIRPREFIX]Sources.coffeepot.pp
#include $[THISDIRPREFIX]Sources.window002.pp
#include $[THISDIRPREFIX]Sources.window001.pp
#include $[THISDIRPREFIX]Sources.chimney004.pp
#include $[THISDIRPREFIX]Sources.steps_pipe_right_angle.pp
#include $[THISDIRPREFIX]Sources.steps_pipe_e.pp
#include $[THISDIRPREFIX]Sources.steps_pipe_connection.pp
#include $[THISDIRPREFIX]Sources.steps_pipe_d.pp
#include $[THISDIRPREFIX]Sources.steps_pipe_c.pp
#include $[THISDIRPREFIX]Sources.steps_pipe_b.pp
#include $[THISDIRPREFIX]Sources.steps_pipe_a.pp
#include $[THISDIRPREFIX]Sources.window005.pp
#include $[THISDIRPREFIX]Sources.window006b.pp
#include $[THISDIRPREFIX]Sources.grainconveyor001.pp
#include $[THISDIRPREFIX]Sources.chimney006.pp
#include $[THISDIRPREFIX]Sources.tracks001.pp
#include $[THISDIRPREFIX]Sources.silo_cluster01b.pp
#include $[THISDIRPREFIX]Sources.sniper_fence01.pp
#include $[THISDIRPREFIX]Sources.spytech_roofbeam01.pp
#include $[THISDIRPREFIX]Sources.spytech_roofbeam02.pp
#include $[THISDIRPREFIX]Sources.spytech_roofbeam03.pp
#include $[THISDIRPREFIX]Sources.spytech_roofbeam04.pp
#include $[THISDIRPREFIX]Sources.blast_door.pp
#include $[THISDIRPREFIX]Sources.window003.pp
#include $[THISDIRPREFIX]Sources.flag_room_glass_door_frame.pp
#include $[THISDIRPREFIX]Sources.milkjug001.pp
#include $[THISDIRPREFIX]Sources.bullskull001.pp
#include $[THISDIRPREFIX]Sources.nail001.pp
#include $[THISDIRPREFIX]Sources.hose001.pp
#include $[THISDIRPREFIX]Sources.lantern001_off.pp
#include $[THISDIRPREFIX]Sources.metalbucket001.pp
#include $[THISDIRPREFIX]Sources.telephonepole001.pp
#include $[THISDIRPREFIX]Sources.horseshoe001.pp
#include $[THISDIRPREFIX]Sources.wagonwheel001.pp
#include $[THISDIRPREFIX]Sources.pick001.pp
#include $[THISDIRPREFIX]Sources.cow001_reference.pp
#include $[THISDIRPREFIX]Sources.telephone001.pp
#include $[THISDIRPREFIX]Sources.tire003.pp
#include $[THISDIRPREFIX]Sources.chimney005.pp
#include $[THISDIRPREFIX]Sources.corrugated_metal003.pp
#include $[THISDIRPREFIX]Sources.corrugated_metal001.pp
#include $[THISDIRPREFIX]Sources.corrugated_metal002.pp
#include $[THISDIRPREFIX]Sources.tank001.pp
#include $[THISDIRPREFIX]Sources.weathervane001.pp
#include $[THISDIRPREFIX]Sources.chalkboard01.pp
#include $[THISDIRPREFIX]Sources.lunchbag.pp
#include $[THISDIRPREFIX]Sources.thermos.pp
#include $[THISDIRPREFIX]Sources.waterpump001.pp
#include $[THISDIRPREFIX]Sources.chimney003.pp
#include $[THISDIRPREFIX]Sources.trainwheel002.pp
#include $[THISDIRPREFIX]Sources.hubcap.pp
#include $[THISDIRPREFIX]Sources.blue_conveyor001.pp
#include $[THISDIRPREFIX]Sources.bridgesupports001.pp
#include $[THISDIRPREFIX]Sources.chimney008.pp
#include $[THISDIRPREFIX]Sources.window006.pp
#include $[THISDIRPREFIX]Sources.propane_tank_tall01.pp
#include $[THISDIRPREFIX]Sources.tank002.pp
#include $[THISDIRPREFIX]Sources.sink001.pp
#include $[THISDIRPREFIX]Sources.blast_door_frame.pp
#include $[THISDIRPREFIX]Sources.blue_window001_glass.pp
#include $[THISDIRPREFIX]Sources.tracks001b.pp
#include $[THISDIRPREFIX]Sources.bridge_cover001.pp
#include $[THISDIRPREFIX]Sources.bridge_cover_sides001.pp
#include $[THISDIRPREFIX]Sources.window004.pp
#include $[THISDIRPREFIX]Sources.window009.pp
#include $[THISDIRPREFIX]Sources.corrugated_metal007.pp
#include $[THISDIRPREFIX]Sources.chimney001.pp
#include $[THISDIRPREFIX]Sources.hardhat001.pp
#include $[THISDIRPREFIX]Sources.ladder001.pp
#include $[THISDIRPREFIX]Sources.sniper_fence02.pp
#include $[THISDIRPREFIX]Sources.window004b.pp
#include $[THISDIRPREFIX]Sources.groundlight002.pp
#include $[THISDIRPREFIX]Sources.window004c_glass.pp
#include $[THISDIRPREFIX]Sources.chimney_skybox007.pp
#include $[THISDIRPREFIX]Sources.groundlight003.pp
#include $[THISDIRPREFIX]Sources.corrugated_metal005.pp
#include $[THISDIRPREFIX]Sources.corrugated_metal006.pp
#include $[THISDIRPREFIX]Sources.corrugated_metal004.pp
#include $[THISDIRPREFIX]Sources.window004d_cluster01.pp
#include $[THISDIRPREFIX]Sources.handrail001_i1.pp
#include $[THISDIRPREFIX]Sources.window007b.pp
#include $[THISDIRPREFIX]Sources.chimney_skybox001.pp
#include $[THISDIRPREFIX]Sources.chimney_skybox008.pp
