#define DIR_TYPE models
#define INSTALL_TO models/soldier

#begin install_tex
  #define SOURCES \
    soldier_red.ptex soldier_blue.ptex soldier_head.ptex \
    soldier_normal.ptex
#end install_tex

#begin install_mat
  #define SOURCES \
    soldier_red.pmat soldier_blue.pmat soldier_head.pmat \
    eyeball_r_soldier.pmat eyeball_l_soldier.pmat
#end install_mat

#define SOLDIER_ANIMS \
  AttackCrouch_PRIMARY  \
  AttackCrouch_PRIMARY2  \
  AttackCrouch_PRIMARY2_SUPER  \
  AttackCrouch_SECONDARY  \
  AttackCrouch_SECONDARY2  \
  AttackStand_PRIMARY  \
  AttackStand_PRIMARY2  \
  AttackStand_PRIMARY2_SUPER  \
  AttackStand_SECONDARY  \
  AttackStand_SECONDARY2  \
  AttackSwim_PRIMARY  \
  AttackSwim_PRIMARY2  \
  AttackSwim_PRIMARY2_SUPER  \
  AttackSwim_SECONDARY  \
  Attack_Crouch_MELEE  \
  Attack_Crouch_MELEE_ALLCLASS  \
  Attack_Stand_MELEE  \
  Attack_Stand_MELEE_ALLCLASS  \
  MELEE_ALLCLASS_Swim_Swing  \
  MELEE_allclass_idle_arm  \
  Melee_Swim_Swing  \
  PASSTIME_throw_begin  \
  PASSTIME_throw_cancel  \
  PASSTIME_throw_end  \
  PASSTIME_throw_middle  \
  PRIMARY_Stun_begin  \
  PRIMARY_placeSapper  \
  PRIMARY_stun_end  \
  PRIMARY_stun_middle  \
  ReloadAirwalk_PRIMARY  \
  ReloadAirwalk_PRIMARY_2  \
  ReloadAirwalk_PRIMARY_3  \
  ReloadAirwalk_PRIMARY_end  \
  ReloadAirwalk_PRIMARY_end_2  \
  ReloadAirwalk_PRIMARY_end_3  \
  ReloadAirwalk_PRIMARY_loop  \
  ReloadAirwalk_PRIMARY_loop_2  \
  ReloadAirwalk_PRIMARY_loop_3  \
  ReloadCrouch_PRIMARY  \
  ReloadCrouch_PRIMARY_2  \
  ReloadCrouch_PRIMARY_3  \
  ReloadCrouch_PRIMARY_end  \
  ReloadCrouch_PRIMARY_end_2  \
  ReloadCrouch_PRIMARY_end_3  \
  ReloadCrouch_PRIMARY_loop  \
  ReloadCrouch_PRIMARY_loop_2  \
  ReloadCrouch_PRIMARY_loop_3  \
  ReloadCrouch_SECONDARY  \
  ReloadCrouch_SECONDARY2  \
  ReloadCrouch_SECONDARY2_end  \
  ReloadCrouch_SECONDARY2_loop  \
  ReloadCrouch_SECONDARY_end  \
  ReloadCrouch_SECONDARY_loop  \
  ReloadStand_PRIMARY  \
  ReloadStand_PRIMARY_2  \
  ReloadStand_PRIMARY_3  \
  ReloadStand_PRIMARY_end  \
  ReloadStand_PRIMARY_end_2  \
  ReloadStand_PRIMARY_end_3  \
  ReloadStand_PRIMARY_loop  \
  ReloadStand_PRIMARY_loop_2  \
  ReloadStand_PRIMARY_loop_3  \
  ReloadStand_SECONDARY  \
  ReloadStand_SECONDARY2  \
  ReloadStand_SECONDARY2_end  \
  ReloadStand_SECONDARY2_loop  \
  ReloadStand_SECONDARY_end  \
  ReloadStand_SECONDARY_loop  \
  ReloadSwim_PRIMARY  \
  ReloadSwim_PRIMARY_2  \
  ReloadSwim_PRIMARY_3  \
  ReloadSwim_SECONDARY  \
  SECONDARY2_reload_airwalk  \
  SECONDARY2_reload_airwalk_end  \
  SECONDARY2_reload_airwalk_loop  \
  SECONDARY2_reload_swim  \
  SECONDARY2_reload_swim_end  \
  SECONDARY2_reload_swim_loop  \
  SECONDARY_reload_airwalk  \
  SECONDARY_reload_airwalk_end  \
  SECONDARY_reload_airwalk_loop  \
  SECONDARY_reload_swim  \
  SECONDARY_reload_swim_end  \
  SECONDARY_reload_swim_loop  \
  SPELL_arm_pose  \
  SPELL_hand_pose  \
  Soldier_replay_taunt  \
  a_MELEE_ALLCLASS_Swim_Swing  \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center  \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left  \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right  \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center  \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left  \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right  \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral  \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up  \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center  \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left  \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right  \
  a_MELEE_ALLCLASS_aimmatrix_idle_down_center  \
  a_MELEE_ALLCLASS_aimmatrix_idle_down_left  \
  a_MELEE_ALLCLASS_aimmatrix_idle_down_right  \
  a_MELEE_ALLCLASS_aimmatrix_idle_mid_center  \
  a_MELEE_ALLCLASS_aimmatrix_idle_mid_left  \
  a_MELEE_ALLCLASS_aimmatrix_idle_mid_right  \
  a_MELEE_ALLCLASS_aimmatrix_idle_neutral  \
  a_MELEE_ALLCLASS_aimmatrix_idle_straight_up  \
  a_MELEE_ALLCLASS_aimmatrix_idle_up_center  \
  a_MELEE_ALLCLASS_aimmatrix_idle_up_left  \
  a_MELEE_ALLCLASS_aimmatrix_idle_up_right  \
  a_MELEE_ALLCLASS_aimmatrix_run_down_center  \
  a_MELEE_ALLCLASS_aimmatrix_run_down_left  \
  a_MELEE_ALLCLASS_aimmatrix_run_down_right  \
  a_MELEE_ALLCLASS_aimmatrix_run_mid_center  \
  a_MELEE_ALLCLASS_aimmatrix_run_mid_left  \
  a_MELEE_ALLCLASS_aimmatrix_run_mid_right  \
  a_MELEE_ALLCLASS_aimmatrix_run_neutral  \
  a_MELEE_ALLCLASS_aimmatrix_run_straight_up  \
  a_MELEE_ALLCLASS_aimmatrix_run_up_center  \
  a_MELEE_ALLCLASS_aimmatrix_run_up_left  \
  a_MELEE_ALLCLASS_aimmatrix_run_up_right  \
  a_MELEE_ALLCLASS_aimmatrix_swim_down_center  \
  a_MELEE_ALLCLASS_aimmatrix_swim_down_left  \
  a_MELEE_ALLCLASS_aimmatrix_swim_down_right  \
  a_MELEE_ALLCLASS_aimmatrix_swim_mid_center  \
  a_MELEE_ALLCLASS_aimmatrix_swim_mid_left  \
  a_MELEE_ALLCLASS_aimmatrix_swim_mid_right  \
  a_MELEE_ALLCLASS_aimmatrix_swim_neutral  \
  a_MELEE_ALLCLASS_aimmatrix_swim_straight_up  \
  a_MELEE_ALLCLASS_aimmatrix_swim_up_center  \
  a_MELEE_ALLCLASS_aimmatrix_swim_up_left  \
  a_MELEE_ALLCLASS_aimmatrix_swim_up_right  \
  a_MELEE_aimmatrix_crouch_idle_down_center  \
  a_MELEE_aimmatrix_crouch_idle_down_left  \
  a_MELEE_aimmatrix_crouch_idle_down_right  \
  a_MELEE_aimmatrix_crouch_idle_mid_center  \
  a_MELEE_aimmatrix_crouch_idle_mid_left  \
  a_MELEE_aimmatrix_crouch_idle_mid_right  \
  a_MELEE_aimmatrix_crouch_idle_neutral  \
  a_MELEE_aimmatrix_crouch_idle_straight_up  \
  a_MELEE_aimmatrix_crouch_idle_up_center  \
  a_MELEE_aimmatrix_crouch_idle_up_left  \
  a_MELEE_aimmatrix_crouch_idle_up_right  \
  a_MELEE_aimmatrix_idle_down_center  \
  a_MELEE_aimmatrix_idle_down_left  \
  a_MELEE_aimmatrix_idle_down_right  \
  a_MELEE_aimmatrix_idle_mid_center  \
  a_MELEE_aimmatrix_idle_mid_left  \
  a_MELEE_aimmatrix_idle_mid_right  \
  a_MELEE_aimmatrix_idle_neutral  \
  a_MELEE_aimmatrix_idle_straight_up  \
  a_MELEE_aimmatrix_idle_up_center  \
  a_MELEE_aimmatrix_idle_up_left  \
  a_MELEE_aimmatrix_idle_up_right  \
  a_MELEE_aimmatrix_run_down_center  \
  a_MELEE_aimmatrix_run_down_left  \
  a_MELEE_aimmatrix_run_down_right  \
  a_MELEE_aimmatrix_run_mid_center  \
  a_MELEE_aimmatrix_run_mid_left  \
  a_MELEE_aimmatrix_run_mid_right  \
  a_MELEE_aimmatrix_run_neutral  \
  a_MELEE_aimmatrix_run_straight_up  \
  a_MELEE_aimmatrix_run_up_center  \
  a_MELEE_aimmatrix_run_up_left  \
  a_MELEE_aimmatrix_run_up_right  \
  a_MELEE_aimmatrix_swim_down_center  \
  a_MELEE_aimmatrix_swim_down_left  \
  a_MELEE_aimmatrix_swim_down_right  \
  a_MELEE_aimmatrix_swim_mid_center  \
  a_MELEE_aimmatrix_swim_mid_left  \
  a_MELEE_aimmatrix_swim_mid_right  \
  a_MELEE_aimmatrix_swim_neutral  \
  a_MELEE_aimmatrix_swim_straight_up  \
  a_MELEE_aimmatrix_swim_up_center  \
  a_MELEE_aimmatrix_swim_up_left  \
  a_MELEE_aimmatrix_swim_up_right  \
  a_Melee_Swim_Swing  \
  a_PASSTIME_aimmatrix_crouch_idle_down_center  \
  a_PASSTIME_aimmatrix_crouch_idle_down_left  \
  a_PASSTIME_aimmatrix_crouch_idle_down_right  \
  a_PASSTIME_aimmatrix_crouch_idle_mid_center  \
  a_PASSTIME_aimmatrix_crouch_idle_mid_left  \
  a_PASSTIME_aimmatrix_crouch_idle_mid_right  \
  a_PASSTIME_aimmatrix_crouch_idle_neutral  \
  a_PASSTIME_aimmatrix_crouch_idle_straight_up  \
  a_PASSTIME_aimmatrix_crouch_idle_up_center  \
  a_PASSTIME_aimmatrix_crouch_idle_up_left  \
  a_PASSTIME_aimmatrix_crouch_idle_up_right  \
  a_PASSTIME_aimmatrix_idle_down_center  \
  a_PASSTIME_aimmatrix_idle_down_left  \
  a_PASSTIME_aimmatrix_idle_down_right  \
  a_PASSTIME_aimmatrix_idle_mid_center  \
  a_PASSTIME_aimmatrix_idle_mid_left  \
  a_PASSTIME_aimmatrix_idle_mid_right  \
  a_PASSTIME_aimmatrix_idle_neutral  \
  a_PASSTIME_aimmatrix_idle_straight_up  \
  a_PASSTIME_aimmatrix_idle_up_center  \
  a_PASSTIME_aimmatrix_idle_up_left  \
  a_PASSTIME_aimmatrix_idle_up_right  \
  a_PASSTIME_aimmatrix_run_down_center  \
  a_PASSTIME_aimmatrix_run_down_left  \
  a_PASSTIME_aimmatrix_run_down_right  \
  a_PASSTIME_aimmatrix_run_mid_center  \
  a_PASSTIME_aimmatrix_run_mid_left  \
  a_PASSTIME_aimmatrix_run_mid_right  \
  a_PASSTIME_aimmatrix_run_neutral  \
  a_PASSTIME_aimmatrix_run_straight_up  \
  a_PASSTIME_aimmatrix_run_up_center  \
  a_PASSTIME_aimmatrix_run_up_left  \
  a_PASSTIME_aimmatrix_run_up_right  \
  a_PRIMARY_aimmatrix_crouch_idle_down_center  \
  a_PRIMARY_aimmatrix_crouch_idle_down_left  \
  a_PRIMARY_aimmatrix_crouch_idle_down_right  \
  a_PRIMARY_aimmatrix_crouch_idle_mid_center  \
  a_PRIMARY_aimmatrix_crouch_idle_mid_left  \
  a_PRIMARY_aimmatrix_crouch_idle_mid_right  \
  a_PRIMARY_aimmatrix_crouch_idle_neutral  \
  a_PRIMARY_aimmatrix_crouch_idle_straight_up  \
  a_PRIMARY_aimmatrix_crouch_idle_up_center  \
  a_PRIMARY_aimmatrix_crouch_idle_up_left  \
  a_PRIMARY_aimmatrix_crouch_idle_up_right  \
  a_PRIMARY_aimmatrix_idle_down_center  \
  a_PRIMARY_aimmatrix_idle_down_left  \
  a_PRIMARY_aimmatrix_idle_down_right  \
  a_PRIMARY_aimmatrix_idle_mid_center  \
  a_PRIMARY_aimmatrix_idle_mid_left  \
  a_PRIMARY_aimmatrix_idle_mid_right  \
  a_PRIMARY_aimmatrix_idle_neutral  \
  a_PRIMARY_aimmatrix_idle_straight_up  \
  a_PRIMARY_aimmatrix_idle_up_center  \
  a_PRIMARY_aimmatrix_idle_up_left  \
  a_PRIMARY_aimmatrix_idle_up_right  \
  a_PRIMARY_aimmatrix_run_down_center  \
  a_PRIMARY_aimmatrix_run_down_left  \
  a_PRIMARY_aimmatrix_run_down_right  \
  a_PRIMARY_aimmatrix_run_mid_center  \
  a_PRIMARY_aimmatrix_run_mid_left  \
  a_PRIMARY_aimmatrix_run_mid_right  \
  a_PRIMARY_aimmatrix_run_neutral  \
  a_PRIMARY_aimmatrix_run_straight_up  \
  a_PRIMARY_aimmatrix_run_up_center  \
  a_PRIMARY_aimmatrix_run_up_left  \
  a_PRIMARY_aimmatrix_run_up_right  \
  a_PRIMARY_aimmatrix_swim_down_center  \
  a_PRIMARY_aimmatrix_swim_down_left  \
  a_PRIMARY_aimmatrix_swim_down_right  \
  a_PRIMARY_aimmatrix_swim_mid_center  \
  a_PRIMARY_aimmatrix_swim_mid_left  \
  a_PRIMARY_aimmatrix_swim_mid_right  \
  a_PRIMARY_aimmatrix_swim_neutral  \
  a_PRIMARY_aimmatrix_swim_straight_up  \
  a_PRIMARY_aimmatrix_swim_up_center  \
  a_PRIMARY_aimmatrix_swim_up_left  \
  a_PRIMARY_aimmatrix_swim_up_right  \
  a_SECONDARY2_aimmatrix_crouch_idle_down_center  \
  a_SECONDARY2_aimmatrix_crouch_idle_down_left  \
  a_SECONDARY2_aimmatrix_crouch_idle_down_right  \
  a_SECONDARY2_aimmatrix_crouch_idle_mid_center  \
  a_SECONDARY2_aimmatrix_crouch_idle_mid_left  \
  a_SECONDARY2_aimmatrix_crouch_idle_mid_right  \
  a_SECONDARY2_aimmatrix_crouch_idle_neutral  \
  a_SECONDARY2_aimmatrix_crouch_idle_straight_up  \
  a_SECONDARY2_aimmatrix_crouch_idle_up_center  \
  a_SECONDARY2_aimmatrix_crouch_idle_up_left  \
  a_SECONDARY2_aimmatrix_crouch_idle_up_right  \
  a_SECONDARY2_aimmatrix_idle_down_center  \
  a_SECONDARY2_aimmatrix_idle_down_left  \
  a_SECONDARY2_aimmatrix_idle_down_right  \
  a_SECONDARY2_aimmatrix_idle_mid_center  \
  a_SECONDARY2_aimmatrix_idle_mid_left  \
  a_SECONDARY2_aimmatrix_idle_mid_right  \
  a_SECONDARY2_aimmatrix_idle_neutral  \
  a_SECONDARY2_aimmatrix_idle_straight_up  \
  a_SECONDARY2_aimmatrix_idle_up_center  \
  a_SECONDARY2_aimmatrix_idle_up_left  \
  a_SECONDARY2_aimmatrix_idle_up_right  \
  a_SECONDARY2_aimmatrix_run_down_center  \
  a_SECONDARY2_aimmatrix_run_down_left  \
  a_SECONDARY2_aimmatrix_run_down_right  \
  a_SECONDARY2_aimmatrix_run_mid_center  \
  a_SECONDARY2_aimmatrix_run_mid_left  \
  a_SECONDARY2_aimmatrix_run_mid_right  \
  a_SECONDARY2_aimmatrix_run_neutral  \
  a_SECONDARY2_aimmatrix_run_straight_up  \
  a_SECONDARY2_aimmatrix_run_up_center  \
  a_SECONDARY2_aimmatrix_run_up_left  \
  a_SECONDARY2_aimmatrix_run_up_right  \
  a_SECONDARY2_aimmatrix_swim_down_center  \
  a_SECONDARY2_aimmatrix_swim_down_left  \
  a_SECONDARY2_aimmatrix_swim_down_right  \
  a_SECONDARY2_aimmatrix_swim_mid_center  \
  a_SECONDARY2_aimmatrix_swim_mid_left  \
  a_SECONDARY2_aimmatrix_swim_mid_right  \
  a_SECONDARY2_aimmatrix_swim_neutral  \
  a_SECONDARY2_aimmatrix_swim_straight_up  \
  a_SECONDARY2_aimmatrix_swim_up_center  \
  a_SECONDARY2_aimmatrix_swim_up_left  \
  a_SECONDARY2_aimmatrix_swim_up_right  \
  a_SECONDARY2_reload_airwalk  \
  a_SECONDARY2_reload_swim  \
  a_SECONDARY_aimmatrix_crouch_idle_down_center  \
  a_SECONDARY_aimmatrix_crouch_idle_down_left  \
  a_SECONDARY_aimmatrix_crouch_idle_down_right  \
  a_SECONDARY_aimmatrix_crouch_idle_mid_center  \
  a_SECONDARY_aimmatrix_crouch_idle_mid_left  \
  a_SECONDARY_aimmatrix_crouch_idle_mid_right  \
  a_SECONDARY_aimmatrix_crouch_idle_neutral  \
  a_SECONDARY_aimmatrix_crouch_idle_straight_up  \
  a_SECONDARY_aimmatrix_crouch_idle_up_center  \
  a_SECONDARY_aimmatrix_crouch_idle_up_left  \
  a_SECONDARY_aimmatrix_crouch_idle_up_right  \
  a_SECONDARY_aimmatrix_idle_down_center  \
  a_SECONDARY_aimmatrix_idle_down_left  \
  a_SECONDARY_aimmatrix_idle_down_right  \
  a_SECONDARY_aimmatrix_idle_mid_center  \
  a_SECONDARY_aimmatrix_idle_mid_left  \
  a_SECONDARY_aimmatrix_idle_mid_right  \
  a_SECONDARY_aimmatrix_idle_neutral  \
  a_SECONDARY_aimmatrix_idle_straight_up  \
  a_SECONDARY_aimmatrix_idle_up_center  \
  a_SECONDARY_aimmatrix_idle_up_left  \
  a_SECONDARY_aimmatrix_idle_up_right  \
  a_SECONDARY_aimmatrix_run_down_center  \
  a_SECONDARY_aimmatrix_run_down_left  \
  a_SECONDARY_aimmatrix_run_down_right  \
  a_SECONDARY_aimmatrix_run_mid_center  \
  a_SECONDARY_aimmatrix_run_mid_left  \
  a_SECONDARY_aimmatrix_run_mid_right  \
  a_SECONDARY_aimmatrix_run_neutral  \
  a_SECONDARY_aimmatrix_run_straight_up  \
  a_SECONDARY_aimmatrix_run_up_center  \
  a_SECONDARY_aimmatrix_run_up_left  \
  a_SECONDARY_aimmatrix_run_up_right  \
  a_SECONDARY_aimmatrix_swim_down_center  \
  a_SECONDARY_aimmatrix_swim_down_left  \
  a_SECONDARY_aimmatrix_swim_down_right  \
  a_SECONDARY_aimmatrix_swim_mid_center  \
  a_SECONDARY_aimmatrix_swim_mid_left  \
  a_SECONDARY_aimmatrix_swim_mid_right  \
  a_SECONDARY_aimmatrix_swim_neutral  \
  a_SECONDARY_aimmatrix_swim_straight_up  \
  a_SECONDARY_aimmatrix_swim_up_center  \
  a_SECONDARY_aimmatrix_swim_up_left  \
  a_SECONDARY_aimmatrix_swim_up_right  \
  a_SECONDARY_reload_airwalk  \
  a_SECONDARY_reload_swim  \
  a_aerobic_center  \
  a_aerobic_left  \
  a_aerobic_neutral  \
  a_aerobic_right  \
  a_blend_crouchN_crouch_walk_MELEE  \
  a_blend_crouchN_crouch_walk_MELEE_ALLCLASS  \
  a_blend_crouchN_crouch_walk_PASSTIME  \
  a_blend_crouchN_crouch_walk_SECONDARY  \
  a_blend_crouchN_crouch_walk_SECONDARY2  \
  a_crouch_walkCenter_PRIMARY  \
  a_crouch_walkCenter_crouch_walk_MELEE  \
  a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS  \
  a_crouch_walkCenter_crouch_walk_PASSTIME  \
  a_crouch_walkCenter_crouch_walk_SECONDARY  \
  a_crouch_walkCenter_crouch_walk_SECONDARY2  \
  a_crouch_walkE_PRIMARY  \
  a_crouch_walkE_crouch_walk_MELEE  \
  a_crouch_walkE_crouch_walk_MELEE_ALLCLASS  \
  a_crouch_walkE_crouch_walk_PASSTIME  \
  a_crouch_walkE_crouch_walk_SECONDARY  \
  a_crouch_walkE_crouch_walk_SECONDARY2  \
  a_crouch_walkNE_PRIMARY  \
  a_crouch_walkNE_crouch_walk_MELEE  \
  a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS  \
  a_crouch_walkNE_crouch_walk_PASSTIME  \
  a_crouch_walkNE_crouch_walk_SECONDARY  \
  a_crouch_walkNE_crouch_walk_SECONDARY2  \
  a_crouch_walkNW_PRIMARY  \
  a_crouch_walkNW_crouch_walk_MELEE  \
  a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS  \
  a_crouch_walkNW_crouch_walk_PASSTIME  \
  a_crouch_walkNW_crouch_walk_SECONDARY  \
  a_crouch_walkNW_crouch_walk_SECONDARY2  \
  a_crouch_walkN_PRIMARY  \
  a_crouch_walkN_crouch_walk_MELEE  \
  a_crouch_walkN_crouch_walk_MELEE_ALLCLASS  \
  a_crouch_walkN_crouch_walk_PASSTIME  \
  a_crouch_walkN_crouch_walk_SECONDARY  \
  a_crouch_walkN_crouch_walk_SECONDARY2  \
  a_crouch_walkSE_PRIMARY  \
  a_crouch_walkSE_crouch_walk_MELEE  \
  a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS  \
  a_crouch_walkSE_crouch_walk_PASSTIME  \
  a_crouch_walkSE_crouch_walk_SECONDARY  \
  a_crouch_walkSE_crouch_walk_SECONDARY2  \
  a_crouch_walkSW_PRIMARY  \
  a_crouch_walkSW_crouch_walk_MELEE  \
  a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS  \
  a_crouch_walkSW_crouch_walk_PASSTIME  \
  a_crouch_walkSW_crouch_walk_SECONDARY  \
  a_crouch_walkSW_crouch_walk_SECONDARY2  \
  a_crouch_walkS_PRIMARY  \
  a_crouch_walkS_crouch_walk_MELEE  \
  a_crouch_walkS_crouch_walk_MELEE_ALLCLASS  \
  a_crouch_walkS_crouch_walk_PASSTIME  \
  a_crouch_walkS_crouch_walk_SECONDARY  \
  a_crouch_walkS_crouch_walk_SECONDARY2  \
  a_crouch_walkW_PRIMARY  \
  a_crouch_walkW_crouch_walk_MELEE  \
  a_crouch_walkW_crouch_walk_MELEE_ALLCLASS  \
  a_crouch_walkW_crouch_walk_PASSTIME  \
  a_crouch_walkW_crouch_walk_SECONDARY  \
  a_crouch_walkW_crouch_walk_SECONDARY2  \
  a_flinch01  \
  a_grapple_SHOOT  \
  a_grapple_pull_idle  \
  a_grapple_pull_start  \
  a_jumpfloat_LOSER  \
  a_jumpfloat_MELEE  \
  a_jumpfloat_MELEE_ALLCLASS  \
  a_jumpstart_LOSER  \
  a_jumpstart_MELEE  \
  a_jumpstart_MELEE_ALLCLASS  \
  a_kart_jump_float  \
  a_kart_jump_start  \
  a_kart_reference  \
  a_passtime_throw_endpose  \
  a_passtime_throw_startpose  \
  a_quake_reload_startpose  \
  a_reference  \
  a_reload_SECONDARY2_startpose  \
  a_reload_crouch_SECONDARY2_startpose  \
  a_reload_crouch_secondary_startpose  \
  a_reload_secondary_startpose  \
  a_reload_startpose  \
  a_reload_startpose_2  \
  a_reload_startpose_3  \
  a_runCenter_LOSER  \
  a_runCenter_MELEE  \
  a_runCenter_MELEE_ALLCLASS  \
  a_runCenter_PASSTIME  \
  a_runCenter_PRIMARY  \
  a_runCenter_SECONDARY  \
  a_runCenter_SECONDARY2  \
  a_runE_LOSER  \
  a_runE_MELEE  \
  a_runE_MELEE_ALLCLASS  \
  a_runE_PASSTIME  \
  a_runE_PRIMARY  \
  a_runE_SECONDARY  \
  a_runE_SECONDARY2  \
  a_runNE_LOSER  \
  a_runNE_MELEE  \
  a_runNE_MELEE_ALLCLASS  \
  a_runNE_PASSTIME  \
  a_runNE_PRIMARY  \
  a_runNE_SECONDARY  \
  a_runNE_SECONDARY2  \
  a_runNW_LOSER  \
  a_runNW_MELEE  \
  a_runNW_MELEE_ALLCLASS  \
  a_runNW_PASSTIME  \
  a_runNW_PRIMARY  \
  a_runNW_SECONDARY  \
  a_runNW_SECONDARY2  \
  a_runN_LOSER  \
  a_runN_MELEE  \
  a_runN_MELEE_ALLCLASS  \
  a_runN_PASSTIME  \
  a_runN_PRIMARY  \
  a_runN_SECONDARY  \
  a_runN_SECONDARY2  \
  a_runSE_LOSER  \
  a_runSE_MELEE  \
  a_runSE_MELEE_ALLCLASS  \
  a_runSE_PASSTIME  \
  a_runSE_PRIMARY  \
  a_runSE_SECONDARY  \
  a_runSE_SECONDARY2  \
  a_runSW_LOSER  \
  a_runSW_MELEE  \
  a_runSW_MELEE_ALLCLASS  \
  a_runSW_PASSTIME  \
  a_runSW_PRIMARY  \
  a_runSW_SECONDARY  \
  a_runSW_SECONDARY2  \
  a_runS_LOSER  \
  a_runS_MELEE  \
  a_runS_MELEE_ALLCLASS  \
  a_runS_PASSTIME  \
  a_runS_PRIMARY  \
  a_runS_SECONDARY  \
  a_runS_SECONDARY2  \
  a_runW_LOSER  \
  a_runW_MELEE  \
  a_runW_MELEE_ALLCLASS  \
  a_runW_PASSTIME  \
  a_runW_PRIMARY  \
  a_runW_SECONDARY  \
  a_runW_SECONDARY2  \
  a_stun_endpose  \
  a_stun_startpose  \
  a_swimCenter_LOSER  \
  a_swimCenter_MELEE  \
  a_swimCenter_MELEE_ALLCLASS  \
  a_swimCenter_PRIMARY  \
  a_swimCenter_SECONDARY  \
  a_swimCenter_SECONDARY2  \
  a_swimE_LOSER  \
  a_swimE_MELEE  \
  a_swimE_MELEE_ALLCLASS  \
  a_swimE_PRIMARY  \
  a_swimE_SECONDARY  \
  a_swimE_SECONDARY2  \
  a_swimNE_LOSER  \
  a_swimNE_MELEE  \
  a_swimNE_MELEE_ALLCLASS  \
  a_swimNE_PRIMARY  \
  a_swimNE_SECONDARY  \
  a_swimNE_SECONDARY2  \
  a_swimNW_LOSER  \
  a_swimNW_MELEE  \
  a_swimNW_MELEE_ALLCLASS  \
  a_swimNW_PRIMARY  \
  a_swimNW_SECONDARY  \
  a_swimNW_SECONDARY2  \
  a_swimN_LOSER  \
  a_swimN_MELEE  \
  a_swimN_MELEE_ALLCLASS  \
  a_swimN_PRIMARY  \
  a_swimN_SECONDARY  \
  a_swimN_SECONDARY2  \
  a_swimSE_LOSER  \
  a_swimSE_MELEE  \
  a_swimSE_MELEE_ALLCLASS  \
  a_swimSE_PRIMARY  \
  a_swimSE_SECONDARY  \
  a_swimSE_SECONDARY2  \
  a_swimSW_LOSER  \
  a_swimSW_MELEE  \
  a_swimSW_MELEE_ALLCLASS  \
  a_swimSW_PRIMARY  \
  a_swimSW_SECONDARY  \
  a_swimSW_SECONDARY2  \
  a_swimS_LOSER  \
  a_swimS_MELEE  \
  a_swimS_MELEE_ALLCLASS  \
  a_swimS_PRIMARY  \
  a_swimS_SECONDARY  \
  a_swimS_SECONDARY2  \
  a_swimW_LOSER  \
  a_swimW_MELEE  \
  a_swimW_MELEE_ALLCLASS  \
  a_swimW_PRIMARY  \
  a_swimW_SECONDARY  \
  a_swimW_SECONDARY2  \
  a_throw_fire  \
  a_vehicle_allclass_center  \
  a_vehicle_allclass_lean_center  \
  a_vehicle_allclass_lean_neutral  \
  a_vehicle_allclass_left  \
  a_vehicle_allclass_left_bd  \
  a_vehicle_allclass_neutral  \
  a_vehicle_allclass_right  \
  a_vehicle_allclass_right_bd  \
  a_vehicle_lean_backward  \
  a_vehicle_lean_forward  \
  a_vehicle_tank_center  \
  a_vehicle_tank_left  \
  a_vehicle_tank_left_a  \
  a_vehicle_tank_left_b  \
  a_vehicle_tank_neutral  \
  a_vehicle_tank_right  \
  a_vehicle_tank_right_a  \
  a_vehicle_tank_right_b  \
  a_vehicle_taunt_allclass_center  \
  a_vehicle_taunt_allclass_left  \
  a_vehicle_taunt_allclass_neutral  \
  a_vehicle_taunt_allclass_right  \
  airwalk_LOSER  \
  airwalk_MELEE  \
  airwalk_MELEE_ALLCLASS  \
  airwalk_PRIMARY  \
  airwalk_SECONDARY  \
  airwalk_SECONDARY2  \
  arm_pose_01  \
  armslayer_MELEE_ALLCLASS_Swim_swing  \
  armslayer_melee_Swim_swing  \
  armslayer_throw_fire  \
  bodylayer_MELEE_ALLCLASS_Swim_Swing  \
  bodylayer_Melee_Swim_Swing  \
  bread_bagged_pose  \
  bread_baguette_pose  \
  bread_burnt_pose  \
  bread_cinnamon_pose  \
  bread_cornbread_pose  \
  bread_crumpet_pose  \
  bread_monster_pose  \
  bread_pretzel_pose  \
  bread_ration_pose  \
  bread_robo_pose  \
  bread_russianblack_pose  \
  bread_shortbread_pose  \
  competitive_loserstate_idle  \
  competitive_winnerstate_idle  \
  crouch_LOSER  \
  crouch_MELEE  \
  crouch_MELEE_ALLCLASS  \
  crouch_PRIMARY  \
  crouch_SECONDARY  \
  crouch_SECONDARY2  \
  dieviolent  \
  gesture_melee_cheer  \
  gesture_melee_go  \
  gesture_melee_help  \
  gesture_melee_positive  \
  gesture_primary_cheer  \
  gesture_primary_go  \
  gesture_primary_help  \
  gesture_primary_positive  \
  gesture_secondary_cheer  \
  gesture_secondary_go  \
  gesture_secondary_help  \
  gesture_secondary_positive  \
  grapple_arm_pose  \
  grapple_hand_pose  \
  hand_pose_01  \
  hand_pose_02  \
  item1_buglecall_blue  \
  item1_buglecall_red  \
  item2_warhorncall_blue  \
  item2_warhorncall_red  \
  jump_float_PRIMARY  \
  jump_float_SECONDARY  \
  jump_float_SECONDARY2  \
  jump_start_PRIMARY  \
  jump_start_SECONDARY  \
  jump_start_SECONDARY2  \
  jumplandPose_LOSER  \
  jumplandPose_MELEE  \
  jumplandPose_MELEE_ALLCLASS  \
  jumpland_KART  \
  jumpland_LOSER  \
  jumpland_MELEE  \
  jumpland_MELEE_ALLCLASS  \
  jumpland_PRIMARY  \
  jumpland_SECONDARY  \
  jumpland_SECONDARY2  \
  kart_cheer  \
  kart_dash  \
  kart_idle  \
  kart_impact  \
  kart_impact_big  \
  layer_AttackCrouchMELEE_ALLCLASS_arms  \
  layer_AttackCrouchMelee_arms  \
  layer_AttackStandMELEE_ALLCLASS_arms  \
  layer_AttackStandMelee_arms  \
  layer_PASSTIME_throw_begin  \
  layer_PASSTIME_throw_cancel  \
  layer_PASSTIME_throw_end  \
  layer_PASSTIME_throw_middle  \
  layer_PRIMARY_Stun_begin  \
  layer_PRIMARY_Stun_end  \
  layer_PRIMARY_jump_floatNoise  \
  layer_PRIMARY_stun_middle  \
  layer_Soldier_replay_taunt  \
  layer_dieviolent  \
  layer_gesture_item1_buglecall  \
  layer_gesture_item1_buglecall_blue  \
  layer_gesture_item2_warhorncall  \
  layer_gesture_item2_warhorncall_blue  \
  layer_gesture_melee_cheer_armL  \
  layer_gesture_melee_go_armL  \
  layer_gesture_melee_help_armL  \
  layer_gesture_melee_positive  \
  layer_gesture_primary_cheer_armL  \
  layer_gesture_primary_go_armL  \
  layer_gesture_primary_help_armL  \
  layer_gesture_primary_positive_armL  \
  layer_gesture_secondary_cheer_armL  \
  layer_gesture_secondary_go_armL  \
  layer_gesture_secondary_help_armL  \
  layer_gesture_secondary_positive_armL  \
  layer_grapple_SHOOT  \
  layer_kart_cheer  \
  layer_placeSapper_ArmL  \
  layer_quake_reload_standing_arms  \
  layer_quake_reload_standing_arms_end  \
  layer_quake_reload_standing_arms_loop  \
  layer_quake_reload_swim_arms  \
  layer_reload_arms_SECONDARY  \
  layer_reload_arms_SECONDARY2  \
  layer_reload_arms_SECONDARY2_end  \
  layer_reload_arms_SECONDARY2_end_swim  \
  layer_reload_arms_SECONDARY2_loop  \
  layer_reload_arms_SECONDARY2_loop_swim  \
  layer_reload_arms_SECONDARY2_swim  \
  layer_reload_arms_SECONDARY_end  \
  layer_reload_arms_SECONDARY_end_swim  \
  layer_reload_arms_SECONDARY_loop  \
  layer_reload_arms_SECONDARY_loop_swim  \
  layer_reload_arms_SECONDARY_swim  \
  layer_reload_crouch_SECONDARY2_arms  \
  layer_reload_crouch_SECONDARY2_arms_end  \
  layer_reload_crouch_SECONDARY2_arms_loop  \
  layer_reload_crouch_secondary_arms  \
  layer_reload_crouch_secondary_arms_end  \
  layer_reload_crouch_secondary_arms_loop  \
  layer_reload_standing_SECONDARY2_arms  \
  layer_reload_standing_SECONDARY2_arms_end  \
  layer_reload_standing_SECONDARY2_arms_loop  \
  layer_reload_standing_arms  \
  layer_reload_standing_arms_2  \
  layer_reload_standing_arms_3  \
  layer_reload_standing_arms_end  \
  layer_reload_standing_arms_end_2  \
  layer_reload_standing_arms_end_3  \
  layer_reload_standing_arms_loop  \
  layer_reload_standing_arms_loop_2  \
  layer_reload_standing_arms_loop_3  \
  layer_reload_standing_secondary_arms  \
  layer_reload_standing_secondary_arms_end  \
  layer_reload_standing_secondary_arms_loop  \
  layer_reload_swim_arms  \
  layer_reload_swim_arms_2  \
  layer_reload_swim_arms_3  \
  layer_taunt01  \
  layer_taunt02  \
  layer_taunt03  \
  layer_taunt04  \
  layer_taunt05  \
  layer_taunt07  \
  layer_taunt08  \
  layer_taunt09  \
  layer_taunt_coffee  \
  layer_taunt_cyoa_PDA_intro  \
  layer_taunt_cyoa_PDA_outro  \
  layer_taunt_dosido_dance  \
  layer_taunt_dosido_intro  \
  layer_taunt_flip_success_initiator  \
  layer_taunt_flip_success_receiver  \
  layer_taunt_headbutt_start  \
  layer_taunt_headbutt_success  \
  layer_taunt_highfiveSuccess  \
  layer_taunt_highfiveSuccessFull  \
  layer_taunt_laugh  \
  layer_taunt_rps_paper  \
  layer_taunt_rps_paper_lose  \
  layer_taunt_rps_paper_lose2  \
  layer_taunt_rps_paper_win  \
  layer_taunt_rps_rock  \
  layer_taunt_rps_rock_lose  \
  layer_taunt_rps_rock_lose2  \
  layer_taunt_rps_rock_win  \
  layer_taunt_rps_scissors  \
  layer_taunt_rps_scissors_lose  \
  layer_taunt_rps_scissors_lose2  \
  layer_taunt_rps_scissors_win  \
  layer_taunt_vehicle_allclass_end  \
  layer_taunt_vehicle_allclass_honk  \
  layer_taunt_vehicle_allclass_spawn  \
  layer_taunt_vehicle_tank_honk  \
  layer_taunt_yeti_prop  \
  layer_taunt_yetipunch  \
  layer_tuant_vehicle_tank_end  \
  melee_fall_stomp  \
  primary_death_backStab  \
  primary_death_burning  \
  primary_death_headshot  \
  primary_fall_stomp_A  \
  primary_fall_stomp_B  \
  primary_floatA  \
  primary_floatB  \
  primary_floatC  \
  primary_floatD  \
  quake_ReloadAirwalk_PRIMARY  \
  quake_ReloadAirwalk_PRIMARY_end  \
  quake_ReloadAirwalk_PRIMARY_loop  \
  quake_ReloadCrouch_PRIMARY  \
  quake_ReloadCrouch_PRIMARY_end  \
  quake_ReloadCrouch_PRIMARY_loop  \
  quake_ReloadStand_PRIMARY  \
  quake_ReloadStand_PRIMARY_end  \
  quake_ReloadStand_PRIMARY_loop  \
  quake_ReloadSwim_PRIMARY  \
  r_handposes  \
  ragdollspawn  \
  saxxy_pose  \
  selectionMenu_Anim0l  \
  selectionMenu_Idle  \
  selectionMenu_StartPose  \
  stand_LOSER  \
  stand_MELEE  \
  stand_MELEE_ALLCLASS  \
  stand_PASSTIME  \
  stand_PRIMARY  \
  stand_SECONDARY  \
  stand_SECONDARY2  \
  taunt01  \
  taunt02  \
  taunt03  \
  taunt04  \
  taunt05  \
  taunt06  \
  taunt07  \
  taunt08  \
  taunt09  \
  taunt_aerobic_A  \
  taunt_aerobic_A_START  \
  taunt_aerobic_B  \
  taunt_aerobic_B_START  \
  taunt_brutallegend  \
  taunt_brutallegendin  \
  taunt_brutallegendinblend  \
  taunt_brutallegendinterior  \
  taunt_brutallegendout  \
  taunt_brutallegendoutblend  \
  taunt_coffee  \
  taunt_conga  \
  taunt_cyoa_PDA_idle  \
  taunt_cyoa_PDA_intro  \
  taunt_cyoa_PDA_outro  \
  taunt_dosido_dance  \
  taunt_dosido_intro  \
  taunt_flip_start  \
  taunt_flip_success_initiator  \
  taunt_flip_success_receiver  \
  taunt_headbutt_start  \
  taunt_headbutt_success  \
  taunt_highFiveStart  \
  taunt_highFiveStart_idle  \
  taunt_highfiveSuccess  \
  taunt_highfiveSuccessFull  \
  taunt_laugh  \
  taunt_rps_paper  \
  taunt_rps_paper_lose  \
  taunt_rps_paper_lose2  \
  taunt_rps_paper_win  \
  taunt_rps_rock  \
  taunt_rps_rock_lose  \
  taunt_rps_rock_lose2  \
  taunt_rps_rock_win  \
  taunt_rps_scissors  \
  taunt_rps_scissors_lose  \
  taunt_rps_scissors_lose2  \
  taunt_rps_scissors_win  \
  taunt_rps_start  \
  taunt_russian  \
  taunt_vehicle_allclass_end  \
  taunt_vehicle_allclass_honk  \
  taunt_vehicle_allclass_start  \
  taunt_vehicle_allclass_start_layer  \
  taunt_vehicle_tank_end  \
  taunt_vehicle_tank_honk  \
  taunt_vehicle_tank_spawn_layer  \
  taunt_vehicle_tank_start  \
  taunt_vehicle_tank_start_layer  \
  taunt_yeti  \
  taunt_yeti_layer  \
  taunt_yetipunch  \
  test  \
  throw_fire

#begin blender_char_egg
  #define BLENDER_PREFIX soldier-
  #define EGG_PREFIX soldier-
  #define POLY_MODEL zero
  #define CHAR_NAME soldier.qc_skeleton
  #define ANIMS_DIR anims
  #define ANIMS $[SOLDIER_ANIMS]
#end blender_char_egg

#begin optchar_egg
  #define TARGET_DIR optchar
  #define SOURCES \
    soldier-zero.egg \
    $[matrix anims/soldier-,$[SOLDIER_ANIMS],.egg]

  #define OPTCHAR_OPTS \
    -keepall \
    -expose weapon_bone \
    -expose weapon_bone_L \
    -expose weapon_bone_1 \
    -expose bip_head \
    -flag soldier_eye_l \
    -flag soldier_eye_r \
    -flag soldier_morphs_low \
    -flag soldier_morphs_low_lod1 \
    -flag soldier_morphs_low_lod2 \
    -flag soldier_morphs_low_lod3 \
    -flag soldier_morphs_low_lod4 \
    -flag soldier_morphs_low_lod5 \
    -flag medal_bodygroup \
    -flag medal_bodygroup_lod1 \
    -flag medal_bodygroup_lod2 \
    -flag medal_bodygroup_lod3 \
    -flag medal_bodygroup_lod4 \
    -flag medal_bodygroup_lod5 \
    -flag grenades_bodygroup \
    -flag grenades_bodygroup_lod1 \
    -flag grenades_bodygroup_lod2 \
    -flag grenades_bodygroup_lod3 \
    -flag grenades_bodygroup_lod4 \
    -flag grenades_bodygroup_lod5 \
    -flag hat_bodygroup \
    -flag hat_bodygroup_lod1 \
    -flag hat_bodygroup_lod2 \
    -flag hat_bodygroup_lod3 \
    -flag hat_bodygroup_lod4 \
    -flag hat_bodygroup_lod5 \
    -flag soldier_rocket \
    -flag soldier_rocket_lod1 \
    -flag soldier_rocket_lod2 \
    -flag soldier_rocket_lod3 \
    -flag soldier_rocket_lod4 \
    -flag soldier_rocket_lod5
#end optchar_egg

#begin install_egg
  #define SOURCE_DIR optchar
  #define SOURCES \
    soldier-zero.egg
  #define SOURCES_NC \
    $[matrix soldier-,$[SOLDIER_ANIMS],.egg]
#end install_egg
