#define DIR_TYPE models
#define INSTALL_TO models/props_trainyard

#include $[THISDIRPREFIX]Sources.bomb_cart.pp
#include $[THISDIRPREFIX]Sources.cart_bomb_separate.pp
#include $[THISDIRPREFIX]Sources.cart_base_separate.pp
#include $[THISDIRPREFIX]Sources.handrail128.pp
#include $[THISDIRPREFIX]Sources.handrail28.pp
#include $[THISDIRPREFIX]Sources.metal_watertower001.pp
#include $[THISDIRPREFIX]Sources.train_loader001.pp
#include $[THISDIRPREFIX]Sources.blast_furnace001.pp
#include $[THISDIRPREFIX]Sources.train_billboard001_sm.pp
#include $[THISDIRPREFIX]Sources.handrail216.pp
#include $[THISDIRPREFIX]Sources.blast_furnace002.pp
#include $[THISDIRPREFIX]Sources.awning001.pp
#include $[THISDIRPREFIX]Sources.ladder001.pp
#include $[THISDIRPREFIX]Sources.ladder002.pp
#include $[THISDIRPREFIX]Sources.metal_watertower_skybox001.pp
#include $[THISDIRPREFIX]Sources.blast_furnace_skybox007.pp
#include $[THISDIRPREFIX]Sources.handrail480.pp
#include $[THISDIRPREFIX]Sources.handrail608.pp
#include $[THISDIRPREFIX]Sources.handrail_stairs01.pp
#include $[THISDIRPREFIX]Sources.power_pylon.pp
#include $[THISDIRPREFIX]Sources.train_signal_skybox001.pp
#include $[THISDIRPREFIX]Sources.train_signal002.pp
#include $[THISDIRPREFIX]Sources.train_signal004.pp
#include $[THISDIRPREFIX]Sources.blast_furnace_skybox005.pp
#include $[THISDIRPREFIX]Sources.blast_furnace_skybox006.pp
#include $[THISDIRPREFIX]Sources.blast_furnace_skybox001.pp
#include $[THISDIRPREFIX]Sources.blast_furnace_skybox002.pp
#include $[THISDIRPREFIX]Sources.blast_furnace_skybox003.pp
#include $[THISDIRPREFIX]Sources.blast_furnace_skybox004.pp
#include $[THISDIRPREFIX]Sources.overhead_cable_truss.pp
#include $[THISDIRPREFIX]Sources.lightpole.pp
#include $[THISDIRPREFIX]Sources.train_signal003.pp
#include $[THISDIRPREFIX]Sources.metal_watertower_skybox002.pp
#include $[THISDIRPREFIX]Sources.train_sign002.pp
#include $[THISDIRPREFIX]Sources.train_sign001.pp
#include $[THISDIRPREFIX]Sources.train_signal001.pp
#include $[THISDIRPREFIX]Sources.sign001.pp
#include $[THISDIRPREFIX]Sources.train_gate001.pp
#include $[THISDIRPREFIX]Sources.train_gate001b.pp
#include $[THISDIRPREFIX]Sources.crane_box001.pp
#include $[THISDIRPREFIX]Sources.crane_platform001b.pp
#include $[THISDIRPREFIX]Sources.pulley_block001.pp
#include $[THISDIRPREFIX]Sources.train_gate002b.pp
#include $[THISDIRPREFIX]Sources.roof_truss001.pp
#include $[THISDIRPREFIX]Sources.train_gate002.pp
#include $[THISDIRPREFIX]Sources.window_skylight001.pp
#include $[THISDIRPREFIX]Sources.crane_cable001b.pp
#include $[THISDIRPREFIX]Sources.train_building001.pp
#include $[THISDIRPREFIX]Sources.handrailcorner.pp
#include $[THISDIRPREFIX]Sources.handrail_corner02.pp
#include $[THISDIRPREFIX]Sources.train_billboard001.pp
#include $[THISDIRPREFIX]Sources.handrail_stairs.pp
