#define DIR_TYPE models
#define INSTALL_TO models/props_coalmines

#include $[THISDIRPREFIX]Sources.wood_fence_short_128.pp
#include $[THISDIRPREFIX]Sources.wood_fence_128.pp
#include $[THISDIRPREFIX]Sources.wood_fence_64.pp
#include $[THISDIRPREFIX]Sources.wood_support_128.pp
#include $[THISDIRPREFIX]Sources.window5.pp
#include $[THISDIRPREFIX]Sources.wood_support_256.pp
#include $[THISDIRPREFIX]Sources.window7.pp
#include $[THISDIRPREFIX]Sources.wood_fence_256.pp
#include $[THISDIRPREFIX]Sources.wood_fence_short_256.pp
#include $[THISDIRPREFIX]Sources.boulder6.pp
#include $[THISDIRPREFIX]Sources.boulder5.pp
#include $[THISDIRPREFIX]Sources.boulder3_medium.pp
#include $[THISDIRPREFIX]Sources.window6.pp
#include $[THISDIRPREFIX]Sources.scaffolding1.pp
#include $[THISDIRPREFIX]Sources.boulder5_medium.pp
#include $[THISDIRPREFIX]Sources.boulder5_huge.pp
#include $[THISDIRPREFIX]Sources.boulder1_large.pp
#include $[THISDIRPREFIX]Sources.boulder7_huge.pp
#include $[THISDIRPREFIX]Sources.boulder7.pp
#include $[THISDIRPREFIX]Sources.boulder2_large.pp
#include $[THISDIRPREFIX]Sources.boulder3.pp
#include $[THISDIRPREFIX]Sources.boulder2_medium.pp
#include $[THISDIRPREFIX]Sources.boulder4_large.pp
#include $[THISDIRPREFIX]Sources.boulder_pile2.pp
#include $[THISDIRPREFIX]Sources.boulder_pile1.pp
#include $[THISDIRPREFIX]Sources.boulder1.pp
#include $[THISDIRPREFIX]Sources.wood_debris5.pp
#include $[THISDIRPREFIX]Sources.wood_debris4.pp
#include $[THISDIRPREFIX]Sources.wood_debris3.pp
#include $[THISDIRPREFIX]Sources.wood_debris2.pp
#include $[THISDIRPREFIX]Sources.wood_debris1.pp
#include $[THISDIRPREFIX]Sources.boulder5_large.pp
#include $[THISDIRPREFIX]Sources.boulder7_large.pp
#include $[THISDIRPREFIX]Sources.boulder6_large.pp
#include $[THISDIRPREFIX]Sources.boulder1_medium.pp
#include $[THISDIRPREFIX]Sources.boulder2.pp
#include $[THISDIRPREFIX]Sources.boulder6_huge.pp
#include $[THISDIRPREFIX]Sources.upward_bridge_supports1.pp
#include $[THISDIRPREFIX]Sources.foliage_clump3.pp
#include $[THISDIRPREFIX]Sources.foliage_clump1.pp
#include $[THISDIRPREFIX]Sources.foliage_clump2.pp
#include $[THISDIRPREFIX]Sources.foliage_single1.pp
