#define DIR_TYPE models
#define INSTALL_TO models/props_farm

#include $[THISDIRPREFIX]Sources.spool_rope.pp
#include $[THISDIRPREFIX]Sources.wood_pile.pp
#include $[THISDIRPREFIX]Sources.conduit01.pp
#include $[THISDIRPREFIX]Sources.tools_shovel.pp
#include $[THISDIRPREFIX]Sources.tools_fork.pp
#include $[THISDIRPREFIX]Sources.tools_rope.pp
#include $[THISDIRPREFIX]Sources.tools_rack.pp
#include $[THISDIRPREFIX]Sources.gutter_pipe_connect.pp
#include $[THISDIRPREFIX]Sources.gutter_pipe_128.pp
#include $[THISDIRPREFIX]Sources.gutter_hole.pp
#include $[THISDIRPREFIX]Sources.gutter_end002.pp
#include $[THISDIRPREFIX]Sources.gutter_64.pp
#include $[THISDIRPREFIX]Sources.gutter_128.pp
#include $[THISDIRPREFIX]Sources.gutter_end001.pp
#include $[THISDIRPREFIX]Sources.gutter_pipe_end.pp
#include $[THISDIRPREFIX]Sources.spawnroom_door_left.pp
#include $[THISDIRPREFIX]Sources.stairs_wood001a.pp
#include $[THISDIRPREFIX]Sources.stairs_wood001b.pp
#include $[THISDIRPREFIX]Sources.lamp002.pp
#include $[THISDIRPREFIX]Sources.grain_elevator01.pp
#include $[THISDIRPREFIX]Sources.junction_box.pp
#include $[THISDIRPREFIX]Sources.vent001.pp
#include $[THISDIRPREFIX]Sources.box_cluster01.pp
#include $[THISDIRPREFIX]Sources.paint_can002.pp
#include $[THISDIRPREFIX]Sources.box_cluster02.pp
#include $[THISDIRPREFIX]Sources.oilcan01b.pp
#include $[THISDIRPREFIX]Sources.conduit_pipe01.pp
#include $[THISDIRPREFIX]Sources.conduit02.pp
#include $[THISDIRPREFIX]Sources.rafter_01a.pp
#include $[THISDIRPREFIX]Sources.rafter_01b.pp
#include $[THISDIRPREFIX]Sources.spawnroom_door_right.pp
#include $[THISDIRPREFIX]Sources.wooden_barrel.pp
#include $[THISDIRPREFIX]Sources.air_intake.pp
#include $[THISDIRPREFIX]Sources.water_spigot.pp
#include $[THISDIRPREFIX]Sources.haypile001.pp
#include $[THISDIRPREFIX]Sources.tractor_tire001.pp
#include $[THISDIRPREFIX]Sources.drain_pipe001.pp
#include $[THISDIRPREFIX]Sources.grain_elevator04.pp
#include $[THISDIRPREFIX]Sources.tree001_skybox.pp
#include $[THISDIRPREFIX]Sources.tree001.pp
#include $[THISDIRPREFIX]Sources.awning001.pp
#include $[THISDIRPREFIX]Sources.conduit_pipe02.pp
#include $[THISDIRPREFIX]Sources.grain_elevator02.pp
#include $[THISDIRPREFIX]Sources.spool_wire.pp
#include $[THISDIRPREFIX]Sources.metal_pile.pp
#include $[THISDIRPREFIX]Sources.concrete_pipe002.pp
#include $[THISDIRPREFIX]Sources.concrete_pipe001.pp
#include $[THISDIRPREFIX]Sources.doorframe001a.pp
#include $[THISDIRPREFIX]Sources.doorframe001b.pp
#include $[THISDIRPREFIX]Sources.doorframe002d.pp
#include $[THISDIRPREFIX]Sources.doorframe002b.pp
#include $[THISDIRPREFIX]Sources.doorframe002c.pp
#include $[THISDIRPREFIX]Sources.building001.pp
#include $[THISDIRPREFIX]Sources.wood_support001.pp
#include $[THISDIRPREFIX]Sources.rafter_caps001a.pp
#include $[THISDIRPREFIX]Sources.rafter_caps001b.pp
#include $[THISDIRPREFIX]Sources.building002.pp
#include $[THISDIRPREFIX]Sources.wood_shack001.pp
#include $[THISDIRPREFIX]Sources.fence_metal01a.pp
#include $[THISDIRPREFIX]Sources.gate_sign001.pp
#include $[THISDIRPREFIX]Sources.sewer_cap001a.pp
#include $[THISDIRPREFIX]Sources.wood_framing001a.pp
#include $[THISDIRPREFIX]Sources.doorframe002a.pp
#include $[THISDIRPREFIX]Sources.wood_framing001b.pp
#include $[THISDIRPREFIX]Sources.wood_framing001c.pp
#include $[THISDIRPREFIX]Sources.awning002.pp
#include $[THISDIRPREFIX]Sources.barn_loft001a.pp
#include $[THISDIRPREFIX]Sources.barn_loft002a.pp
#include $[THISDIRPREFIX]Sources.silo001.pp
#include $[THISDIRPREFIX]Sources.oilcan02.pp
#include $[THISDIRPREFIX]Sources.welding_machine01.pp
#include $[THISDIRPREFIX]Sources.oilcan01.pp
#include $[THISDIRPREFIX]Sources.roof_vent001.pp
#include $[THISDIRPREFIX]Sources.silo_skybox004_cluster.pp
#include $[THISDIRPREFIX]Sources.silo004b.pp
#include $[THISDIRPREFIX]Sources.barn_tower001.pp
#include $[THISDIRPREFIX]Sources.barn_tower001b.pp
#include $[THISDIRPREFIX]Sources.barn_loft002b.pp
#include $[THISDIRPREFIX]Sources.concrete_block001.pp
#include $[THISDIRPREFIX]Sources.paint_can001.pp
#include $[THISDIRPREFIX]Sources.pallet001.pp
#include $[THISDIRPREFIX]Sources.powertower02_skybox.pp
#include $[THISDIRPREFIX]Sources.silo_skybox001.pp
#include $[THISDIRPREFIX]Sources.powertower01_skybox.pp
#include $[THISDIRPREFIX]Sources.silo_skybox003.pp
#include $[THISDIRPREFIX]Sources.sewer_grate_end01.pp
