#define DIR_TYPE models
#define INSTALL_TO models/char

#begin install_mat
  #define SOURCES \
    materials/eyeball_l_scout.pmat \
    materials/eyeball_r_scout.pmat

#end install_mat

#define SCOUT_ANIMS \
  AttackCrouch_ITEM2 \
  AttackCrouch_PRIMARY \
  AttackCrouch_SECONDARY \
  AttackStand_ITEM2 \
  AttackStand_PRIMARY \
  AttackStand_SECONDARY \
  AttackSwim_ITEM2 \
  AttackSwim_MELEE \
  AttackSwim_MELEE_allclass \
  AttackSwim_PRIMARY \
  AttackSwim_SECONDARY \
  ITEM1_Crouch_fire \
  ITEM1_fire \
  MELEE_allclass_crouch_swing \
  MELEE_allclass_idle_arm \
  MELEE_allclass_swing \
  MELEE_crouch_swing \
  MELEE_swing \
  PASSTIME_throw_begin \
  PASSTIME_throw_cancel \
  PASSTIME_throw_end \
  PASSTIME_throw_middle \
  PRIMARY_Stun_begin \
  PRIMARY_airwalk_reload_end \
  PRIMARY_airwalk_reload_loop \
  PRIMARY_airwalk_reload_start \
  PRIMARY_crouch_reload_end \
  PRIMARY_crouch_reload_loop \
  PRIMARY_crouch_reload_start \
  PRIMARY_placeSapper \
  PRIMARY_reload_end \
  PRIMARY_reload_loop \
  PRIMARY_reload_start \
  PRIMARY_stun_end \
  PRIMARY_stun_middle \
  PRIMARY_swim_reload_end \
  PRIMARY_swim_reload_loop \
  PRIMARY_swim_reload_start \
  ReloadAirwalk_ITEM2 \
  ReloadAirwalk_SECONDARY \
  ReloadAirwalk_SECONDARY_2 \
  ReloadCrouch_ITEM2 \
  ReloadCrouch_SECONDARY \
  ReloadCrouch_SECONDARY_2 \
  ReloadStand_ITEM2 \
  ReloadStand_SECONDARY \
  ReloadStand_SECONDARY_2 \
  ReloadSwim_ITEM2 \
  ReloadSwim_SECONDARY \
  ReloadSwim_SECONDARY_2 \
  SECONDARY_crouch_fire_alt \
  SECONDARY_fire_alt \
  SECONDARY_swim_fire_alt \
  SPELL_arm_pose \
  SPELL_hand_pose \
  a_ITEM1_Crouch_fire \
  a_ITEM1_aimmatrix_crouch_idle_down_center \
  a_ITEM1_aimmatrix_crouch_idle_down_left \
  a_ITEM1_aimmatrix_crouch_idle_down_right \
  a_ITEM1_aimmatrix_crouch_idle_mid_center \
  a_ITEM1_aimmatrix_crouch_idle_mid_left \
  a_ITEM1_aimmatrix_crouch_idle_mid_right \
  a_ITEM1_aimmatrix_crouch_idle_neutral \
  a_ITEM1_aimmatrix_crouch_idle_straight_up \
  a_ITEM1_aimmatrix_crouch_idle_up_center \
  a_ITEM1_aimmatrix_crouch_idle_up_left \
  a_ITEM1_aimmatrix_crouch_idle_up_right \
  a_ITEM1_aimmatrix_idle_down_center \
  a_ITEM1_aimmatrix_idle_down_left \
  a_ITEM1_aimmatrix_idle_down_right \
  a_ITEM1_aimmatrix_idle_mid_center \
  a_ITEM1_aimmatrix_idle_mid_left \
  a_ITEM1_aimmatrix_idle_mid_right \
  a_ITEM1_aimmatrix_idle_neutral \
  a_ITEM1_aimmatrix_idle_straight_up \
  a_ITEM1_aimmatrix_idle_up_center \
  a_ITEM1_aimmatrix_idle_up_left \
  a_ITEM1_aimmatrix_idle_up_right \
  a_ITEM1_aimmatrix_run_down_center \
  a_ITEM1_aimmatrix_run_down_left \
  a_ITEM1_aimmatrix_run_down_right \
  a_ITEM1_aimmatrix_run_mid_center \
  a_ITEM1_aimmatrix_run_mid_left \
  a_ITEM1_aimmatrix_run_mid_right \
  a_ITEM1_aimmatrix_run_neutral \
  a_ITEM1_aimmatrix_run_straight_up \
  a_ITEM1_aimmatrix_run_up_center \
  a_ITEM1_aimmatrix_run_up_left \
  a_ITEM1_aimmatrix_run_up_right \
  a_ITEM1_fire \
  a_ITEM2_aimmatrix_crouch_idle_down_center \
  a_ITEM2_aimmatrix_crouch_idle_down_left \
  a_ITEM2_aimmatrix_crouch_idle_down_right \
  a_ITEM2_aimmatrix_crouch_idle_mid_center \
  a_ITEM2_aimmatrix_crouch_idle_mid_left \
  a_ITEM2_aimmatrix_crouch_idle_mid_right \
  a_ITEM2_aimmatrix_crouch_idle_neutral \
  a_ITEM2_aimmatrix_crouch_idle_straight_up \
  a_ITEM2_aimmatrix_crouch_idle_up_center \
  a_ITEM2_aimmatrix_crouch_idle_up_left \
  a_ITEM2_aimmatrix_crouch_idle_up_right \
  a_ITEM2_aimmatrix_idle_down_center \
  a_ITEM2_aimmatrix_idle_down_left \
  a_ITEM2_aimmatrix_idle_down_right \
  a_ITEM2_aimmatrix_idle_mid_center \
  a_ITEM2_aimmatrix_idle_mid_left \
  a_ITEM2_aimmatrix_idle_mid_right \
  a_ITEM2_aimmatrix_idle_neutral \
  a_ITEM2_aimmatrix_idle_straight_up \
  a_ITEM2_aimmatrix_idle_up_center \
  a_ITEM2_aimmatrix_idle_up_left \
  a_ITEM2_aimmatrix_idle_up_right \
  a_ITEM2_aimmatrix_runS_down_center \
  a_ITEM2_aimmatrix_runS_down_left \
  a_ITEM2_aimmatrix_runS_down_right \
  a_ITEM2_aimmatrix_runS_mid_center \
  a_ITEM2_aimmatrix_runS_mid_left \
  a_ITEM2_aimmatrix_runS_mid_right \
  a_ITEM2_aimmatrix_runS_neutral \
  a_ITEM2_aimmatrix_runS_straight_up \
  a_ITEM2_aimmatrix_runS_up_center \
  a_ITEM2_aimmatrix_runS_up_left \
  a_ITEM2_aimmatrix_runS_up_right \
  a_ITEM2_aimmatrix_run_down_center \
  a_ITEM2_aimmatrix_run_down_left \
  a_ITEM2_aimmatrix_run_down_right \
  a_ITEM2_aimmatrix_run_mid_center \
  a_ITEM2_aimmatrix_run_mid_left \
  a_ITEM2_aimmatrix_run_mid_right \
  a_ITEM2_aimmatrix_run_neutral \
  a_ITEM2_aimmatrix_run_straight_up \
  a_ITEM2_aimmatrix_run_up_center \
  a_ITEM2_aimmatrix_run_up_left \
  a_ITEM2_aimmatrix_run_up_right \
  a_ITEM2_aimmatrix_swim_down_center \
  a_ITEM2_aimmatrix_swim_down_left \
  a_ITEM2_aimmatrix_swim_down_right \
  a_ITEM2_aimmatrix_swim_mid_center \
  a_ITEM2_aimmatrix_swim_mid_left \
  a_ITEM2_aimmatrix_swim_mid_right \
  a_ITEM2_aimmatrix_swim_neutral \
  a_ITEM2_aimmatrix_swim_straight_up \
  a_ITEM2_aimmatrix_swim_up_center \
  a_ITEM2_aimmatrix_swim_up_left \
  a_ITEM2_aimmatrix_swim_up_right \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_center \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_left \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_down_right \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_center \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_left \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_mid_right \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_neutral \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_straight_up \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_center \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_left \
  a_MELEE_ALLCLASS_aimmatrix_crouch_idle_up_right \
  a_MELEE_ALLCLASS_aimmatrix_idle_down_center \
  a_MELEE_ALLCLASS_aimmatrix_idle_down_left \
  a_MELEE_ALLCLASS_aimmatrix_idle_down_right \
  a_MELEE_ALLCLASS_aimmatrix_idle_mid_center \
  a_MELEE_ALLCLASS_aimmatrix_idle_mid_left \
  a_MELEE_ALLCLASS_aimmatrix_idle_mid_right \
  a_MELEE_ALLCLASS_aimmatrix_idle_neutral \
  a_MELEE_ALLCLASS_aimmatrix_idle_straight_up \
  a_MELEE_ALLCLASS_aimmatrix_idle_up_center \
  a_MELEE_ALLCLASS_aimmatrix_idle_up_left \
  a_MELEE_ALLCLASS_aimmatrix_idle_up_right \
  a_MELEE_ALLCLASS_aimmatrix_run_down_center \
  a_MELEE_ALLCLASS_aimmatrix_run_down_left \
  a_MELEE_ALLCLASS_aimmatrix_run_down_right \
  a_MELEE_ALLCLASS_aimmatrix_run_mid_center \
  a_MELEE_ALLCLASS_aimmatrix_run_mid_left \
  a_MELEE_ALLCLASS_aimmatrix_run_mid_right \
  a_MELEE_ALLCLASS_aimmatrix_run_neutral \
  a_MELEE_ALLCLASS_aimmatrix_run_straight_up \
  a_MELEE_ALLCLASS_aimmatrix_run_up_center \
  a_MELEE_ALLCLASS_aimmatrix_run_up_left \
  a_MELEE_ALLCLASS_aimmatrix_run_up_right \
  a_MELEE_aimmatrix_crouch_idle_down_center \
  a_MELEE_aimmatrix_crouch_idle_down_left \
  a_MELEE_aimmatrix_crouch_idle_down_right \
  a_MELEE_aimmatrix_crouch_idle_mid_center \
  a_MELEE_aimmatrix_crouch_idle_mid_left \
  a_MELEE_aimmatrix_crouch_idle_mid_right \
  a_MELEE_aimmatrix_crouch_idle_neutral \
  a_MELEE_aimmatrix_crouch_idle_straight_up \
  a_MELEE_aimmatrix_crouch_idle_up_center \
  a_MELEE_aimmatrix_crouch_idle_up_left \
  a_MELEE_aimmatrix_crouch_idle_up_right \
  a_MELEE_aimmatrix_idle_down_center \
  a_MELEE_aimmatrix_idle_down_left \
  a_MELEE_aimmatrix_idle_down_right \
  a_MELEE_aimmatrix_idle_mid_center \
  a_MELEE_aimmatrix_idle_mid_left \
  a_MELEE_aimmatrix_idle_mid_right \
  a_MELEE_aimmatrix_idle_neutral \
  a_MELEE_aimmatrix_idle_straight_up \
  a_MELEE_aimmatrix_idle_up_center \
  a_MELEE_aimmatrix_idle_up_left \
  a_MELEE_aimmatrix_idle_up_right \
  a_MELEE_aimmatrix_run_down_center \
  a_MELEE_aimmatrix_run_down_left \
  a_MELEE_aimmatrix_run_down_right \
  a_MELEE_aimmatrix_run_mid_center \
  a_MELEE_aimmatrix_run_mid_left \
  a_MELEE_aimmatrix_run_mid_right \
  a_MELEE_aimmatrix_run_neutral \
  a_MELEE_aimmatrix_run_straight_up \
  a_MELEE_aimmatrix_run_up_center \
  a_MELEE_aimmatrix_run_up_left \
  a_MELEE_aimmatrix_run_up_right \
  a_PASSTIME_aimmatrix_crouch_idle_down_center \
  a_PASSTIME_aimmatrix_crouch_idle_down_left \
  a_PASSTIME_aimmatrix_crouch_idle_down_right \
  a_PASSTIME_aimmatrix_crouch_idle_mid_center \
  a_PASSTIME_aimmatrix_crouch_idle_mid_left \
  a_PASSTIME_aimmatrix_crouch_idle_mid_right \
  a_PASSTIME_aimmatrix_crouch_idle_neutral \
  a_PASSTIME_aimmatrix_crouch_idle_straight_up \
  a_PASSTIME_aimmatrix_crouch_idle_up_center \
  a_PASSTIME_aimmatrix_crouch_idle_up_left \
  a_PASSTIME_aimmatrix_crouch_idle_up_right \
  a_PASSTIME_aimmatrix_idle_down_center \
  a_PASSTIME_aimmatrix_idle_down_left \
  a_PASSTIME_aimmatrix_idle_down_right \
  a_PASSTIME_aimmatrix_idle_mid_center \
  a_PASSTIME_aimmatrix_idle_mid_left \
  a_PASSTIME_aimmatrix_idle_mid_right \
  a_PASSTIME_aimmatrix_idle_neutral \
  a_PASSTIME_aimmatrix_idle_straight_up \
  a_PASSTIME_aimmatrix_idle_up_center \
  a_PASSTIME_aimmatrix_idle_up_left \
  a_PASSTIME_aimmatrix_idle_up_right \
  a_PASSTIME_aimmatrix_run_down_center \
  a_PASSTIME_aimmatrix_run_down_left \
  a_PASSTIME_aimmatrix_run_down_right \
  a_PASSTIME_aimmatrix_run_mid_center \
  a_PASSTIME_aimmatrix_run_mid_left \
  a_PASSTIME_aimmatrix_run_mid_right \
  a_PASSTIME_aimmatrix_run_neutral \
  a_PASSTIME_aimmatrix_run_straight_up \
  a_PASSTIME_aimmatrix_run_up_center \
  a_PASSTIME_aimmatrix_run_up_left \
  a_PASSTIME_aimmatrix_run_up_right \
  a_PRIMARY_aimmatrix_crouch_idle_down_center \
  a_PRIMARY_aimmatrix_crouch_idle_down_left \
  a_PRIMARY_aimmatrix_crouch_idle_down_right \
  a_PRIMARY_aimmatrix_crouch_idle_mid_center \
  a_PRIMARY_aimmatrix_crouch_idle_mid_left \
  a_PRIMARY_aimmatrix_crouch_idle_mid_right \
  a_PRIMARY_aimmatrix_crouch_idle_neutral \
  a_PRIMARY_aimmatrix_crouch_idle_straight_up \
  a_PRIMARY_aimmatrix_crouch_idle_up_center \
  a_PRIMARY_aimmatrix_crouch_idle_up_left \
  a_PRIMARY_aimmatrix_crouch_idle_up_right \
  a_PRIMARY_aimmatrix_idle_down_center \
  a_PRIMARY_aimmatrix_idle_down_left \
  a_PRIMARY_aimmatrix_idle_down_right \
  a_PRIMARY_aimmatrix_idle_mid_center \
  a_PRIMARY_aimmatrix_idle_mid_left \
  a_PRIMARY_aimmatrix_idle_mid_right \
  a_PRIMARY_aimmatrix_idle_neutral \
  a_PRIMARY_aimmatrix_idle_straight_up \
  a_PRIMARY_aimmatrix_idle_up_center \
  a_PRIMARY_aimmatrix_idle_up_left \
  a_PRIMARY_aimmatrix_idle_up_right \
  a_PRIMARY_aimmatrix_runS_down_center \
  a_PRIMARY_aimmatrix_runS_down_left \
  a_PRIMARY_aimmatrix_runS_down_right \
  a_PRIMARY_aimmatrix_runS_mid_center \
  a_PRIMARY_aimmatrix_runS_mid_left \
  a_PRIMARY_aimmatrix_runS_mid_right \
  a_PRIMARY_aimmatrix_runS_neutral \
  a_PRIMARY_aimmatrix_runS_straight_up \
  a_PRIMARY_aimmatrix_runS_up_center \
  a_PRIMARY_aimmatrix_runS_up_left \
  a_PRIMARY_aimmatrix_runS_up_right \
  a_PRIMARY_aimmatrix_run_down_center \
  a_PRIMARY_aimmatrix_run_down_left \
  a_PRIMARY_aimmatrix_run_down_right \
  a_PRIMARY_aimmatrix_run_mid_center \
  a_PRIMARY_aimmatrix_run_mid_left \
  a_PRIMARY_aimmatrix_run_mid_right \
  a_PRIMARY_aimmatrix_run_neutral \
  a_PRIMARY_aimmatrix_run_straight_up \
  a_PRIMARY_aimmatrix_run_up_center \
  a_PRIMARY_aimmatrix_run_up_left \
  a_PRIMARY_aimmatrix_run_up_right \
  a_PRIMARY_aimmatrix_swim_down_center \
  a_PRIMARY_aimmatrix_swim_down_left \
  a_PRIMARY_aimmatrix_swim_down_right \
  a_PRIMARY_aimmatrix_swim_mid_center \
  a_PRIMARY_aimmatrix_swim_mid_left \
  a_PRIMARY_aimmatrix_swim_mid_right \
  a_PRIMARY_aimmatrix_swim_neutral \
  a_PRIMARY_aimmatrix_swim_straight_up \
  a_PRIMARY_aimmatrix_swim_up_center \
  a_PRIMARY_aimmatrix_swim_up_left \
  a_PRIMARY_aimmatrix_swim_up_right \
  a_SECONDARY_aimmatrix_crouch_idle_down_center \
  a_SECONDARY_aimmatrix_crouch_idle_down_left \
  a_SECONDARY_aimmatrix_crouch_idle_down_right \
  a_SECONDARY_aimmatrix_crouch_idle_mid_center \
  a_SECONDARY_aimmatrix_crouch_idle_mid_left \
  a_SECONDARY_aimmatrix_crouch_idle_mid_right \
  a_SECONDARY_aimmatrix_crouch_idle_neutral \
  a_SECONDARY_aimmatrix_crouch_idle_straight_up \
  a_SECONDARY_aimmatrix_crouch_idle_up_center \
  a_SECONDARY_aimmatrix_crouch_idle_up_left \
  a_SECONDARY_aimmatrix_crouch_idle_up_right \
  a_SECONDARY_aimmatrix_idle_down_center \
  a_SECONDARY_aimmatrix_idle_down_left \
  a_SECONDARY_aimmatrix_idle_down_right \
  a_SECONDARY_aimmatrix_idle_mid_center \
  a_SECONDARY_aimmatrix_idle_mid_left \
  a_SECONDARY_aimmatrix_idle_mid_right \
  a_SECONDARY_aimmatrix_idle_neutral \
  a_SECONDARY_aimmatrix_idle_straight_up \
  a_SECONDARY_aimmatrix_idle_up_center \
  a_SECONDARY_aimmatrix_idle_up_left \
  a_SECONDARY_aimmatrix_idle_up_right \
  a_SECONDARY_aimmatrix_run_down_center \
  a_SECONDARY_aimmatrix_run_down_left \
  a_SECONDARY_aimmatrix_run_down_right \
  a_SECONDARY_aimmatrix_run_mid_center \
  a_SECONDARY_aimmatrix_run_mid_left \
  a_SECONDARY_aimmatrix_run_mid_right \
  a_SECONDARY_aimmatrix_run_neutral \
  a_SECONDARY_aimmatrix_run_straight_up \
  a_SECONDARY_aimmatrix_run_up_center \
  a_SECONDARY_aimmatrix_run_up_left \
  a_SECONDARY_aimmatrix_run_up_right \
  a_STUN_aimmatrix_crouch_idle_down_center \
  a_STUN_aimmatrix_crouch_idle_down_left \
  a_STUN_aimmatrix_crouch_idle_down_right \
  a_STUN_aimmatrix_crouch_idle_mid_center \
  a_STUN_aimmatrix_crouch_idle_mid_left \
  a_STUN_aimmatrix_crouch_idle_mid_right \
  a_STUN_aimmatrix_crouch_idle_neutral \
  a_STUN_aimmatrix_crouch_idle_straight_up \
  a_STUN_aimmatrix_crouch_idle_up_center \
  a_STUN_aimmatrix_crouch_idle_up_left \
  a_STUN_aimmatrix_crouch_idle_up_right \
  a_STUN_aimmatrix_idle_down_center \
  a_STUN_aimmatrix_idle_down_left \
  a_STUN_aimmatrix_idle_down_right \
  a_STUN_aimmatrix_idle_mid_center \
  a_STUN_aimmatrix_idle_mid_left \
  a_STUN_aimmatrix_idle_mid_right \
  a_STUN_aimmatrix_idle_neutral \
  a_STUN_aimmatrix_idle_straight_up \
  a_STUN_aimmatrix_idle_up_center \
  a_STUN_aimmatrix_idle_up_left \
  a_STUN_aimmatrix_idle_up_right \
  a_STUN_aimmatrix_run_down_center \
  a_STUN_aimmatrix_run_down_left \
  a_STUN_aimmatrix_run_down_right \
  a_STUN_aimmatrix_run_mid_center \
  a_STUN_aimmatrix_run_mid_left \
  a_STUN_aimmatrix_run_mid_right \
  a_STUN_aimmatrix_run_neutral \
  a_STUN_aimmatrix_run_straight_up \
  a_STUN_aimmatrix_run_up_center \
  a_STUN_aimmatrix_run_up_left \
  a_STUN_aimmatrix_run_up_right \
  a_aerobic_center \
  a_aerobic_left \
  a_aerobic_neutral \
  a_aerobic_right \
  a_blend_crouchN_crouch_Walk_SECONDARY \
  a_blend_crouchN_crouch_walk_ITEM1 \
  a_blend_crouchN_crouch_walk_ITEM2 \
  a_blend_crouchN_crouch_walk_MELEE \
  a_blend_crouchN_crouch_walk_MELEE_ALLCLASS \
  a_blend_crouchN_crouch_walk_PASSTIME \
  a_crouch_walkCenter_PRIMARY \
  a_crouch_walkCenter_crouch_Walk_SECONDARY \
  a_crouch_walkCenter_crouch_walk_ITEM1 \
  a_crouch_walkCenter_crouch_walk_ITEM2 \
  a_crouch_walkCenter_crouch_walk_MELEE \
  a_crouch_walkCenter_crouch_walk_MELEE_ALLCLASS \
  a_crouch_walkCenter_crouch_walk_PASSTIME \
  a_crouch_walkE_PRIMARY \
  a_crouch_walkE_crouch_Walk_SECONDARY \
  a_crouch_walkE_crouch_walk_ITEM1 \
  a_crouch_walkE_crouch_walk_ITEM2 \
  a_crouch_walkE_crouch_walk_MELEE \
  a_crouch_walkE_crouch_walk_MELEE_ALLCLASS \
  a_crouch_walkE_crouch_walk_PASSTIME \
  a_crouch_walkNE_PRIMARY \
  a_crouch_walkNE_crouch_Walk_SECONDARY \
  a_crouch_walkNE_crouch_walk_ITEM1 \
  a_crouch_walkNE_crouch_walk_ITEM2 \
  a_crouch_walkNE_crouch_walk_MELEE \
  a_crouch_walkNE_crouch_walk_MELEE_ALLCLASS \
  a_crouch_walkNE_crouch_walk_PASSTIME \
  a_crouch_walkNW_PRIMARY \
  a_crouch_walkNW_crouch_Walk_SECONDARY \
  a_crouch_walkNW_crouch_walk_ITEM1 \
  a_crouch_walkNW_crouch_walk_ITEM2 \
  a_crouch_walkNW_crouch_walk_MELEE \
  a_crouch_walkNW_crouch_walk_MELEE_ALLCLASS \
  a_crouch_walkNW_crouch_walk_PASSTIME \
  a_crouch_walkN_PRIMARY \
  a_crouch_walkN_crouch_Walk_SECONDARY \
  a_crouch_walkN_crouch_walk_ITEM1 \
  a_crouch_walkN_crouch_walk_ITEM2 \
  a_crouch_walkN_crouch_walk_MELEE \
  a_crouch_walkN_crouch_walk_MELEE_ALLCLASS \
  a_crouch_walkN_crouch_walk_PASSTIME \
  a_crouch_walkSE_PRIMARY \
  a_crouch_walkSE_crouch_Walk_SECONDARY \
  a_crouch_walkSE_crouch_walk_ITEM1 \
  a_crouch_walkSE_crouch_walk_ITEM2 \
  a_crouch_walkSE_crouch_walk_MELEE \
  a_crouch_walkSE_crouch_walk_MELEE_ALLCLASS \
  a_crouch_walkSE_crouch_walk_PASSTIME \
  a_crouch_walkSW_PRIMARY \
  a_crouch_walkSW_crouch_Walk_SECONDARY \
  a_crouch_walkSW_crouch_walk_ITEM1 \
  a_crouch_walkSW_crouch_walk_ITEM2 \
  a_crouch_walkSW_crouch_walk_MELEE \
  a_crouch_walkSW_crouch_walk_MELEE_ALLCLASS \
  a_crouch_walkSW_crouch_walk_PASSTIME \
  a_crouch_walkS_PRIMARY \
  a_crouch_walkS_crouch_Walk_SECONDARY \
  a_crouch_walkS_crouch_walk_ITEM1 \
  a_crouch_walkS_crouch_walk_ITEM2 \
  a_crouch_walkS_crouch_walk_MELEE \
  a_crouch_walkS_crouch_walk_MELEE_ALLCLASS \
  a_crouch_walkS_crouch_walk_PASSTIME \
  a_crouch_walkW_PRIMARY \
  a_crouch_walkW_crouch_Walk_SECONDARY \
  a_crouch_walkW_crouch_walk_ITEM1 \
  a_crouch_walkW_crouch_walk_ITEM2 \
  a_crouch_walkW_crouch_walk_MELEE \
  a_crouch_walkW_crouch_walk_MELEE_ALLCLASS \
  a_crouch_walkW_crouch_walk_PASSTIME \
  a_crouchjump_E_primary \
  a_crouchjump_NE_primary \
  a_crouchjump_NW_primary \
  a_crouchjump_N_primary \
  a_crouchjump_SE_primary \
  a_crouchjump_SW_primary \
  a_crouchjump_S_primary \
  a_crouchjump_W_primary \
  a_crouchjump_center_primary \
  a_flinch01 \
  a_grapple_SHOOT \
  a_grapple_pull_idle \
  a_grapple_pull_start \
  a_jumpDouble_E_loser \
  a_jumpDouble_E_primary \
  a_jumpDouble_NE_loser \
  a_jumpDouble_NE_primary \
  a_jumpDouble_NW_loser \
  a_jumpDouble_NW_primary \
  a_jumpDouble_N_loser \
  a_jumpDouble_N_primary \
  a_jumpDouble_S_loser \
  a_jumpDouble_S_primary \
  a_jumpDouble_W_loser \
  a_jumpDouble_W_primary \
  a_jumpDouble_center_loser \
  a_jumpDouble_center_primary \
  a_jumpFloat_E_ITEM1 \
  a_jumpFloat_E_ITEM2 \
  a_jumpFloat_E_MELEE_ALLCLASS \
  a_jumpFloat_E_loser \
  a_jumpFloat_E_melee \
  a_jumpFloat_E_primary \
  a_jumpFloat_E_secondary \
  a_jumpFloat_ITEM1 \
  a_jumpFloat_ITEM2 \
  a_jumpFloat_MELEE_ALLCLASS \
  a_jumpFloat_NE_ITEM1 \
  a_jumpFloat_NE_ITEM2 \
  a_jumpFloat_NE_MELEE_ALLCLASS \
  a_jumpFloat_NE_loser \
  a_jumpFloat_NE_melee \
  a_jumpFloat_NE_primary \
  a_jumpFloat_NE_secondary \
  a_jumpFloat_NW_ITEM1 \
  a_jumpFloat_NW_ITEM2 \
  a_jumpFloat_NW_MELEE_ALLCLASS \
  a_jumpFloat_NW_loser \
  a_jumpFloat_NW_melee \
  a_jumpFloat_NW_primary \
  a_jumpFloat_NW_secondary \
  a_jumpFloat_N_ITEM1 \
  a_jumpFloat_N_ITEM2 \
  a_jumpFloat_N_MELEE_ALLCLASS \
  a_jumpFloat_N_loser \
  a_jumpFloat_N_melee \
  a_jumpFloat_N_primary \
  a_jumpFloat_N_secondary \
  a_jumpFloat_SE_ITEM1 \
  a_jumpFloat_SE_ITEM2 \
  a_jumpFloat_SE_MELEE_ALLCLASS \
  a_jumpFloat_SE_loser \
  a_jumpFloat_SE_melee \
  a_jumpFloat_SE_primary \
  a_jumpFloat_SE_secondary \
  a_jumpFloat_SW_ITEM1 \
  a_jumpFloat_SW_ITEM2 \
  a_jumpFloat_SW_MELEE_ALLCLASS \
  a_jumpFloat_SW_loser \
  a_jumpFloat_SW_melee \
  a_jumpFloat_SW_primary \
  a_jumpFloat_SW_secondary \
  a_jumpFloat_S_ITEM1 \
  a_jumpFloat_S_ITEM2 \
  a_jumpFloat_S_MELEE_ALLCLASS \
  a_jumpFloat_S_loser \
  a_jumpFloat_S_melee \
  a_jumpFloat_S_primary \
  a_jumpFloat_S_secondary \
  a_jumpFloat_W_ITEM1 \
  a_jumpFloat_W_ITEM2 \
  a_jumpFloat_W_MELEE_ALLCLASS \
  a_jumpFloat_W_loser \
  a_jumpFloat_W_melee \
  a_jumpFloat_W_primary \
  a_jumpFloat_W_secondary \
  a_jumpFloat_loser \
  a_jumpFloat_melee \
  a_jumpFloat_primary \
  a_jumpFloat_secondary \
  a_jumpstart_E_ITEM1 \
  a_jumpstart_E_ITEM2 \
  a_jumpstart_E_MELEE_ALLCLASS \
  a_jumpstart_E_loser \
  a_jumpstart_E_melee \
  a_jumpstart_E_primary \
  a_jumpstart_E_secondary \
  a_jumpstart_ITEM1 \
  a_jumpstart_ITEM2 \
  a_jumpstart_MELEE_ALLCLASS \
  a_jumpstart_NE_ITEM1 \
  a_jumpstart_NE_ITEM2 \
  a_jumpstart_NE_MELEE_ALLCLASS \
  a_jumpstart_NE_loser \
  a_jumpstart_NE_melee \
  a_jumpstart_NE_primary \
  a_jumpstart_NE_secondary \
  a_jumpstart_NW_ITEM1 \
  a_jumpstart_NW_ITEM2 \
  a_jumpstart_NW_MELEE_ALLCLASS \
  a_jumpstart_NW_loser \
  a_jumpstart_NW_melee \
  a_jumpstart_NW_primary \
  a_jumpstart_NW_secondary \
  a_jumpstart_N_ITEM1 \
  a_jumpstart_N_ITEM2 \
  a_jumpstart_N_MELEE_ALLCLASS \
  a_jumpstart_N_loser \
  a_jumpstart_N_melee \
  a_jumpstart_N_primary \
  a_jumpstart_N_secondary \
  a_jumpstart_SE_ITEM1 \
  a_jumpstart_SE_ITEM2 \
  a_jumpstart_SE_MELEE_ALLCLASS \
  a_jumpstart_SE_loser \
  a_jumpstart_SE_melee \
  a_jumpstart_SE_primary \
  a_jumpstart_SE_secondary \
  a_jumpstart_SW_ITEM1 \
  a_jumpstart_SW_ITEM2 \
  a_jumpstart_SW_MELEE_ALLCLASS \
  a_jumpstart_SW_loser \
  a_jumpstart_SW_melee \
  a_jumpstart_SW_primary \
  a_jumpstart_SW_secondary \
  a_jumpstart_S_ITEM1 \
  a_jumpstart_S_ITEM2 \
  a_jumpstart_S_MELEE_ALLCLASS \
  a_jumpstart_S_loser \
  a_jumpstart_S_melee \
  a_jumpstart_S_primary \
  a_jumpstart_S_secondary \
  a_jumpstart_W_ITEM1 \
  a_jumpstart_W_ITEM2 \
  a_jumpstart_W_MELEE_ALLCLASS \
  a_jumpstart_W_loser \
  a_jumpstart_W_melee \
  a_jumpstart_W_primary \
  a_jumpstart_W_secondary \
  a_jumpstart_loser \
  a_jumpstart_melee \
  a_jumpstart_primary \
  a_jumpstart_secondary \
  a_kart_jump_float \
  a_kart_jump_start \
  a_kart_reference \
  a_passtime_throw_endpose \
  a_passtime_throw_startpose \
  a_reference \
  a_reload_startpose \
  a_runCenter_ITEM1 \
  a_runCenter_ITEM2 \
  a_runCenter_LOSER \
  a_runCenter_MELEE \
  a_runCenter_MELEE_ALLCLASS \
  a_runCenter_PASSTIME \
  a_runCenter_PRIMARY \
  a_runCenter_SECONDARY \
  a_runE_ITEM1 \
  a_runE_ITEM2 \
  a_runE_LOSER \
  a_runE_MELEE \
  a_runE_MELEE_ALLCLASS \
  a_runE_PASSTIME \
  a_runE_PRIMARY \
  a_runE_SECONDARY \
  a_runNE_ITEM1 \
  a_runNE_ITEM2 \
  a_runNE_LOSER \
  a_runNE_MELEE \
  a_runNE_MELEE_ALLCLASS \
  a_runNE_PASSTIME \
  a_runNE_PRIMARY \
  a_runNE_SECONDARY \
  a_runNW_ITEM1 \
  a_runNW_ITEM2 \
  a_runNW_LOSER \
  a_runNW_MELEE \
  a_runNW_MELEE_ALLCLASS \
  a_runNW_PASSTIME \
  a_runNW_PRIMARY \
  a_runNW_SECONDARY \
  a_runN_ITEM1 \
  a_runN_ITEM2 \
  a_runN_LOSER \
  a_runN_MELEE \
  a_runN_MELEE_ALLCLASS \
  a_runN_PASSTIME \
  a_runN_PRIMARY \
  a_runN_SECONDARY \
  a_runSE_ITEM1 \
  a_runSE_ITEM2 \
  a_runSE_LOSER \
  a_runSE_MELEE \
  a_runSE_MELEE_ALLCLASS \
  a_runSE_PASSTIME \
  a_runSE_PRIMARY \
  a_runSE_SECONDARY \
  a_runSW_ITEM1 \
  a_runSW_ITEM2 \
  a_runSW_LOSER \
  a_runSW_MELEE \
  a_runSW_MELEE_ALLCLASS \
  a_runSW_PASSTIME \
  a_runSW_PRIMARY \
  a_runSW_SECONDARY \
  a_runS_ITEM1 \
  a_runS_ITEM2 \
  a_runS_LOSER \
  a_runS_MELEE \
  a_runS_MELEE_ALLCLASS \
  a_runS_PASSTIME \
  a_runS_PRIMARY \
  a_runS_SECONDARY \
  a_runW_ITEM1 \
  a_runW_ITEM2 \
  a_runW_LOSER \
  a_runW_MELEE \
  a_runW_MELEE_ALLCLASS \
  a_runW_PASSTIME \
  a_runW_PRIMARY \
  a_runW_SECONDARY \
  a_stun_endpose \
  a_stun_startpose \
  a_swimCenter_ITEM1 \
  a_swimCenter_ITEM2 \
  a_swimCenter_LOSER \
  a_swimCenter_MELEE \
  a_swimCenter_MELEE_ALLCLASS \
  a_swimCenter_PRIMARY \
  a_swimCenter_SECONDARY \
  a_swimE_ITEM1 \
  a_swimE_ITEM2 \
  a_swimE_LOSER \
  a_swimE_MELEE \
  a_swimE_MELEE_ALLCLASS \
  a_swimE_PRIMARY \
  a_swimE_SECONDARY \
  a_swimNE_ITEM1 \
  a_swimNE_ITEM2 \
  a_swimNE_LOSER \
  a_swimNE_MELEE \
  a_swimNE_MELEE_ALLCLASS \
  a_swimNE_PRIMARY \
  a_swimNE_SECONDARY \
  a_swimNW_ITEM1 \
  a_swimNW_ITEM2 \
  a_swimNW_LOSER \
  a_swimNW_MELEE \
  a_swimNW_MELEE_ALLCLASS \
  a_swimNW_PRIMARY \
  a_swimNW_SECONDARY \
  a_swimN_ITEM1 \
  a_swimN_ITEM2 \
  a_swimN_LOSER \
  a_swimN_MELEE \
  a_swimN_MELEE_ALLCLASS \
  a_swimN_PRIMARY \
  a_swimN_SECONDARY \
  a_swimSE_ITEM1 \
  a_swimSE_ITEM2 \
  a_swimSE_LOSER \
  a_swimSE_MELEE \
  a_swimSE_MELEE_ALLCLASS \
  a_swimSE_PRIMARY \
  a_swimSE_SECONDARY \
  a_swimSW_ITEM1 \
  a_swimSW_ITEM2 \
  a_swimSW_LOSER \
  a_swimSW_MELEE \
  a_swimSW_MELEE_ALLCLASS \
  a_swimSW_PRIMARY \
  a_swimSW_SECONDARY \
  a_swimS_ITEM1 \
  a_swimS_ITEM2 \
  a_swimS_LOSER \
  a_swimS_MELEE \
  a_swimS_MELEE_ALLCLASS \
  a_swimS_PRIMARY \
  a_swimS_SECONDARY \
  a_swimW_ITEM1 \
  a_swimW_ITEM2 \
  a_swimW_LOSER \
  a_swimW_MELEE \
  a_swimW_MELEE_ALLCLASS \
  a_swimW_PRIMARY \
  a_swimW_SECONDARY \
  a_throw_fire \
  a_vehicle_allclass_center \
  a_vehicle_allclass_lean_center \
  a_vehicle_allclass_lean_neutral \
  a_vehicle_allclass_left \
  a_vehicle_allclass_left_bd \
  a_vehicle_allclass_neutral \
  a_vehicle_allclass_right \
  a_vehicle_allclass_right_bd \
  a_vehicle_lean_backward \
  a_vehicle_lean_forward \
  a_vehicle_moped_center \
  a_vehicle_moped_left \
  a_vehicle_moped_neutral \
  a_vehicle_moped_right \
  a_vehicle_taunt_allclass_center \
  a_vehicle_taunt_allclass_left \
  a_vehicle_taunt_allclass_neutral \
  a_vehicle_taunt_allclass_right \
  airwalk_ITEM1 \
  airwalk_ITEM2 \
  airwalk_LOSER \
  airwalk_MELEE \
  airwalk_MELEE_ALLCLASS \
  airwalk_PRIMARY \
  airwalk_SECONDARY \
  arm_pose_01 \
  armslayer_ITEM1_Crouch_fire \
  armslayer_ITEM1_fire \
  armslayer_throw_fire \
  b_reference \
  bodylayer_ITEM1_Crouch_fire \
  bodylayer_ITEM1_fire \
  bread_bagged_pose \
  bread_baguette_pose \
  bread_burnt_pose \
  bread_cinnamon_pose \
  bread_cornbread_pose \
  bread_crumpet_pose \
  bread_monster_pose \
  bread_pretzel_pose \
  bread_ration_pose \
  bread_robo_pose \
  bread_russianblack_pose \
  bread_shortbread_pose \
  competitive_loserstate_idle \
  competitive_winnerstate_idle \
  crouch_ITEM1 \
  crouch_ITEM2 \
  crouch_LOSER \
  crouch_MELEE \
  crouch_MELEE_ALLCLASS \
  crouch_PRIMARY \
  crouch_SECONDARY \
  dieviolent \
  gesture_ITEM1_cheer \
  gesture_ITEM1_go \
  gesture_ITEM1_help \
  gesture_ITEM1_positive \
  gesture_ITEM2_cheer \
  gesture_ITEM2_go \
  gesture_ITEM2_help \
  gesture_ITEM2_positive \
  gesture_melee_cheer \
  gesture_melee_go \
  gesture_melee_help \
  gesture_melee_positive \
  gesture_primary_cheer \
  gesture_primary_go \
  gesture_primary_help \
  gesture_primary_positive \
  gesture_secondary_cheer \
  gesture_secondary_go \
  gesture_secondary_help \
  gesture_secondary_positive \
  grapple_arm_pose \
  grapple_hand_pose \
  hand_pose_01 \
  hand_pose_02 \
  jumpTest \
  jumplandPose_primary \
  jumpland_ITEM1 \
  jumpland_ITEM2 \
  jumpland_KART \
  jumpland_MELEE_ALLCLASS \
  jumpland_loser \
  jumpland_melee \
  jumpland_primary \
  jumpland_secondary \
  kart_cheer \
  kart_dash \
  kart_idle \
  kart_impact \
  kart_impact_big \
  layer_AttackStandMelee_allclass_arms \
  layer_AttackStandMelee_allclass_runS_arms \
  layer_AttackStandMelee_arms \
  layer_AttackStandMelee_runS_arms \
  layer_ITEM1_WepGrip \
  layer_ITEM2_WepGrip \
  layer_MELEE_WepGrip \
  layer_MELEE_allclass_WepGrip \
  layer_PASSTIME_throw_begin \
  layer_PASSTIME_throw_cancel \
  layer_PASSTIME_throw_end \
  layer_PASSTIME_throw_middle \
  layer_PRIMARY_Stun_begin \
  layer_PRIMARY_Stun_end \
  layer_PRIMARY_stun_middle \
  layer_SECONDARY_WepGrip \
  layer_SECONDARY_crouch_fire_alt \
  layer_SECONDARY_fire_alt \
  layer_SECONDARY_swim_fire_alt \
  layer_STUN_WepGrip \
  layer_dieviolent \
  layer_gesture_ITEM1_cheer_armL \
  layer_gesture_ITEM1_go_armL \
  layer_gesture_ITEM1_help_armL \
  layer_gesture_ITEM1_positive_armL \
  layer_gesture_ITEM2_cheer_armL \
  layer_gesture_ITEM2_go_armL \
  layer_gesture_ITEM2_go_runN_armL \
  layer_gesture_ITEM2_help_armL \
  layer_gesture_ITEM2_positive_armL \
  layer_gesture_melee_cheer_armL \
  layer_gesture_melee_go_armL \
  layer_gesture_melee_help_armL \
  layer_gesture_melee_positive_armL \
  layer_gesture_primary_cheer_armL \
  layer_gesture_primary_go_armL \
  layer_gesture_primary_go_runN_armL \
  layer_gesture_primary_help_armL \
  layer_gesture_primary_positive_armL \
  layer_gesture_secondary_cheer_armL \
  layer_gesture_secondary_go_armL \
  layer_gesture_secondary_go_runN_armL \
  layer_gesture_secondary_help_armL \
  layer_gesture_secondary_positive \
  layer_gesture_secondary_positive_armL \
  layer_gesture_secondary_positive_runN \
  layer_gesture_secondary_positive_runN_armL \
  layer_grapple_SHOOT \
  layer_idleNoise \
  layer_kart_cheer \
  layer_melee_allclass_swing \
  layer_melee_allclass_swing_runS \
  layer_melee_swing \
  layer_melee_swing_runS \
  layer_null \
  layer_placeSapper_ArmL \
  layer_primary_jump_floatNoise \
  layer_reload_standing_arms_item2 \
  layer_reload_standing_arms_primary_end \
  layer_reload_standing_arms_primary_loop \
  layer_reload_standing_arms_primary_start \
  layer_reload_standing_arms_secondary \
  layer_reload_standing_arms_secondary_2 \
  layer_stun_swing \
  layer_stun_swing_S \
  layer_stun_swing_arm_s \
  layer_stun_swing_arms \
  layer_swim_ITEM1_wepGrip \
  layer_swim_MELEE_ALLCLASS_wepGrip \
  layer_swim_MELEE_wepGrip \
  layer_swim_SECONDARY_wepGrip \
  layer_taunt01 \
  layer_taunt01_Alt \
  layer_taunt04 \
  layer_taunt_bat_man \
  layer_taunt_chicken \
  layer_taunt_come_and_get_me \
  layer_taunt_cyoa_PDA_intro \
  layer_taunt_cyoa_PDA_outro \
  layer_taunt_dosido_dance \
  layer_taunt_dosido_intro \
  layer_taunt_flip_success_initiator \
  layer_taunt_flip_success_receiver \
  layer_taunt_freshbeats \
  layer_taunt_headbutt_start \
  layer_taunt_headbutt_success \
  layer_taunt_highFiveSuccess \
  layer_taunt_highFiveSuccessFull \
  layer_taunt_laugh \
  layer_taunt_rps_paper_lose \
  layer_taunt_rps_paper_win \
  layer_taunt_rps_rock_lose \
  layer_taunt_rps_rock_win \
  layer_taunt_rps_scissors_lose \
  layer_taunt_rps_scissors_win \
  layer_taunt_vehicle_allclass_end \
  layer_taunt_vehicle_allclass_honk \
  layer_taunt_vehicle_allclass_spawn \
  layer_taunt_wheely \
  layer_taunt_wheely_steer \
  layer_taunt_yeti_prop \
  layer_taunt_yetipunch \
  layer_tuant_vehicle_moped_end \
  primary_death_backstab \
  primary_death_burning \
  primary_death_headshot \
  r_handposes \
  ragdollspawn \
  saxxy_pose \
  scout_taunt_replay \
  selectionMenu_Anim01 \
  selectionMenu_Idle \
  selectionMenu_StartPose \
  selectionMenu_all \
  stand_ITEM1 \
  stand_ITEM2 \
  stand_LOSER \
  stand_MELEE \
  stand_MELEE_ALLCLASS \
  stand_PASSTIME \
  stand_PRIMARY \
  stand_SECONDARY \
  stand_STUN \
  stun_swing \
  stun_swing_crouch \
  taunt01 \
  taunt01_Alt \
  taunt02 \
  taunt03 \
  taunt04 \
  taunt05 \
  taunt06 \
  taunt_aerobic_A \
  taunt_aerobic_A_START \
  taunt_aerobic_B \
  taunt_aerobic_B_START \
  taunt_bat_man \
  taunt_brutallegend \
  taunt_brutallegendin \
  taunt_brutallegendinblend \
  taunt_brutallegendinterior \
  taunt_brutallegendout \
  taunt_brutallegendoutblend \
  taunt_chicken \
  taunt_come_and_get_me \
  taunt_conga \
  taunt_cyoa_PDA_idle \
  taunt_cyoa_PDA_intro \
  taunt_cyoa_PDA_outro \
  taunt_dosido_dance \
  taunt_dosido_intro \
  taunt_flip_start \
  taunt_flip_success_initiator \
  taunt_flip_success_receiver \
  taunt_freshbeats \
  taunt_headbutt_start \
  taunt_headbutt_success \
  taunt_highFiveStart \
  taunt_highFiveStart_idle \
  taunt_highFiveSuccess \
  taunt_highFiveSuccessFull \
  taunt_laugh \
  taunt_rps_paper_lose \
  taunt_rps_paper_win \
  taunt_rps_rock_lose \
  taunt_rps_rock_win \
  taunt_rps_scissors_lose \
  taunt_rps_scissors_win \
  taunt_rps_start \
  taunt_russian \
  taunt_vehicle_allclass_end \
  taunt_vehicle_allclass_honk \
  taunt_vehicle_allclass_start \
  taunt_vehicle_allclass_start_layer \
  taunt_vehicle_moped_end \
  taunt_vehicle_moped_spawn_layer \
  taunt_vehicle_moped_start \
  taunt_vehicle_moped_start_layer \
  taunt_vehicle_moped_wheely \
  taunt_yeti \
  taunt_yeti_layer \
  taunt_yetipunch \
  throw_fire

#begin blender_char_egg
  #define BLENDER_PREFIX scout-
  #define EGG_PREFIX scout-
  #define POLY_MODEL zero
  #define CHAR_NAME scout.qc_skeleton
  #define ANIMS_DIR anims
  #define ANIMS $[SCOUT_ANIMS]
#end blender_char_egg

#begin optchar_egg
  #define TARGET_DIR optchar
  #define SOURCES \
    scout-zero.egg \
    $[matrix anims/scout-,$[SCOUT_ANIMS],.egg]

  #define OPTCHAR_OPTS \
    -keepall \
    -drop hlp_forearm_L,hlp_forearm_R \
    -flag scout_morphs_low,scout_morphs_low_lod1,scout_morphs_low_lod2,scout_morphs_low_lod3,scout_morphs_low_lod4,scout_morphs_low_lod5 \
    -flag scout_physics

#end optchar_egg

#begin install_mdl
  #define SOURCES \
    scout.pmdl

#end install_mdl
