#define DIR_TYPE models
#define INSTALL_TO models/char

#begin install_mat
  #define SOURCES \
    eyeball_r_spy.pmat eyeball_l_spy.pmat

#end install_mat

#define SPY_ANIMS \
  AttackCrouch_SECONDARY \
  AttackStand_SECONDARY \
  AttackSwim_SECONDARY \
  Melee_Crouch_Swing \
  Melee_Overhand_Swing \
  Melee_Swim_Swing \
  Melee_Swing \
  PDA_Crouch_fire \
  PDA_fire \
  PDA_run_fire \
  PRIMARY_Stun_begin \
  PRIMARY_stun_end \
  PRIMARY_stun_middle \
  ReloadAirwalk_SECONDARY \
  ReloadCrouch_SECONDARY \
  ReloadStand_SECONDARY \
  ReloadSwim_SECONDARY \
  SAPPER_placeSapper \
  SECONDARY_placeSapper \
  SelectionMenu_Anim01 \
  SelectionMenu_Idle \
  SelectionMenu_StartPose \
  a_MELEE_aimmatrix_crouch_idle_down_center \
  a_MELEE_aimmatrix_crouch_idle_down_left \
  a_MELEE_aimmatrix_crouch_idle_down_right \
  a_MELEE_aimmatrix_crouch_idle_mid_center \
  a_MELEE_aimmatrix_crouch_idle_mid_left \
  a_MELEE_aimmatrix_crouch_idle_mid_right \
  a_MELEE_aimmatrix_crouch_idle_neutral \
  a_MELEE_aimmatrix_crouch_idle_straight_up \
  a_MELEE_aimmatrix_crouch_idle_up_center \
  a_MELEE_aimmatrix_crouch_idle_up_left \
  a_MELEE_aimmatrix_crouch_idle_up_right \
  a_MELEE_aimmatrix_idle_down_center \
  a_MELEE_aimmatrix_idle_down_left \
  a_MELEE_aimmatrix_idle_down_right \
  a_MELEE_aimmatrix_idle_mid_center \
  a_MELEE_aimmatrix_idle_mid_left \
  a_MELEE_aimmatrix_idle_mid_right \
  a_MELEE_aimmatrix_idle_neutral \
  a_MELEE_aimmatrix_idle_straight_up \
  a_MELEE_aimmatrix_idle_up_center \
  a_MELEE_aimmatrix_idle_up_left \
  a_MELEE_aimmatrix_idle_up_right \
  a_MELEE_aimmatrix_run_down_center \
  a_MELEE_aimmatrix_run_down_left \
  a_MELEE_aimmatrix_run_down_right \
  a_MELEE_aimmatrix_run_mid_center \
  a_MELEE_aimmatrix_run_mid_left \
  a_MELEE_aimmatrix_run_mid_right \
  a_MELEE_aimmatrix_run_neutral \
  a_MELEE_aimmatrix_run_straight_up \
  a_MELEE_aimmatrix_run_up_center \
  a_MELEE_aimmatrix_run_up_left \
  a_MELEE_aimmatrix_run_up_right \
  a_MELEE_aimmatrix_swim_down_center \
  a_MELEE_aimmatrix_swim_down_left \
  a_MELEE_aimmatrix_swim_down_right \
  a_MELEE_aimmatrix_swim_mid_center \
  a_MELEE_aimmatrix_swim_mid_left \
  a_MELEE_aimmatrix_swim_mid_right \
  a_MELEE_aimmatrix_swim_neutral \
  a_MELEE_aimmatrix_swim_straight_up \
  a_MELEE_aimmatrix_swim_up_center \
  a_MELEE_aimmatrix_swim_up_left \
  a_MELEE_aimmatrix_swim_up_right \
  a_Melee_Crouch_Swing \
  a_Melee_Overhand_Swing \
  a_Melee_Swim_Swing \
  a_Melee_Swing \
  a_PDA_Crouch_fire \
  a_PDA_aimmatrix_crouch_idle_down_center \
  a_PDA_aimmatrix_crouch_idle_down_left \
  a_PDA_aimmatrix_crouch_idle_down_right \
  a_PDA_aimmatrix_crouch_idle_mid_center \
  a_PDA_aimmatrix_crouch_idle_mid_left \
  a_PDA_aimmatrix_crouch_idle_mid_right \
  a_PDA_aimmatrix_crouch_idle_neutral \
  a_PDA_aimmatrix_crouch_idle_straight_up \
  a_PDA_aimmatrix_crouch_idle_up_center \
  a_PDA_aimmatrix_crouch_idle_up_left \
  a_PDA_aimmatrix_crouch_idle_up_right \
  a_PDA_aimmatrix_idle_down_center \
  a_PDA_aimmatrix_idle_down_left \
  a_PDA_aimmatrix_idle_down_right \
  a_PDA_aimmatrix_idle_mid_center \
  a_PDA_aimmatrix_idle_mid_left \
  a_PDA_aimmatrix_idle_mid_right \
  a_PDA_aimmatrix_idle_neutral \
  a_PDA_aimmatrix_idle_straight_up \
  a_PDA_aimmatrix_idle_up_center \
  a_PDA_aimmatrix_idle_up_left \
  a_PDA_aimmatrix_idle_up_right \
  a_PDA_aimmatrix_run_down_center \
  a_PDA_aimmatrix_run_down_left \
  a_PDA_aimmatrix_run_down_right \
  a_PDA_aimmatrix_run_mid_center \
  a_PDA_aimmatrix_run_mid_left \
  a_PDA_aimmatrix_run_mid_right \
  a_PDA_aimmatrix_run_neutral \
  a_PDA_aimmatrix_run_straight_up \
  a_PDA_aimmatrix_run_up_center \
  a_PDA_aimmatrix_run_up_left \
  a_PDA_aimmatrix_run_up_right \
  a_PDA_aimmatrix_swim_down_center \
  a_PDA_aimmatrix_swim_down_left \
  a_PDA_aimmatrix_swim_down_right \
  a_PDA_aimmatrix_swim_mid_center \
  a_PDA_aimmatrix_swim_mid_left \
  a_PDA_aimmatrix_swim_mid_right \
  a_PDA_aimmatrix_swim_neutral \
  a_PDA_aimmatrix_swim_straight_up \
  a_PDA_aimmatrix_swim_up_center \
  a_PDA_aimmatrix_swim_up_left \
  a_PDA_aimmatrix_swim_up_right \
  a_PDA_fire \
  a_PDA_run_fire \
  a_SAPPER_aimmatrix_crouch_idle_down_center \
  a_SAPPER_aimmatrix_crouch_idle_down_left \
  a_SAPPER_aimmatrix_crouch_idle_down_right \
  a_SAPPER_aimmatrix_crouch_idle_mid_center \
  a_SAPPER_aimmatrix_crouch_idle_mid_left \
  a_SAPPER_aimmatrix_crouch_idle_mid_right \
  a_SAPPER_aimmatrix_crouch_idle_neutral \
  a_SAPPER_aimmatrix_crouch_idle_straight_up \
  a_SAPPER_aimmatrix_crouch_idle_up_center \
  a_SAPPER_aimmatrix_crouch_idle_up_left \
  a_SAPPER_aimmatrix_crouch_idle_up_right \
  a_SAPPER_aimmatrix_idle_down_center \
  a_SAPPER_aimmatrix_idle_down_left \
  a_SAPPER_aimmatrix_idle_down_right \
  a_SAPPER_aimmatrix_idle_mid_center \
  a_SAPPER_aimmatrix_idle_mid_left \
  a_SAPPER_aimmatrix_idle_mid_right \
  a_SAPPER_aimmatrix_idle_neutral \
  a_SAPPER_aimmatrix_idle_straight_up \
  a_SAPPER_aimmatrix_idle_up_center \
  a_SAPPER_aimmatrix_idle_up_left \
  a_SAPPER_aimmatrix_idle_up_right \
  a_SAPPER_aimmatrix_run_down_center \
  a_SAPPER_aimmatrix_run_down_left \
  a_SAPPER_aimmatrix_run_down_right \
  a_SAPPER_aimmatrix_run_mid_center \
  a_SAPPER_aimmatrix_run_mid_left \
  a_SAPPER_aimmatrix_run_mid_right \
  a_SAPPER_aimmatrix_run_neutral \
  a_SAPPER_aimmatrix_run_straight_up \
  a_SAPPER_aimmatrix_run_up_center \
  a_SAPPER_aimmatrix_run_up_left \
  a_SAPPER_aimmatrix_run_up_right \
  a_SAPPER_aimmatrix_swim_down_center \
  a_SAPPER_aimmatrix_swim_down_left \
  a_SAPPER_aimmatrix_swim_down_right \
  a_SAPPER_aimmatrix_swim_mid_center \
  a_SAPPER_aimmatrix_swim_mid_left \
  a_SAPPER_aimmatrix_swim_mid_right \
  a_SAPPER_aimmatrix_swim_neutral \
  a_SAPPER_aimmatrix_swim_straight_up \
  a_SAPPER_aimmatrix_swim_up_center \
  a_SAPPER_aimmatrix_swim_up_left \
  a_SAPPER_aimmatrix_swim_up_right \
  a_SECONDARY_aimmatrix_crouch_idle_down_center \
  a_SECONDARY_aimmatrix_crouch_idle_down_left \
  a_SECONDARY_aimmatrix_crouch_idle_down_right \
  a_SECONDARY_aimmatrix_crouch_idle_mid_center \
  a_SECONDARY_aimmatrix_crouch_idle_mid_left \
  a_SECONDARY_aimmatrix_crouch_idle_mid_right \
  a_SECONDARY_aimmatrix_crouch_idle_neutral \
  a_SECONDARY_aimmatrix_crouch_idle_straight_up \
  a_SECONDARY_aimmatrix_crouch_idle_up_center \
  a_SECONDARY_aimmatrix_crouch_idle_up_left \
  a_SECONDARY_aimmatrix_crouch_idle_up_right \
  a_SECONDARY_aimmatrix_idle_down_center \
  a_SECONDARY_aimmatrix_idle_down_left \
  a_SECONDARY_aimmatrix_idle_down_right \
  a_SECONDARY_aimmatrix_idle_mid_center \
  a_SECONDARY_aimmatrix_idle_mid_left \
  a_SECONDARY_aimmatrix_idle_mid_right \
  a_SECONDARY_aimmatrix_idle_neutral \
  a_SECONDARY_aimmatrix_idle_straight_up \
  a_SECONDARY_aimmatrix_idle_up_center \
  a_SECONDARY_aimmatrix_idle_up_left \
  a_SECONDARY_aimmatrix_idle_up_right \
  a_SECONDARY_aimmatrix_run_down_center \
  a_SECONDARY_aimmatrix_run_down_left \
  a_SECONDARY_aimmatrix_run_down_right \
  a_SECONDARY_aimmatrix_run_mid_center \
  a_SECONDARY_aimmatrix_run_mid_left \
  a_SECONDARY_aimmatrix_run_mid_right \
  a_SECONDARY_aimmatrix_run_neutral \
  a_SECONDARY_aimmatrix_run_straight_up \
  a_SECONDARY_aimmatrix_run_up_center \
  a_SECONDARY_aimmatrix_run_up_left \
  a_SECONDARY_aimmatrix_run_up_right \
  a_SECONDARY_aimmatrix_swim_down_center \
  a_SECONDARY_aimmatrix_swim_down_left \
  a_SECONDARY_aimmatrix_swim_down_right \
  a_SECONDARY_aimmatrix_swim_mid_center \
  a_SECONDARY_aimmatrix_swim_mid_left \
  a_SECONDARY_aimmatrix_swim_mid_right \
  a_SECONDARY_aimmatrix_swim_neutral \
  a_SECONDARY_aimmatrix_swim_straight_up \
  a_SECONDARY_aimmatrix_swim_up_center \
  a_SECONDARY_aimmatrix_swim_up_left \
  a_SECONDARY_aimmatrix_swim_up_right \
  a_blend_crouchN_crouch_walk_PDA \
  a_blend_crouchN_crouch_walk_SAPPER \
  a_blend_crouchN_crouch_walk_SECONDARY \
  a_crouch_walkCenter_MELEE \
  a_crouch_walkCenter_crouch_walk_PDA \
  a_crouch_walkCenter_crouch_walk_SAPPER \
  a_crouch_walkCenter_crouch_walk_SECONDARY \
  a_crouch_walkE_MELEE \
  a_crouch_walkE_crouch_walk_PDA \
  a_crouch_walkE_crouch_walk_SAPPER \
  a_crouch_walkE_crouch_walk_SECONDARY \
  a_crouch_walkNE_MELEE \
  a_crouch_walkNE_crouch_walk_PDA \
  a_crouch_walkNE_crouch_walk_SAPPER \
  a_crouch_walkNE_crouch_walk_SECONDARY \
  a_crouch_walkNW_MELEE \
  a_crouch_walkNW_crouch_walk_PDA \
  a_crouch_walkNW_crouch_walk_SAPPER \
  a_crouch_walkNW_crouch_walk_SECONDARY \
  a_crouch_walkN_MELEE \
  a_crouch_walkN_crouch_walk_PDA \
  a_crouch_walkN_crouch_walk_SAPPER \
  a_crouch_walkN_crouch_walk_SECONDARY \
  a_crouch_walkSE_MELEE \
  a_crouch_walkSE_crouch_walk_PDA \
  a_crouch_walkSE_crouch_walk_SAPPER \
  a_crouch_walkSE_crouch_walk_SECONDARY \
  a_crouch_walkSW_MELEE \
  a_crouch_walkSW_crouch_walk_PDA \
  a_crouch_walkSW_crouch_walk_SAPPER \
  a_crouch_walkSW_crouch_walk_SECONDARY \
  a_crouch_walkS_MELEE \
  a_crouch_walkS_crouch_walk_PDA \
  a_crouch_walkS_crouch_walk_SAPPER \
  a_crouch_walkS_crouch_walk_SECONDARY \
  a_crouch_walkW_MELEE \
  a_crouch_walkW_crouch_walk_PDA \
  a_crouch_walkW_crouch_walk_SAPPER \
  a_crouch_walkW_crouch_walk_SECONDARY \
  a_flinch01 \
  a_jumpfloat_LOSER \
  a_jumpfloat_MELEE \
  a_jumpfloat_PDA \
  a_jumpfloat_SAPPER \
  a_jumpfloat_SECONDARY \
  a_jumpstart_LOSER \
  a_jumpstart_MELEE \
  a_jumpstart_PDA \
  a_jumpstart_SAPPER \
  a_jumpstart_SECONDARY \
  a_reference \
  a_runCenter_LOSER \
  a_runCenter_MELEE \
  a_runCenter_PDA \
  a_runCenter_SAPPER \
  a_runCenter_SECONDARY \
  a_runE_LOSER \
  a_runE_MELEE \
  a_runE_PDA \
  a_runE_SAPPER \
  a_runE_SECONDARY \
  a_runNE_LOSER \
  a_runNE_MELEE \
  a_runNE_PDA \
  a_runNE_SAPPER \
  a_runNE_SECONDARY \
  a_runNW_LOSER \
  a_runNW_MELEE \
  a_runNW_PDA \
  a_runNW_SAPPER \
  a_runNW_SECONDARY \
  a_runN_LOSER \
  a_runN_MELEE \
  a_runN_PDA \
  a_runN_SAPPER \
  a_runN_SECONDARY \
  a_runSE_LOSER \
  a_runSE_MELEE \
  a_runSE_PDA \
  a_runSE_SAPPER \
  a_runSE_SECONDARY \
  a_runSW_LOSER \
  a_runSW_MELEE \
  a_runSW_PDA \
  a_runSW_SAPPER \
  a_runSW_SECONDARY \
  a_runS_LOSER \
  a_runS_MELEE \
  a_runS_PDA \
  a_runS_SAPPER \
  a_runS_SECONDARY \
  a_runW_LOSER \
  a_runW_MELEE \
  a_runW_PDA \
  a_runW_SAPPER \
  a_runW_SECONDARY \
  a_stun_endpose \
  a_stun_startpose \
  a_swimCenter_LOSER \
  a_swimCenter_MELEE \
  a_swimCenter_PDA \
  a_swimCenter_SAPPER \
  a_swimCenter_SECONDARY \
  a_swimE_LOSER \
  a_swimE_MELEE \
  a_swimE_PDA \
  a_swimE_SAPPER \
  a_swimE_SECONDARY \
  a_swimNE_LOSER \
  a_swimNE_MELEE \
  a_swimNE_PDA \
  a_swimNE_SAPPER \
  a_swimNE_SECONDARY \
  a_swimNW_LOSER \
  a_swimNW_MELEE \
  a_swimNW_PDA \
  a_swimNW_SAPPER \
  a_swimNW_SECONDARY \
  a_swimN_LOSER \
  a_swimN_MELEE \
  a_swimN_PDA \
  a_swimN_SAPPER \
  a_swimN_SECONDARY \
  a_swimSE_LOSER \
  a_swimSE_MELEE \
  a_swimSE_PDA \
  a_swimSE_SAPPER \
  a_swimSE_SECONDARY \
  a_swimSW_LOSER \
  a_swimSW_MELEE \
  a_swimSW_PDA \
  a_swimSW_SAPPER \
  a_swimSW_SECONDARY \
  a_swimS_LOSER \
  a_swimS_MELEE \
  a_swimS_PDA \
  a_swimS_SAPPER \
  a_swimS_SECONDARY \
  a_swimW_LOSER \
  a_swimW_MELEE \
  a_swimW_PDA \
  a_swimW_SAPPER \
  a_swimW_SECONDARY \
  airwalk_LOSER \
  airwalk_MELEE \
  airwalk_PDA \
  airwalk_SAPPER \
  airwalk_SECONDARY \
  arm_pose_01 \
  armslayer_PDA_Crouch_fire \
  armslayer_PDA_fire \
  armslayer_PDA_run_fire \
  armslayer_melee_Crouch_swing \
  armslayer_melee_Overhand_swing \
  armslayer_melee_Swim_swing \
  armslayer_melee_swing \
  bodylayer_Melee_Crouch_Swing \
  bodylayer_Melee_Overhand_Swing \
  bodylayer_Melee_Swim_Swing \
  bodylayer_Melee_Swing \
  bodylayer_PDA_Crouch_fire \
  bodylayer_PDA_fire \
  bodylayer_PDA_run_fire \
  crouch_LOSER \
  crouch_MELEE \
  crouch_PDA \
  crouch_SAPPER \
  crouch_SECONDARY \
  dieviolent \
  gesture_PDA_cheer \
  gesture_PDA_go \
  gesture_PDA_help \
  gesture_PDA_positive \
  gesture_melee_cheer \
  gesture_melee_go \
  gesture_melee_help \
  gesture_melee_positive \
  gesture_secondary_cheer \
  gesture_secondary_go \
  gesture_secondary_help \
  gesture_secondary_positive \
  jumplandPose_LOSER \
  jumplandPose_MELEE \
  jumplandPose_PDA \
  jumplandPose_SAPPER \
  jumplandPose_SECONDARY \
  jumpland_LOSER \
  jumpland_MELEE \
  jumpland_PDA \
  jumpland_SAPPER \
  jumpland_SECONDARY \
  layer_PRIMARY_Stun_begin \
  layer_PRIMARY_Stun_end \
  layer_PRIMARY_stun_middle \
  layer_a_placeSapper_ArmL \
  layer_dieviolent \
  layer_gesture_PDA_cheer_armL \
  layer_gesture_PDA_cheer_runN_armL \
  layer_gesture_PDA_go_armL \
  layer_gesture_PDA_go_runN_armL \
  layer_gesture_PDA_help_armL \
  layer_gesture_PDA_help_runN_armL \
  layer_gesture_PDA_positive_armL \
  layer_gesture_PDA_positive_runN_armL \
  layer_gesture_melee_cheer_armL \
  layer_gesture_melee_cheer_runN_armL \
  layer_gesture_melee_go_armL \
  layer_gesture_melee_go_runN_armL \
  layer_gesture_melee_help_armL \
  layer_gesture_melee_help_runN_armL \
  layer_gesture_melee_positive_armL \
  layer_gesture_melee_positive_runN_armL \
  layer_gesture_secondary_cheer_armL \
  layer_gesture_secondary_go_armL \
  layer_gesture_secondary_go_runN_armL \
  layer_gesture_secondary_help_armL \
  layer_gesture_secondary_positive_armL \
  layer_placeSapper_ArmL \
  layer_reload_airwalk_arms_SECONDARY \
  layer_reload_crouching_arms_SECONDARY \
  layer_reload_standing_arms_SECONDARY \
  layer_reload_swimming_arms_SECONDARY \
  layer_taunt03 \
  layer_taunt04 \
  layer_taunt05 \
  primary_death_backstab \
  primary_death_burning \
  primary_death_headshot \
  r_handposes \
  secondary_taunt \
  stand_LOSER \
  stand_MELEE \
  stand_PDA \
  stand_SAPPER \
  stand_SECONDARY \
  taunt01 \
  taunt03 \
  taunt04 \
  taunt05 \
  taunt06 \
  x_runSE_PDA \
  x_runSW_PDA \
  x_runS_PDA

#begin blender_char_egg
  #define BLENDER_PREFIX spy-
  #define EGG_PREFIX spy-
  #define POLY_MODEL zero
  #define CHAR_NAME spy.qc_skeleton
  #define ANIMS_DIR anims
  #define ANIMS $[SPY_ANIMS]

#end blender_char_egg

#begin optchar_egg
  #define TARGET_DIR optchar
  #define SOURCES \
    spy-zero.egg \
    $[matrix anims/spy-,$[SPY_ANIMS],.egg]

  #define OPTCHAR_OPTS \
    -keepall \
    -flag spy_morphs_low,spy_morphs_low_lod1,spy_morphs_low_lod2,spy_morphs_low_lod3,spy_morphs_low_lod4,spy_morphs_low_lod5 \
    -flag spy_mask,spy_mask_lod1,spy_mask_lod2,spy_mask_lod3,spy_mask_lod4,spy_mask_lod5 \
    -flag spy_physics

#end optchar_egg

#begin install_mdl
  #define SOURCES \
    spy.pmdl

#end install_mdl
