#define DIR_TYPE models

#begin install_mat
  #define SOURCES \
    engineer_red.pmat \
    engineer_blue.pmat \
    engineer_head.pmat \
    soldier_red.pmat \
    soldier_blue.pmat \
    soldier_head.pmat \
    mini_sentry_blue.pmat \
    mini_sentry_light_blue.pmat \
    mini_sentry_light_red.pmat \
    mini_sentry_red.pmat \
    sentry1.pmat \
    sentry1_blue.pmat \
    sentry1_gibs.pmat \
    sentry1_gibs_blue.pmat \
    sentry2.pmat \
    sentry2_blue.pmat \
    sentry2_gibs.pmat \
    sentry2_gibs_blue.pmat \
    soldier_statue.pmat \
    train_boxcar.pmat \
    spotlight001a.pmat \
    spotlight001a_off.pmat \
    spotlight001a_blue.pmat \
    spotlight001a_blue_off.pmat \
    spotlight001a_grey.pmat \
    spotlight001a_grey_off.pmat \
    lights.pmat \
    security_camera.pmat \
    groundlight001_sheet.pmat \
    computer_wall05.pmat \
    computer_wall05b.pmat \
    computer_wall06.pmat \
    computer_wall06b.pmat \
    vent_system01.pmat \
    lightbulb001.pmat \
    lightbulb001_off.pmat \
    tools.pmat \
    fence001.pmat \
    telephonepole001.pmat \
    hanging_ceiling_lamp.pmat \
    gutters001.pmat \
    gutters001a.pmat \
    window002.pmat \
    window002b.pmat \
    window002_warm1.pmat \
    window001.pmat \
    window001b.pmat \
    window001_warm1.pmat \
    door_slide_large.pmat \
    door_slide.pmat \
    door_slide_large_noentry.pmat \
    chimney004.pmat \
    steps_pipes_piece.pmat \
    security_fence_big.pmat \
    security_fence_alpha.pmat \
    spawnroom_door.pmat \
    walllight001a.pmat \
    walllight001a_off.pmat \
    walllight001a_blue.pmat \
    walllight001a_blue_off.pmat \
    walllight001a_grey.pmat \
    walllight001a_grey_off.pmat \
    wood_floor001.pmat \
    grain_elevator01.pmat \
    window005.pmat \
    window005b.pmat \
    window006b.pmat \
    conveyor_belt.pmat \
    grainconveyor001.pmat \
    wooden_rail01.pmat \
    junction_box.pmat \
    vent001.pmat \
    shelf_props01.pmat \
    shelf_props01_skin2.pmat \
    ceiling_pipe01.pmat \
    ceiling_pipe01_skin2.pmat \
    foot_spray_can01.pmat \
    pill_bottle01.pmat \
    conduit.pmat \
    computer_wall_cabinet.pmat \
    work_table001.pmat \
    chimney006.pmat \
    barbfence001.pmat \
    rafter_01a.pmat \
    windmill001.pmat \
    spool_rope.pmat \
    wooden_barrel.pmat \
    wood_pile.pmat \
    haypile001.pmat \
    haypile001_card.pmat \
    wall_clock.pmat \
    wall_clock_glass.pmat \
    watercooler_sheet.pmat \
    watercooler_bottle.pmat \
    silo_cluster01a.pmat \
    lights_off.pmat \
    intercom.pmat \
    time_card_machine002.pmat \
    time_card_machine.pmat \
    computer_printer.pmat \
    computer_printer002.pmat \
    computer_printer_red_worn.pmat \
    computer_printer_blue_worn.pmat \
    outlet.pmat \
    window003.pmat \
    window003b.pmat \
    window003_warm1.pmat \
    ceiling_conduit.pmat \
    miningcrate001.pmat \
    nail001.pmat \
    lantern_glass001_off.pmat \
    lantern001_off.pmat \
    metalbucket001.pmat \
    horseshoe001.pmat \
    miningcrate002.pmat \
    pick001.pmat \
    cow001.pmat \
    telephone001.pmat \
    crane002.pmat \
    cranehook001.pmat \
    board002.pmat \
    board001.pmat \
    vent.pmat \
    chimney005.pmat \
    sign001.pmat \
    corrugated_metal003.pmat \
    corrugated_metal001.pmat \
    corrugated_metal002.pmat \
    weathervane001.pmat \
    lunchbag.pmat \
    waste_basket01.pmat \
    thermos.pmat \
    corkboard01.pmat \
    grain_elevator04.pmat \
    silo001.pmat \
    tree001_card.pmat \
    tree001_card_skin2.pmat \
    chimney003.pmat \
    lamp001.pmat \
    lamp001_off.pmat \
    exit_sign01.pmat \
    spool_wire.pmat \
    blue_window001.pmat \
    rock_worn001.pmat \
    metal_pile.pmat \
    floodlight001.pmat \
    siren.pmat \
    siren_skin2.pmat \
    factory_pipe004.pmat \
    wood_bridge001.pmat \
    wood_bridge002.pmat \
    crank01.pmat \
    crank02.pmat \
    rafters001.pmat \
    wood_wall002.pmat \
    wood_beam01.pmat \
    wall027.pmat \
    wood_beam02.pmat \
    wood_beam03.pmat \
    wall026.pmat \
    wood_wall005a.pmat \
    window006.pmat \
    propane_tank_tall01.pmat \
    shelf_props02.pmat \
    junctionbox01.pmat \
    barbell01.pmat \
    tape_wrap01.pmat \
    towel_rack01.pmat \
    bench001a.pmat \
    sign_gameplay01_skin1.pmat \
    sign_gameplay01_skin2.pmat \
    sign_gameplay01_skin3.pmat \
    sign_gameplay01_skin4.pmat \
    sign_gameplay01_skin5.pmat \
    sign_gameplay01_skin6.pmat \
    sign_gameplay01_skin7.pmat \
    sign_gameplay01_skin8.pmat \
    sign_gameplay01_skin9.pmat \
    sign_gameplay01_skin10.pmat \
    sign_gameplay01_skin11.pmat \
    sign_gameplay01_skin12.pmat \
    blast_door_frame01.pmat \
    doorframe002a.pmat \
    blue_window001_glass.pmat \
    tracks001.pmat \
    silo_skybox004.pmat \
    silo002.pmat \
    doorframe003.pmat \
    grain_elevator_facade_14b.pmat \
    coffeepot.pmat \
    lamp002.pmat \
    lamp002_skin1.pmat \
    chalkboard01.pmat \
    chalkboard01_skin1.pmat \
    floodlight001b.pmat \
    door_grate001.pmat \
    handrail128.pmat \
    handrail128_skin2.pmat \
    handrail128_skin3.pmat \
    handrail128_skin4.pmat \
    window004.pmat \
    train_engine.pmat \
    train_engine_01.pmat \
    factory_pipe003.pmat \
    factory_pipe005.pmat \
    window009.pmat \
    window009c.pmat \
    window009_warm1.pmat \
    blast_furnace001.pmat \
    metal_barrier01.pmat \
    rock006.pmat \
    sign_wood_cap001a.pmat \
    sign_wood_cap001b.pmat \
    sign_wood_cap001c.pmat \
    sign_wood_cap_redcart.pmat \
    sign_wood_cap_bluecart.pmat \
    sign_wood_cap001a_blue.pmat \
    sign_wood_cap001b_blue.pmat \
    sign_wood_cap001c_blue.pmat \
    handrail128_skin5.pmat \
    rock007.pmat \
    rock007a.pmat \
    rock007b.pmat \
    rock007c.pmat \
    rock005.pmat \
    rock005a.pmat \
    rock005b.pmat \
    rock003.pmat \
    rock003a.pmat \
    rock003b.pmat \
    rock001_skybox.pmat \
    rock006a.pmat \
    rock006b.pmat \
    shrub_03.pmat \
    shrub_03_snow.pmat \
    rock002_skybox.pmat \
    blast_furnace002.pmat \
    industrial_pipe01.pmat \
    concrete_block001.pmat \
    corrugated_metal004.pmat \
    lamp002_off.pmat \
    wall_map.pmat \
    chimney001.pmat \
    hardhat001.pmat \
    ladder001.pmat \
    cart_base_separate.pmat \
    pallet001.pmat \
    fire_bell01.pmat \
    wood_fence_short_128.pmat \
    chicken_wire.pmat \
    wood_fence_short_128b.pmat \
    barrel_crate.pmat \
    milk_crate.pmat \
    cart_bomb_separate.pmat \
    target_demoman.pmat \
    target_demoman_blu.pmat \
    target_pyro.pmat \
    target_pyro_blu.pmat \
    target_engineer.pmat \
    target_engineer_blu.pmat \
    target_spy.pmat \
    target_spy_blu.pmat \
    target_soldier.pmat \
    target_soldier_blu.pmat \
    wood_fence_128.pmat \
    wood_fence_128b.pmat \
    waste_elevator.pmat \
    sign_barricade001a.pmat \
    barrel01.pmat \
    wood_pallet.pmat \
    track_mining.pmat \
    track_mining_blue.pmat \
    hand_truck01.pmat \
    hand_truck01_skin2.pmat \
    cart_base.pmat \
    cart_bomb.pmat \
    cart_dispenser.pmat \
    terminal_chair.pmat \
    terminal_chair_blue.pmat \
    terminal_chair_red_worn.pmat \
    terminal_chair_blue_worn.pmat \
    oildrum001.pmat \
    oildrum002.pmat \
    oildrum003.pmat \
    oildrum004.pmat \
    oildrum005.pmat \
    oildrum006.pmat \
    siren001.pmat \
    siren001b.pmat \
    water_pipes.pmat \
    2pipe.pmat \
    computer_wall02.pmat \
    mop_and_bucket01.pmat \
    fire_extinguisher.pmat \
    tire001.pmat \
    trainwheel001.pmat \
    computer_cart01.pmat \
    computer_wall.pmat \
    computer_wallb.pmat \
    computer_wall_red_worn.pmat \
    computer_wall_blue_worn.pmat \
    computer_wall04.pmat \
    computer_wall04b.pmat \
    computer_wall04_red_worn.pmat \
    computer_wall04_blue_worn.pmat \
    computer_wall03.pmat \
    computer_wall03b.pmat \
    computer_wall03_red_worn.pmat \
    computer_wall03_blue_worn.pmat \
    computer_low.pmat \
    computer_lowb.pmat \
    control_room_consoles.pmat \
    control_room_consoles_skin2.pmat \
    control_room_consoles_red_worn.pmat \
    control_room_consoles_blue_worn.pmat \
    coffeemaker.pmat \
    haybale.pmat \
    conduit_outdoor01.pmat \
    train_orecar.pmat \
    pickup03.pmat \
    pickup04.pmat \
    grain_sack_red.pmat \
    grain_sack_blue.pmat \
    house001.pmat \
    air_intake.pmat \
    water_spigot.pmat \
    sniper_fence01_red.pmat \
    sniper_fence01_blue.pmat \
    desk.pmat \
    spytech_roofbeam001.pmat \
    spytech_roofbeam001b.pmat \
    spytech_roofbeam02.pmat \
    spytech_roofbeam02b.pmat \
    spytech_roofbeam03.pmat \
    spytech_roofbeam03b.pmat \
    spytech_roofbeam04.pmat \
    spytech_roofbeam04b.pmat \
    blast_door.pmat \
    reel_rack.pmat \
    flag_room_glass_door_frame.pmat \
    milkjug001.pmat \
    bullskull001.pmat \
    hose001.pmat \
    wagonwheel001.pmat \
    tv001.pmat \
    tractor_tire001.pmat \
    tank001.pmat \
    drain_pipe001.pmat \
    waterpump001.pmat \
    barn001.pmat \
    tree001.pmat \
    awning01_red.pmat \
    security_fence_light01.pmat \
    security_fence_light01_on.pmat \
    grain_elevator02.pmat \
    hubcap.pmat \
    blue_conveyor001.pmat \
    pipes_wall001.pmat \
    concrete_pipe001.pmat \
    factory_hatch001.pmat \
    building001.pmat \
    steeldoor001.pmat \
    building001_metal.pmat \
    building001_woodtrim.pmat \
    computer_industrial02.pmat \
    computer_industrial05.pmat \
    computer_industrial05_skin2.pmat \
    computer_industrial03.pmat \
    computer_industrial01.pmat \
    computer_industrial04.pmat \
    computer_industrial04_skin2.pmat \
    metal_fence02.pmat \
    metal_fence01.pmat \
    bridgesupport01.pmat \
    sewer_cap001.pmat \
    metal_watertower001.pmat \
    chimney008.pmat \
    tank002.pmat \
    sink001.pmat \
    unform_locker01.pmat \
    unform_locker01_skin2.pmat \
    weight_scale01.pmat \
    welding_machine01.pmat \
    welding_machine01_skin2.pmat \
    train_enginecar.pmat \
    grain_machinery_set2.pmat \
    roof_vent001.pmat \
    roof_metal_bridge001.pmat \
    wood_wall001.pmat \
    spytech_railing.pmat \
    railing_stairs001.pmat \
    chair.pmat \
    billboard001.pmat \
    billboard003.pmat \
    train_loader001.pmat \
    train_container.pmat \
    train_container_red.pmat \
    rock005c.pmat \
    rock001.pmat \
    rock001a.pmat \
    rock001b.pmat \
    rock001c.pmat \
    rock004.pmat \
    rock004a.pmat \
    rock004b.pmat \
    rock004c.pmat \
    rock003c.pmat \
    train_billboard001.pmat \
    grain_machinery_set1.pmat \
    cactus01.pmat \
    joshuatree01.pmat \
    rock002.pmat \
    rock002a.pmat \
    rock002b.pmat \
    dumptruck.pmat \
    barn_rocket1.pmat \
    rocket_launchpad1.pmat \
    rocket_launchpad1_blue.pmat \
    paint_can001.pmat \
    sniper_fence02_red.pmat \
    sniper_fence02_blue.pmat \
    barrel03.pmat \
    barrel03_blue.pmat \
    ammo_box1.pmat \
    ammo_box2.pmat \
    medkit.pmat \
    satellite_antenna01.pmat \
    window_glass004.pmat \
    chimney007.pmat \
    groundlight001_sheet_skin2.pmat \
    construction_light_on.pmat \
    construction_light.pmat \
    grass_01.pmat \
    grass_01_skin2.pmat \
    shrub_03_skin2.pmat \
    satellite_dish001.pmat \
    generator_pipe01.pmat \
    window_industrial01.pmat \
    window_industrial01_glass01.pmat \
    window_industrial01_glass01_skin2.pmat \
    window_industrial01_glass01_skin3.pmat \
    generator_machine01.pmat \
    generator_steamgage01.pmat \
    powertower02.pmat \
    dam.pmat \
    substation_transformer01.pmat \
    grass_02.pmat \
    grass_02_dark.pmat \
    grass_02_snow.pmat \
    shrub_01a.pmat \
    awning001.pmat \
    brewing_vat.pmat \
    beer_keg001.pmat \
    road_bumper01.pmat \
    dam_pipes.pmat \
    observatory_dome.pmat \
    car_lift.pmat \
    generator01.pmat \
    bramble01a.pmat \
    shrub_03_card.pmat \
    shrub_03_card_skin2.pmat \
    shrub_03_card_skin3.pmat \
    deadtree01.pmat \
    hydraulic_door.pmat \
    generator_pipe01_cap.pmat \
    exit_mounted.pmat \
    exit_mounted_blue.pmat \
    glass_door_handle001a.pmat \
    main_entrance_frame_red.pmat \
    road_railing01.pmat \
    alpha_electric_logo.pmat \
    small_substation1.pmat \
    spikeplant01.pmat \
    barricade.pmat \
    blast_furnace006.pmat \
    substation_truss01.pmat \
    billboard002.pmat \
    cap_point_base.pmat \
    cap_point_base_red.pmat \
    cap_point_base_blue.pmat \
    vault_door.pmat \
    handrail001_l1.pmat \
    competitive_stage_crates.pmat \
    competitive_stage_tarps.pmat \
    competitive_stage.pmat \
    competitive_stage_top.pmat \
    competitive_stage_warehouse.pmat \
    power_pylon.pmat \
    train_boxcar_noladder.pmat \
    train_boxcar_blue_noladder.pmat \
    train_flatcar_leveltop.pmat \
    train_rockets.pmat \
    window007b.pmat \
    train_tankcar.pmat \
    train_signal001.pmat \
    train_signal002.pmat \
    train_signal002_off.pmat \
    train_signal002_yellow.pmat \
    train_signal004.pmat \
    blast_furnace005.pmat \
    blast_furnace003.pmat \
    blast_furnace004.pmat \
    brickwall001.pmat \
    brickwall001b.pmat \
    ibeam001b.pmat \
    concretefloor002.pmat \
    factory_pipe002.pmat \
    powercable_truss.pmat \
    lightpole.pmat \
    lightpole_on.pmat \
    train_signal003.pmat \
    watertower.pmat \
    metal_watertower002.pmat \
    train_sign002.pmat \
    train_sign001.pmat \
    watertower002.pmat \
    smoke_stack001.pmat \
    train_gate001.pmat \
    crane_box001.pmat \
    crane_platform001.pmat \
    pulley_block001.pmat \
    train_gate002.pmat \
    powertower01.pmat \
    roof_truss001.pmat \
    window_skylight001.pmat \
    crane_cable001.pmat \
    concretewall003.pmat \
    black.pmat \
    brickwall002.pmat \
    concretefloor007.pmat \
    silo_top001.pmat \
    silo_skybox003.pmat \
    metaldoor001.pmat \
    computerwall007.pmat \
    concretewall026l.pmat \
    concretewall007.pmat \
    w_grenade_blue.pmat \
    w_grenade_red.pmat \
    demoman_red.pmat \
    demoman_blue.pmat \
    demoman_head.pmat

#end install_mat
