#define DIR_TYPE models
#define INSTALL_TO models/props_mining

#include $[THISDIRPREFIX]Sources.track_straight_256.pp
#include $[THISDIRPREFIX]Sources.track_arc_90degree_128.pp
#include $[THISDIRPREFIX]Sources.cranehook001.pp
#include $[THISDIRPREFIX]Sources.barbfence001_reference.pp
#include $[THISDIRPREFIX]Sources.fence001_reference.pp
#include $[THISDIRPREFIX]Sources.industrial_ceiling_lamp.pp
#include $[THISDIRPREFIX]Sources.conduit_outdoor512.pp
#include $[THISDIRPREFIX]Sources.conveyor_belt.pp
#include $[THISDIRPREFIX]Sources.wooden_rail01.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe06.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_128.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_64.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe04.pp
#include $[THISDIRPREFIX]Sources.industrial_ceiling_lamp02.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_16_up.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe06_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_128_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe04_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_256_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_64_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe_16_up_thick.pp
#include $[THISDIRPREFIX]Sources.fence003_reference.pp
#include $[THISDIRPREFIX]Sources.barbfence002_reference.pp
#include $[THISDIRPREFIX]Sources.crane002.pp
#include $[THISDIRPREFIX]Sources.board002_reference.pp
#include $[THISDIRPREFIX]Sources.board001_reference.pp
#include $[THISDIRPREFIX]Sources.sign001.pp
#include $[THISDIRPREFIX]Sources.factory_pipe004.pp
#include $[THISDIRPREFIX]Sources.factory_hatch001.pp
#include $[THISDIRPREFIX]Sources.computer_industrial02.pp
#include $[THISDIRPREFIX]Sources.computer_industrial05.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe03.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe01.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe06_thin.pp
#include $[THISDIRPREFIX]Sources.crank01.pp
#include $[THISDIRPREFIX]Sources.crank02.pp
#include $[THISDIRPREFIX]Sources.computer_industrial03.pp
#include $[THISDIRPREFIX]Sources.computer_industrial01.pp
#include $[THISDIRPREFIX]Sources.computer_industrial04.pp
#include $[THISDIRPREFIX]Sources.barbedfence_set01.pp
#include $[THISDIRPREFIX]Sources.conduit_outdoor384.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe05.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe02.pp
#include $[THISDIRPREFIX]Sources.junctionbox03.pp
#include $[THISDIRPREFIX]Sources.junctionbox02.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe01_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe02_thick.pp
#include $[THISDIRPREFIX]Sources.ceiling_pipe05_thick.pp
#include $[THISDIRPREFIX]Sources.conduit_outdoor256.pp
#include $[THISDIRPREFIX]Sources.track_straight_128.pp
#include $[THISDIRPREFIX]Sources.track_s_curve_48.pp
#include $[THISDIRPREFIX]Sources.track_arc_90degree_256.pp
#include $[THISDIRPREFIX]Sources.track_s_curve_96_mirrored.pp
#include $[THISDIRPREFIX]Sources.track_s_curve_96.pp
#include $[THISDIRPREFIX]Sources.track_straight_64.pp
#include $[THISDIRPREFIX]Sources.billboard001.pp
#include $[THISDIRPREFIX]Sources.factory_pipe003.pp
#include $[THISDIRPREFIX]Sources.factory_pipe005.pp
#include $[THISDIRPREFIX]Sources.rock005.pp
#include $[THISDIRPREFIX]Sources.rock001.pp
#include $[THISDIRPREFIX]Sources.rock004.pp
#include $[THISDIRPREFIX]Sources.rock003.pp
#include $[THISDIRPREFIX]Sources.rock006c.pp
#include $[THISDIRPREFIX]Sources.rock007.pp
#include $[THISDIRPREFIX]Sources.rock005_skybox.pp
#include $[THISDIRPREFIX]Sources.rock003_skybox.pp
#include $[THISDIRPREFIX]Sources.rock006b.pp
#include $[THISDIRPREFIX]Sources.rock002.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_256_01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_c_01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_l_128_01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_corner128_01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_s_01.pp
#include $[THISDIRPREFIX]Sources.rock006.pp
#include $[THISDIRPREFIX]Sources.junctionbox01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_128_01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_l_160_01.pp
#include $[THISDIRPREFIX]Sources.industrial_pipe01_corner160_01.pp
#include $[THISDIRPREFIX]Sources.factory_pipe_skybox004.pp
#include $[THISDIRPREFIX]Sources.generator_pipe01.pp
#include $[THISDIRPREFIX]Sources.window_industrial01.pp
#include $[THISDIRPREFIX]Sources.window_industrial01_glass01.pp
#include $[THISDIRPREFIX]Sources.generator_machine01.pp
#include $[THISDIRPREFIX]Sources.generator_steamgage01.pp
#include $[THISDIRPREFIX]Sources.generator01.pp
#include $[THISDIRPREFIX]Sources.generator_pipe01_cap.pp
#include $[THISDIRPREFIX]Sources.billboard002.pp
#include $[THISDIRPREFIX]Sources.billboard_skybox001.pp
#include $[THISDIRPREFIX]Sources.factory_pipe_skybox002.pp
#include $[THISDIRPREFIX]Sources.watertower.pp
#include $[THISDIRPREFIX]Sources.watertower002.pp
#include $[THISDIRPREFIX]Sources.smoke_stack_skybox001.pp
