#define DIR_TYPE models
#define INSTALL_TO maps

#begin install_tex
  #define SOURCES \
    tf2_logo.ptex concretefloor01.ptex \
    tf2_logo_2.ptex \
    tutorial_battle_props_palette_4samlc_1.ptex \
    expl001.ptex expl002.ptex expl003.ptex expl004.ptex \
    expl005.ptex expl006.ptex expl007.ptex expl008.ptex \
    expl009.ptex expl010.ptex sky.ptex brdf_lut.ptex \
    powered_by_panda3d.ptex engineer_red.ptex engineer_normal.ptex \
    pyro_lightwarp.ptex \
    engineer_blue.ptex \
    engineer_exponent.ptex \
    engineer_head.ptex \
    shared_normal.ptex \
    soldier_red.ptex \
    soldier_normal.ptex \
    soldier_blue.ptex \
    soldier_head.ptex \
    soldier_head_phongmask.ptex \
    soldier_head_exponent.ptex \
    Sentry1.ptex \
    Sentry1_normal.ptex \
    Sentry1_lightwarp.ptex \
    Sentry1_blue.ptex \
    Sentry1_Gibs.ptex \
    Sentry1_Gibs_blue.ptex \
    mini_sentry_blue.ptex \
    mini_sentry_light_blue.ptex \
    flat_normal.ptex \
    mini_sentry_light_red.ptex \
    mini_sentry_red.ptex \
    Sentry2.ptex \
    Sentry2_normal.ptex \
    Sentry2_blue.ptex \
    Sentry2_Gibs.ptex \
    Sentry2_Gibs_blue.ptex \
    soldier_statue.ptex \
    soldier_statue_normal.ptex \
    train_boxcar.ptex \
    spotlight001a.ptex \
    spotlight001a_noalpha.ptex \
    spotlight001a_blue.ptex \
    spotlight001a_blue_noalpha.ptex \
    spotlight001a_grey.ptex \
    spotlight001a_grey_noalpha.ptex \
    lights.ptex \
    security_camera.ptex \
    groundlight001_sheet.ptex \
    computer_wall05.ptex \
    computer_wall05b.ptex \
    computer_wall06.ptex \
    computer_wall06b.ptex \
    vent_system01.ptex \
    lightbulb001.ptex \
    tools.ptex \
    fence001.ptex \
    telephonepole001.ptex \
    hanging_ceiling_lamp.ptex \
    gutters001.ptex \
    gutters001a.ptex \
    window002.ptex \
    window002b.ptex \
    window001.ptex \
    window001b.ptex \
    door_slide_large.ptex \
    door_slide.ptex \
    door_slide_large_noentry.ptex \
    chimney004.ptex \
    steps_pipes_piece.ptex \
    security_fence_big.ptex \
    security_fence_alpha.ptex \
    spawnroom_door.ptex \
    walllight001a.ptex \
    walllight001a_noalpha.ptex \
    walllight001a_blue.ptex \
    walllight001a_blue_noalpha.ptex \
    walllight001a_grey.ptex \
    walllight001a_grey_noalpha.ptex \
    wood_floor001.ptex \
    grain_elevator01.ptex \
    window005.ptex \
    window005b.ptex \
    window006b.ptex \
    conveyor_belt.ptex \
    grainconveyor001.ptex \
    wooden_rail01.ptex \
    junction_box.ptex \
    vent001.ptex \
    shelf_props01.ptex \
    shelf_props01_skin2.ptex \
    ceiling_pipe01.ptex \
    ceiling_pipe01_skin2.ptex \
    foot_spray_can01.ptex \
    pill_bottle01.ptex \
    conduit.ptex \
    computer_wall_cabinet.ptex \
    work_table001.ptex \
    chimney006.ptex \
    barbfence001.ptex \
    rafter_01a.ptex \
    windmill001.ptex \
    spool_rope.ptex \
    wooden_barrel.ptex \
    wood_pile.ptex \
    haypile001_card.ptex \
    wall_clock.ptex \
    wall_clock_glass.ptex \
    watercooler_sheet.ptex \
    watercooler_bottle.ptex \
    silo_cluster01a.ptex \
    intercom.ptex \
    time_card_machine002.ptex \
    time_card_machine.ptex \
    computer_printer.ptex \
    computer_printer002.ptex \
    computer_printer_red_worn.ptex \
    computer_printer_blue_worn.ptex \
    outlet.ptex \
    window003.ptex \
    window003b.ptex \
    ceiling_conduit.ptex \
    miningcrate001.ptex \
    nail001.ptex \
    black.ptex \
    lantern001.ptex \
    metalbucket001.ptex \
    horseshoe001.ptex \
    miningcrate002.ptex \
    pick001.ptex \
    cow001.ptex \
    telephone001.ptex \
    crane002.ptex \
    cranehook001.ptex \
    board002.ptex \
    board001.ptex \
    vent.ptex \
    chimney005.ptex \
    sign001.ptex \
    corrugated_metal003.ptex \
    corrugated_metal001.ptex \
    corrugated_metal002.ptex \
    weathervane001.ptex \
    lunchbag.ptex \
    waste_basket01.ptex \
    thermos.ptex \
    thermos_spec01.ptex \
    corkboard01.ptex \
    grain_elevator04.ptex \
    silo001.ptex \
    tree001_card.ptex \
    tree001_card_skin2.ptex \
    chimney003.ptex \
    lamp001.ptex \
    lamp001_noalpha.ptex \
    exit_sign01.ptex \
    spool_wire.ptex \
    blue_window001.ptex \
    rock_worn001.ptex \
    metal_pile.ptex \
    floodlight001.ptex \
    siren.ptex \
    siren_skin2.ptex \
    factory_pipe004.ptex \
    wood_bridge001.ptex \
    wood_bridge002.ptex \
    crank01.ptex \
    crank02.ptex \
    rafters001.ptex \
    wood_wall002.ptex \
    wood_beam01.ptex \
    wall027.ptex \
    wood_beam02.ptex \
    wall026.ptex \
    wood_wall005a.ptex \
    window006.ptex \
    propane_tank_tall01.ptex \
    shelf_props02.ptex \
    junctionbox01.ptex \
    barbell01.ptex \
    tape_wrap01.ptex \
    towel_rack01.ptex \
    bench001a.ptex \
    sign_gameplay01_skin1.ptex \
    sign_gameplay01_normal.ptex \
    sign_gameplay01_skin2.ptex \
    sign_gameplay01_skin3.ptex \
    sign_gameplay01_skin4.ptex \
    sign_gameplay01_skin5.ptex \
    sign_gameplay01_skin6.ptex \
    sign_gameplay01_skin7.ptex \
    sign_gameplay01_skin8.ptex \
    sign_gameplay01_skin9.ptex \
    sign_gameplay01_skin10.ptex \
    sign_gameplay01_skin11.ptex \
    sign_gameplay01_skin12.ptex \
    blast_door_frame01.ptex \
    doorframe002a.ptex \
    blue_window001_glass.ptex \
    tracks001.ptex \
    silo_skybox004.ptex \
    silo002.ptex \
    doorframe003.ptex \
    grain_elevator_facade_14b.ptex \
    CoffeePot.ptex \
    Lamp002.ptex \
    Lamp002_skin1.ptex \
    Chalkboard01.ptex \
    Chalkboard_spec01.ptex \
    Chalkboard01_skin1.ptex \
    floodlight001b.ptex \
    door_grate001.ptex \
    handrail128.ptex \
    handrail128_skin2.ptex \
    handrail128_skin3.ptex \
    handrail128_skin4.ptex \
    window004.ptex \
    train_engine.ptex \
    train_engine_01.ptex \
    factory_pipe003.ptex \
    factory_pipe005.ptex \
    window009.ptex \
    window009c.ptex \
    blast_furnace001.ptex \
    metal_barrier01.ptex \
    rock006.ptex \
    sign_wood_cap001a.ptex \
    sign_wood_cap001b.ptex \
    sign_wood_cap001c.ptex \
    sign_wood_cap_redcart.ptex \
    sign_wood_cap_bluecart.ptex \
    sign_wood_cap001a_blue.ptex \
    sign_wood_cap001b_blue.ptex \
    sign_wood_cap001c_blue.ptex \
    rock007.ptex \
    rock007a.ptex \
    rock007b.ptex \
    rock007c.ptex \
    rock005.ptex \
    rock005a.ptex \
    rock005b.ptex \
    rock003.ptex \
    rock003a.ptex \
    rock003b.ptex \
    rock001_skybox.ptex \
    rock001_skybox_normal.ptex \
    rock006a.ptex \
    rock006b.ptex \
    shrub_03.ptex \
    shrub_03_snow.ptex \
    rock002_skybox.ptex \
    blast_furnace002.ptex \
    industrial_pipe01.ptex \
    Concrete_Block001.ptex \
    corrugated_metal004.ptex \
    lamp002.ptex \
    lamp002_noalpha.ptex \
    wall_map.ptex \
    wall_map_normal.ptex \
    chimney001.ptex \
    hardhat001.ptex \
    ladder001.ptex \
    cart_base_separate.ptex \
    pallet001.ptex \
    fire_bell01.ptex \
    wood_fence_short_128b.ptex \
    barrel_crate.ptex \
    cart_bomb_separate.ptex \
    target_demoman.ptex \
    target_demoman_blu.ptex \
    target_pyro.ptex \
    target_pyro_blu.ptex \
    target_engineer.ptex \
    target_engineer_blu.ptex \
    target_spy.ptex \
    target_spy_blu.ptex \
    target_soldier.ptex \
    target_soldier_blu.ptex \
    wood_fence_128.ptex \
    wood_fence_128b.ptex \
    waste_elevator.ptex \
    sign_barricade001a.ptex \
    barrel01.ptex \
    track_mining.ptex \
    track_mining_blue.ptex \
    hand_truck01.ptex \
    hand_truck01_skin2.ptex \
    cart_base.ptex \
    cart_selfillum.ptex \
    cart_bomb.ptex \
    cart_bomb_selfillum.ptex \
    cart_dispenser.ptex \
    terminal_chair.ptex \
    terminal_chair_blue.ptex \
    terminal_chair_red_worn.ptex \
    terminal_chair_blue_worn.ptex \
    oildrum001.ptex \
    oildrum002.ptex \
    oildrum003.ptex \
    oildrum004.ptex \
    oildrum005.ptex \
    oildrum006.ptex \
    siren001.ptex \
    siren001b.ptex \
    computer_wall02.ptex \
    mop_and_bucket01.ptex \
    fire_extinguisher.ptex \
    tire001.ptex \
    tire001_normal.ptex \
    trainwheel001.ptex \
    computer_cart01.ptex \
    wood_fence_short_128.ptex \
    chicken_wire.ptex \
    wood_pallet.ptex \
    water_pipes.ptex \
    2pipe.ptex \
    milk_crate.ptex \
    computer_wall.ptex \
    computer_wallb.ptex \
    computer_wall_red_worn.ptex \
    computer_wall_blue_worn.ptex \
    computer_wall04.ptex \
    computer_wall04b.ptex \
    computer_wall04_red_worn.ptex \
    computer_wall04_blue_worn.ptex \
    computer_wall03.ptex \
    computer_wall03b.ptex \
    computer_wall03_red_worn.ptex \
    computer_wall03_blue_worn.ptex \
    computer_low.ptex \
    computer_lowb.ptex \
    control_room_consoles.ptex \
    control_room_consoles_skin2.ptex \
    control_room_consoles_red_worn.ptex \
    control_room_consoles_blue_worn.ptex \
    CoffeeMaker.ptex \
    CoffeeMaker_spec01.ptex \
    haybale.ptex \
    conduit_outdoor01.ptex \
    train_orecar.ptex \
    pickup03.ptex \
    pickup_lightwarp.ptex \
    pickup04.ptex \
    grain_sack_red.ptex \
    grain_sack_normal.ptex \
    grain_sack_blue.ptex \
    house001.ptex \
    air_intake.ptex \
    water_spigot.ptex \
    sniper_fence01_red.ptex \
    sniper_fence01_blue.ptex \
    chair_normal.ptex \
    desk.ptex \
    spytech_roofbeam001.ptex \
    spytech_roofbeam001b.ptex \
    spytech_roofbeam02.ptex \
    spytech_roofbeam02b.ptex \
    spytech_roofbeam03.ptex \
    spytech_roofbeam03b.ptex \
    spytech_roofbeam04.ptex \
    spytech_roofbeam04b.ptex \
    blast_door.ptex \
    reel_rack.ptex \
    flag_room_glass_door_frame.ptex \
    milkjug001.ptex \
    bullskull001.ptex \
    hose001.ptex \
    wagonwheel001.ptex \
    TV001.ptex \
    tractor_tire001.ptex \
    tractor_tire001_normal.ptex \
    tank001.ptex \
    drain_pipe001.ptex \
    waterpump001.ptex \
    barn001.ptex \
    tree001.ptex \
    tree001_envmap.ptex \
    awning01_red.ptex \
    security_fence_light01.ptex \
    security_fence_light01_on.ptex \
    grain_elevator02.ptex \
    hubcap.ptex \
    hubcap_normal.ptex \
    blue_conveyor001.ptex \
    pipes_wall001.ptex \
    Concrete_Pipe001.ptex \
    factory_hatch001.ptex \
    building001_dirtmap.ptex \
    steeldoor001.ptex \
    computer_industrial02.ptex \
    computer_industrial05.ptex \
    computer_industrial05_skin2.ptex \
    computer_industrial03.ptex \
    computer_industrial01.ptex \
    computer_industrial04.ptex \
    computer_industrial04_skin2.ptex \
    metal_fence02.ptex \
    metal_fence01.ptex \
    bridgesupport01.ptex \
    sewer_cap001.ptex \
    metal_watertower001.ptex \
    chimney008.ptex \
    tank002.ptex \
    sink001.ptex \
    unform_locker01.ptex \
    unform_locker01_skin2.ptex \
    weight_scale01.ptex \
    welding_machine01.ptex \
    welding_machine01_skin2.ptex \
    train_enginecar.ptex \
    grain_machinery_set2.ptex \
    roof_vent001.ptex \
    roof_metal001.ptex \
    wood_wall001.ptex \
    spytech_railing.ptex \
    railing_stairs001.ptex \
    chair.ptex \
    billboard001.ptex \
    billboard003.ptex \
    train_loader001.ptex \
    train_container.ptex \
    train_container_red.ptex \
    rock005c.ptex \
    rock001.ptex \
    rock001a.ptex \
    rock001b.ptex \
    rock001c.ptex \
    rock004.ptex \
    rock004a.ptex \
    rock004b.ptex \
    rock004c.ptex \
    rock003c.ptex \
    train_billboard001.ptex \
    grain_machinery_set1.ptex \
    cactus01.ptex \
    cactus01_normal.ptex \
    cactus01_lightwarp.ptex \
    joshuatree01.ptex \
    rock002.ptex \
    rock002a.ptex \
    rock002b.ptex \
    dumptruck.ptex \
    dumptruck_normal.ptex \
    barn_rocket1.ptex \
    rocket_launchpad1.ptex \
    rocket_launchpad1_blue.ptex \
    paint_can001.ptex \
    sniper_fence02_red.ptex \
    sniper_fence02_blue.ptex \
    barrel03.ptex \
    barrel03_blue.ptex \
    ammo_box1.ptex \
    ammo_box2.ptex \
    medkit.ptex \
    satellite_antenna01.ptex \
    window_glass004.ptex \
    chimney007.ptex \
    groundlight001_sheet_skin2.ptex \
    construction_light_on.ptex \
    construction_light.ptex \
    grass_01.ptex \
    grass_01_skin2.ptex \
    shrub_03_skin2.ptex \
    satellite_dish001.ptex \
    generator_pipe01.ptex \
    window_industrial01.ptex \
    window_industrial01_glass01.ptex \
    window_industrial01_glass01_skin2.ptex \
    window_industrial01_glass01_skin3.ptex \
    generator_machine01.ptex \
    generator_steamgage01.ptex \
    powertower02.ptex \
    dam.ptex \
    substation_transformer01.ptex \
    grass_02.ptex \
    grass_02_snow.ptex \
    shrub_01a.ptex \
    awning001.ptex \
    brewing_vat.ptex \
    beer_keg001.ptex \
    beer_keg001_normal.ptex \
    road_bumper01.ptex \
    dam_pipes.ptex \
    observatory_dome.ptex \
    car_lift.ptex \
    generator01.ptex \
    generator01_normal.ptex \
    bramble01a.ptex \
    shrub_03_card.ptex \
    shrub_03_card_skin2.ptex \
    shrub_03_card_skin3.ptex \
    deadtree01.ptex \
    hydraulic_door.ptex \
    generator_pipe01_cap.ptex \
    exit_mounted.ptex \
    exit_mounted_blue.ptex \
    glass_door_handle001a.ptex \
    main_entrance_frame_red.ptex \
    road_railing01.ptex \
    alpha_electric_logo.ptex \
    small_substation1.ptex \
    spikeplant01.ptex \
    barricade.ptex \
    barricade_normal.ptex \
    blast_furnace006.ptex \
    substation_truss01.ptex \
    billboard002.ptex \
    cap_point_base.ptex \
    cap_point_base_normal.ptex \
    cap_point_base_red.ptex \
    cap_point_base_blue.ptex \
    vault_door.ptex \
    handrail001_L1.ptex \
    competitive_stage_crates.ptex \
    competitive_stage_tarps.ptex \
    competitive_stage_tarps_normal.ptex \
    competitive_stage.ptex \
    competitive_stage_top.ptex \
    competitive_stage_warehouse.ptex \
    power_pylon.ptex \
    train_boxcar_noladder.ptex \
    train_boxcar_blue_noladder.ptex \
    train_flatcar_leveltop.ptex \
    train_rockets.ptex \
    window007b.ptex \
    train_tankcar.ptex \
    train_signal001.ptex \
    train_signal002.ptex \
    train_signal002_off.ptex \
    train_signal002_yellow.ptex \
    train_signal004.ptex \
    blast_furnace005.ptex \
    blast_furnace003.ptex \
    blast_furnace004.ptex \
    brickwall001.ptex \
    brickwall001b.ptex \
    Ibeam001b.ptex \
    concretefloor002.ptex \
    factory_pipe002.ptex \
    powercable_truss.ptex \
    lightpole.ptex \
    lightpole_on.ptex \
    train_signal003.ptex \
    watertower.ptex \
    metal_watertower002.ptex \
    train_sign002.ptex \
    train_sign001.ptex \
    watertower002.ptex \
    smoke_stack001.ptex \
    train_gate001.ptex \
    crane_box001.ptex \
    crane_platform001.ptex \
    pulley_block001.ptex \
    train_gate002.ptex \
    powertower01.ptex \
    roof_truss001.ptex \
    window_skylight001.ptex \
    crane_cable001.ptex \
    concretewall003.ptex \
    brickwall002.ptex \
    concretefloor007.ptex \
    silo_top001.ptex \
    silo_skybox003.ptex \
    metaldoor001.ptex \
    computerwall007.ptex \
    concretewall026l.ptex \
    concretewall007.ptex \
    w_grenade_blue.ptex \
    weapon_lightwarp.ptex \
    hand_lightwarp.ptex \
    softened_weapon_lightwarp.ptex \
    w_grenade_red.ptex \
    demoman_red.ptex \
    demoman_normal.ptex \
    demoman_red_exponent.ptex \
    demoman_blue.ptex \
    demoman_head.ptex \
    demoman_head_phongmask.ptex \
    demoman_head_exponent.ptex

#end install_tex

#begin install_mat
  #define SOURCES \
    concretefloor01.pmat \
    tutorial_battle_props_palette_4samlc_1.pmat \
    expl001.pmat expl002.pmat expl003.pmat expl004.pmat \
    expl005.pmat expl006.pmat expl007.pmat expl008.pmat \
    expl009.pmat expl010.pmat

#end install_mat
