#define DIR_TYPE models
#define INSTALL_TO maps

#begin install_tex
  #define SOURCES \
    tf2_logo.ptex concretefloor01.ptex \
    tf2_logo_2.ptex \
    tutorial_battle_props_palette_4samlc_1.ptex \
    expl001.ptex expl002.ptex expl003.ptex expl004.ptex \
    expl005.ptex expl006.ptex expl007.ptex expl008.ptex \
    expl009.ptex expl010.ptex sky.ptex brdf_lut.ptex \
    powered_by_panda3d.ptex engineer_red.ptex engineer_normal.ptex \
    pyro_lightwarp.ptex \
    engineer_blue.ptex \
    engineer_exponent.ptex \
    engineer_head.ptex \
    shared_normal.ptex \
    soldier_red.ptex \
    soldier_normal.ptex \
    soldier_blue.ptex \
    soldier_head.ptex \
    soldier_head_phongmask.ptex \
    soldier_head_exponent.ptex \
    Sentry1.ptex \
    Sentry1_normal.ptex \
    Sentry1_lightwarp.ptex \
    Sentry1_blue.ptex \
    Sentry1_Gibs.ptex \
    Sentry1_Gibs_blue.ptex \
    mini_sentry_blue.ptex \
    mini_sentry_light_blue.ptex \
    flat_normal.ptex \
    mini_sentry_light_red.ptex \
    mini_sentry_red.ptex \
    Sentry2.ptex \
    Sentry2_normal.ptex \
    Sentry2_blue.ptex \
    Sentry2_Gibs.ptex \
    Sentry2_Gibs_blue.ptex \
    soldier_statue.ptex \
    soldier_statue_normal.ptex \
    train_boxcar.ptex \
    spotlight001a.ptex \
    spotlight001a_noalpha.ptex \
    spotlight001a_blue.ptex \
    spotlight001a_blue_noalpha.ptex \
    spotlight001a_grey.ptex \
    spotlight001a_grey_noalpha.ptex \
    lights.ptex \
    security_camera.ptex \
    groundlight001_sheet.ptex \
    computer_wall05.ptex \
    computer_wall05b.ptex \
    computer_wall06.ptex \
    computer_wall06b.ptex \
    vent_system01.ptex \
    lightbulb001.ptex \
    tools.ptex \
    fence001.ptex \
    telephonepole001.ptex \
    hanging_ceiling_lamp.ptex \
    gutters001.ptex \
    gutters001a.ptex \
    window002.ptex \
    window002b.ptex \
    window001.ptex \
    window001b.ptex \
    door_slide_large.ptex \
    door_slide.ptex \
    door_slide_large_noentry.ptex \
    chimney004.ptex \
    steps_pipes_piece.ptex \
    security_fence_big.ptex \
    security_fence_alpha.ptex \
    spawnroom_door.ptex \
    walllight001a.ptex \
    walllight001a_noalpha.ptex \
    walllight001a_blue.ptex \
    walllight001a_blue_noalpha.ptex \
    walllight001a_grey.ptex \
    walllight001a_grey_noalpha.ptex \
    wood_floor001.ptex \
    grain_elevator01.ptex \
    window005.ptex \
    window005b.ptex \
    window006b.ptex \
    conveyor_belt.ptex \
    grainconveyor001.ptex \
    wooden_rail01.ptex \
    junction_box.ptex \
    vent001.ptex \
    shelf_props01.ptex \
    shelf_props01_skin2.ptex \
    ceiling_pipe01.ptex \
    ceiling_pipe01_skin2.ptex \
    foot_spray_can01.ptex \
    pill_bottle01.ptex \
    conduit.ptex \
    computer_wall_cabinet.ptex \
    work_table001.ptex \
    chimney006.ptex \
    barbfence001.ptex \
    rafter_01a.ptex \
    windmill001.ptex \
    spool_rope.ptex \
    wooden_barrel.ptex \
    wood_pile.ptex \
    haypile001_card.ptex \
    wall_clock.ptex \
    wall_clock_glass.ptex \
    watercooler_sheet.ptex \
    watercooler_bottle.ptex \
    silo_cluster01a.ptex \
    intercom.ptex \
    time_card_machine002.ptex \
    time_card_machine.ptex \
    computer_printer.ptex \
    computer_printer002.ptex \
    computer_printer_red_worn.ptex \
    computer_printer_blue_worn.ptex \
    outlet.ptex \
    window003.ptex \
    window003b.ptex \
    ceiling_conduit.ptex \
    miningcrate001.ptex \
    nail001.ptex \
    black.ptex \
    lantern001.ptex \
    metalbucket001.ptex \
    horseshoe001.ptex \
    miningcrate002.ptex \
    pick001.ptex \
    cow001.ptex \
    telephone001.ptex \
    crane002.ptex \
    cranehook001.ptex \
    board002.ptex \
    board001.ptex \
    vent.ptex \
    chimney005.ptex \
    sign001.ptex \
    corrugated_metal003.ptex \
    corrugated_metal001.ptex \
    corrugated_metal002.ptex \
    weathervane001.ptex \
    lunchbag.ptex \
    waste_basket01.ptex \
    thermos.ptex \
    thermos_spec01.ptex \
    corkboard01.ptex \
    grain_elevator04.ptex \
    silo001.ptex \
    tree001_card.ptex \
    tree001_card_skin2.ptex \
    chimney003.ptex \
    lamp001.ptex \
    lamp001_noalpha.ptex \
    exit_sign01.ptex \
    spool_wire.ptex \
    blue_window001.ptex \
    rock_worn001.ptex \
    metal_pile.ptex \
    floodlight001.ptex \
    siren.ptex \
    siren_skin2.ptex \
    factory_pipe004.ptex \
    wood_bridge001.ptex \
    wood_bridge002.ptex \
    crank01.ptex \
    crank02.ptex \
    rafters001.ptex \
    wood_wall002.ptex \
    wood_beam01.ptex \
    wall027.ptex \
    wood_beam02.ptex \
    wall026.ptex \
    wood_wall005a.ptex \
    window006.ptex \
    propane_tank_tall01.ptex \
    shelf_props02.ptex \
    junctionbox01.ptex \
    barbell01.ptex \
    tape_wrap01.ptex \
    towel_rack01.ptex \
    bench001a.ptex \
    sign_gameplay01_skin1.ptex \
    sign_gameplay01_normal.ptex \
    sign_gameplay01_skin2.ptex \
    sign_gameplay01_skin3.ptex \
    sign_gameplay01_skin4.ptex \
    sign_gameplay01_skin5.ptex \
    sign_gameplay01_skin6.ptex \
    sign_gameplay01_skin7.ptex \
    sign_gameplay01_skin8.ptex \
    sign_gameplay01_skin9.ptex \
    sign_gameplay01_skin10.ptex \
    sign_gameplay01_skin11.ptex \
    sign_gameplay01_skin12.ptex \
    blast_door_frame01.ptex \
    doorframe002a.ptex \
    blue_window001_glass.ptex \
    tracks001.ptex \
    silo_skybox004.ptex \
    silo002.ptex \
    doorframe003.ptex \
    grain_elevator_facade_14b.ptex \
    CoffeePot.ptex \
    Lamp002.ptex \
    Lamp002_skin1.ptex \
    Chalkboard01.ptex \
    Chalkboard_spec01.ptex \
    Chalkboard01_skin1.ptex \
    floodlight001b.ptex \
    door_grate001.ptex \
    handrail128.ptex \
    handrail128_skin2.ptex \
    handrail128_skin3.ptex \
    handrail128_skin4.ptex \
    window004.ptex \
    train_engine.ptex \
    train_engine_01.ptex \
    factory_pipe003.ptex \
    factory_pipe005.ptex \
    window009.ptex \
    window009c.ptex \
    blast_furnace001.ptex \
    metal_barrier01.ptex \
    rock006.ptex \
    sign_wood_cap001a.ptex \
    sign_wood_cap001b.ptex \
    sign_wood_cap001c.ptex \
    sign_wood_cap_redcart.ptex \
    sign_wood_cap_bluecart.ptex \
    sign_wood_cap001a_blue.ptex \
    sign_wood_cap001b_blue.ptex \
    sign_wood_cap001c_blue.ptex \
    rock007.ptex \
    rock007a.ptex \
    rock007b.ptex \
    rock007c.ptex \
    rock005.ptex \
    rock005a.ptex \
    rock005b.ptex \
    rock003.ptex \
    rock003a.ptex \
    rock003b.ptex \
    rock001_skybox.ptex \
    rock001_skybox_normal.ptex \
    rock006a.ptex \
    rock006b.ptex \
    shrub_03.ptex \
    shrub_03_snow.ptex \
    rock002_skybox.ptex \
    blast_furnace002.ptex \
    industrial_pipe01.ptex \
    Concrete_Block001.ptex \
    corrugated_metal004.ptex \
    lamp002_noalpha.ptex \
    wall_map.ptex \
    wall_map_normal.ptex \
    chimney001.ptex \
    hardhat001.ptex \
    ladder001.ptex \
    cart_base_separate.ptex \
    pallet001.ptex \
    fire_bell01.ptex \
    wood_fence_short_128b.ptex \
    barrel_crate.ptex \
    cart_bomb_separate.ptex \
    target_demoman.ptex \
    target_demoman_blu.ptex \
    target_pyro.ptex \
    target_pyro_blu.ptex \
    target_engineer.ptex \
    target_engineer_blu.ptex \
    target_spy.ptex \
    target_spy_blu.ptex \
    target_soldier.ptex \
    target_soldier_blu.ptex \
    wood_fence_128.ptex \
    wood_fence_128b.ptex \
    waste_elevator.ptex \
    sign_barricade001a.ptex \
    barrel01.ptex \
    track_mining.ptex \
    track_mining_blue.ptex \
    hand_truck01.ptex \
    hand_truck01_skin2.ptex \
    cart_base.ptex \
    cart_selfillum.ptex \
    cart_bomb.ptex \
    cart_bomb_selfillum.ptex \
    cart_dispenser.ptex \
    terminal_chair.ptex \
    terminal_chair_blue.ptex \
    terminal_chair_red_worn.ptex \
    terminal_chair_blue_worn.ptex \
    oildrum001.ptex \
    oildrum002.ptex \
    oildrum003.ptex \
    oildrum004.ptex \
    oildrum005.ptex \
    oildrum006.ptex \
    siren001.ptex \
    siren001b.ptex \
    computer_wall02.ptex \
    mop_and_bucket01.ptex \
    fire_extinguisher.ptex \
    tire001.ptex \
    tire001_normal.ptex \
    trainwheel001.ptex \
    computer_cart01.ptex \
    wood_fence_short_128.ptex \
    chicken_wire.ptex \
    wood_pallet.ptex \
    water_pipes.ptex \
    2pipe.ptex \
    milk_crate.ptex \
    computer_wall.ptex \
    computer_wallb.ptex \
    computer_wall_red_worn.ptex \
    computer_wall_blue_worn.ptex \
    computer_wall04.ptex \
    computer_wall04b.ptex \
    computer_wall04_red_worn.ptex \
    computer_wall04_blue_worn.ptex \
    computer_wall03.ptex \
    computer_wall03b.ptex \
    computer_wall03_red_worn.ptex \
    computer_wall03_blue_worn.ptex \
    computer_low.ptex \
    computer_lowb.ptex \
    control_room_consoles.ptex \
    control_room_consoles_skin2.ptex \
    control_room_consoles_red_worn.ptex \
    control_room_consoles_blue_worn.ptex \
    CoffeeMaker.ptex \
    CoffeeMaker_spec01.ptex \
    haybale.ptex \
    conduit_outdoor01.ptex \
    train_orecar.ptex \
    pickup03.ptex \
    pickup_lightwarp.ptex \
    pickup04.ptex \
    grain_sack_red.ptex \
    grain_sack_normal.ptex \
    grain_sack_blue.ptex \
    house001.ptex \
    air_intake.ptex \
    water_spigot.ptex \
    sniper_fence01_red.ptex \
    sniper_fence01_blue.ptex \
    chair_normal.ptex \
    desk.ptex \
    spytech_roofbeam001.ptex \
    spytech_roofbeam001b.ptex \
    spytech_roofbeam02.ptex \
    spytech_roofbeam02b.ptex \
    spytech_roofbeam03.ptex \
    spytech_roofbeam03b.ptex \
    spytech_roofbeam04.ptex \
    spytech_roofbeam04b.ptex \
    blast_door.ptex \
    reel_rack.ptex \
    flag_room_glass_door_frame.ptex \
    milkjug001.ptex \
    bullskull001.ptex \
    hose001.ptex \
    wagonwheel001.ptex \
    TV001.ptex \
    tractor_tire001.ptex \
    tractor_tire001_normal.ptex \
    tank001.ptex \
    drain_pipe001.ptex \
    waterpump001.ptex \
    barn001.ptex \
    tree001.ptex \
    tree001_envmap.ptex \
    awning01_red.ptex \
    security_fence_light01.ptex \
    security_fence_light01_on.ptex \
    grain_elevator02.ptex \
    hubcap.ptex \
    hubcap_normal.ptex \
    blue_conveyor001.ptex \
    pipes_wall001.ptex \
    Concrete_Pipe001.ptex \
    factory_hatch001.ptex \
    building001_dirtmap.ptex \
    steeldoor001.ptex \
    computer_industrial02.ptex \
    computer_industrial05.ptex \
    computer_industrial05_skin2.ptex \
    computer_industrial03.ptex \
    computer_industrial01.ptex \
    computer_industrial04.ptex \
    computer_industrial04_skin2.ptex \
    metal_fence02.ptex \
    metal_fence01.ptex \
    bridgesupport01.ptex \
    sewer_cap001.ptex \
    metal_watertower001.ptex \
    chimney008.ptex \
    tank002.ptex \
    sink001.ptex \
    unform_locker01.ptex \
    unform_locker01_skin2.ptex \
    weight_scale01.ptex \
    welding_machine01.ptex \
    welding_machine01_skin2.ptex \
    train_enginecar.ptex \
    grain_machinery_set2.ptex \
    roof_vent001.ptex \
    roof_metal001.ptex \
    wood_wall001.ptex \
    spytech_railing.ptex \
    railing_stairs001.ptex \
    chair.ptex \
    billboard001.ptex \
    billboard003.ptex \
    train_loader001.ptex \
    train_container.ptex \
    train_container_red.ptex \
    rock005c.ptex \
    rock001.ptex \
    rock001a.ptex \
    rock001b.ptex \
    rock001c.ptex \
    rock004.ptex \
    rock004a.ptex \
    rock004b.ptex \
    rock004c.ptex \
    rock003c.ptex \
    train_billboard001.ptex \
    grain_machinery_set1.ptex \
    cactus01.ptex \
    cactus01_normal.ptex \
    cactus01_lightwarp.ptex \
    joshuatree01.ptex \
    rock002.ptex \
    rock002a.ptex \
    rock002b.ptex \
    dumptruck.ptex \
    dumptruck_normal.ptex \
    barn_rocket1.ptex \
    rocket_launchpad1.ptex \
    rocket_launchpad1_blue.ptex \
    paint_can001.ptex \
    sniper_fence02_red.ptex \
    sniper_fence02_blue.ptex \
    barrel03.ptex \
    barrel03_blue.ptex \
    ammo_box1.ptex \
    ammo_box2.ptex \
    medkit.ptex \
    satellite_antenna01.ptex \
    window_glass004.ptex \
    chimney007.ptex \
    groundlight001_sheet_skin2.ptex \
    construction_light_on.ptex \
    construction_light.ptex \
    grass_01.ptex \
    grass_01_skin2.ptex \
    shrub_03_skin2.ptex \
    satellite_dish001.ptex \
    generator_pipe01.ptex \
    window_industrial01.ptex \
    window_industrial01_glass01.ptex \
    window_industrial01_glass01_skin2.ptex \
    window_industrial01_glass01_skin3.ptex \
    generator_machine01.ptex \
    generator_steamgage01.ptex \
    powertower02.ptex \
    dam.ptex \
    substation_transformer01.ptex \
    grass_02.ptex \
    grass_02_snow.ptex \
    shrub_01a.ptex \
    awning001.ptex \
    brewing_vat.ptex \
    beer_keg001.ptex \
    beer_keg001_normal.ptex \
    road_bumper01.ptex \
    dam_pipes.ptex \
    observatory_dome.ptex \
    car_lift.ptex \
    generator01.ptex \
    generator01_normal.ptex \
    bramble01a.ptex \
    shrub_03_card.ptex \
    shrub_03_card_skin2.ptex \
    shrub_03_card_skin3.ptex \
    deadtree01.ptex \
    hydraulic_door.ptex \
    generator_pipe01_cap.ptex \
    exit_mounted.ptex \
    exit_mounted_blue.ptex \
    glass_door_handle001a.ptex \
    main_entrance_frame_red.ptex \
    road_railing01.ptex \
    alpha_electric_logo.ptex \
    small_substation1.ptex \
    spikeplant01.ptex \
    barricade.ptex \
    barricade_normal.ptex \
    blast_furnace006.ptex \
    substation_truss01.ptex \
    billboard002.ptex \
    cap_point_base.ptex \
    cap_point_base_normal.ptex \
    cap_point_base_red.ptex \
    cap_point_base_blue.ptex \
    vault_door.ptex \
    handrail001_L1.ptex \
    competitive_stage_crates.ptex \
    competitive_stage_tarps.ptex \
    competitive_stage_tarps_normal.ptex \
    competitive_stage.ptex \
    competitive_stage_top.ptex \
    competitive_stage_warehouse.ptex \
    power_pylon.ptex \
    train_boxcar_noladder.ptex \
    train_boxcar_blue_noladder.ptex \
    train_flatcar_leveltop.ptex \
    train_rockets.ptex \
    window007b.ptex \
    train_tankcar.ptex \
    train_signal001.ptex \
    train_signal002.ptex \
    train_signal002_off.ptex \
    train_signal002_yellow.ptex \
    train_signal004.ptex \
    blast_furnace005.ptex \
    blast_furnace003.ptex \
    blast_furnace004.ptex \
    brickwall001.ptex \
    brickwall001b.ptex \
    Ibeam001b.ptex \
    concretefloor002.ptex \
    factory_pipe002.ptex \
    powercable_truss.ptex \
    lightpole.ptex \
    lightpole_on.ptex \
    train_signal003.ptex \
    watertower.ptex \
    metal_watertower002.ptex \
    train_sign002.ptex \
    train_sign001.ptex \
    watertower002.ptex \
    smoke_stack001.ptex \
    train_gate001.ptex \
    crane_box001.ptex \
    crane_platform001.ptex \
    pulley_block001.ptex \
    train_gate002.ptex \
    powertower01.ptex \
    roof_truss001.ptex \
    window_skylight001.ptex \
    crane_cable001.ptex \
    concretewall003.ptex \
    brickwall002.ptex \
    concretefloor007.ptex \
    silo_top001.ptex \
    silo_skybox003.ptex \
    metaldoor001.ptex \
    computerwall007.ptex \
    concretewall026l.ptex \
    concretewall007.ptex \
    w_grenade_blue.ptex \
    weapon_lightwarp.ptex \
    hand_lightwarp.ptex \
    softened_weapon_lightwarp.ptex \
    w_grenade_red.ptex \
    demoman_red.ptex \
    demoman_normal.ptex \
    demoman_red_exponent.ptex \
    demoman_blue.ptex \
    demoman_head.ptex \
    demoman_head_phongmask.ptex \
    demoman_head_exponent.ptex \
    hanginglight001.ptex \
    tunnel_truss01.ptex \
    tunnel_truss01b.ptex \
    cliff_wall_06.ptex \
    cliff_wall_06_snow.ptex \
    cliff_wall_09.ptex \
    cliff_wall_09_snow.ptex \
    bottle001.ptex \
    wood_patch2.ptex \
    wood_patch2b.ptex \
    wood_patch2c.ptex \
    wood_support_128.ptex \
    cliff_wall_01.ptex \
    cliff_wall_01_snow.ptex \
    tree_pine01.ptex \
    tree_pine01_snow.ptex \
    train_tunnel_01.ptex \
    cliff_wall_05.ptex \
    cliff_wall_05_snow.ptex \
    cliff_wall_10.ptex \
    cliff_wall_10_snow.ptex \
    woodwall_brownslats001.ptex \
    mining_car.ptex \
    cliff_wall_island.ptex \
    wooden_barrier01.ptex \
    chimney01.ptex \
    chimney04.ptex \
    chimney03.ptex \
    chimney06.ptex \
    wood_patch3.ptex \
    wood_patch3b.ptex \
    wood_patch3c.ptex \
    window5.ptex \
    wood_patch1.ptex \
    wood_patch1b.ptex \
    wood_patch1c.ptex \
    chimney02.ptex \
    wood_support_256.ptex \
    chimney08.ptex \
    train_caboose.ptex \
    metalroof_neutral001.ptex \
    minehead.ptex \
    snow_fence_wood001.ptex \
    woodwall_darkbrown001.ptex \
    snow_fence_wood002.ptex \
    skybox_barn_bb001.ptex \
    cliff_wall_02.ptex \
    cliff_wall_02_snow.ptex \
    locker001.ptex \
    track_switch_bb001.ptex \
    radar001.ptex \
    radar002.ptex \
    chimney09.ptex \
    truss002.ptex \
    truss006.ptex \
    chimney05.ptex \
    woodwall_darkbrown001b.ptex \
    binder001.ptex \
    binder001_blue.ptex \
    fence_small_bb01.ptex \
    scout_red.ptex \
    scout_normal.ptex \
    scout_red_exponent.ptex \
    scout_blue.ptex \
    scout_head.ptex \
    scout_head_phongmask.ptex \
    scout_head_exponent.ptex \
    scout_hands.ptex \
    scout_hands_normal.ptex \
    engineer_hands_lightwarp.ptex \
    v_scattergun.ptex \
    w_scattergun.ptex \
    hvyweapon_red.ptex \
    hvyweapon_normal.ptex \
    hvyweapon_blue.ptex \
    heavy_head.ptex \
    heavy_head_phongmask.ptex \
    heavy_head_exponent.ptex \
    hvyweapon_hands.ptex \
    c_minigun.ptex \
    c_minigun_exp.ptex \
    c_grenadelauncher.ptex \
    c_pistol.ptex \
    c_pistol_exp.ptex \
    c_rocketlauncher.ptex \
    c_rocketlauncher_exp.ptex \
    c_shotgun.ptex \
    c_shotgun_exp.ptex \
    c_wrench.ptex \
    v_bottle.ptex \
    c_shovel.ptex \
    demoman_hands.ptex \
    engineer_handr_red.ptex \
    engineer_handl.ptex \
    soldier_sleeves_red.ptex \
    soldier_sleeves_normal.ptex \
    soldier_sleeves_blue.ptex \
    soldier_hands.ptex \
    v_shotgun.ptex \
    pyro_blue.ptex \
    pyro_normal.ptex \
    pyro_red.ptex \
    pyro_hands_red.ptex \
    v_pistol.ptex \
    v_wrench_sheet.ptex \
    v_rocketlauncher01.ptex \
    v_rocket.ptex \
    v_shovel.ptex \
    v_bat.ptex \
    v_bat_phongwarp.ptex \
    v_fireaxe.ptex \
    c_flamethrower.ptex \
    c_flamethrower_blue.ptex \
    ship_conveyer.ptex \
    cargo_ship_skybox.ptex \
    sewer_grate_end01.ptex \
    wood_fence_256.ptex \
    wood_fence_256b.ptex \
    wood_fence_short_256.ptex \
    wood_fence_short_256b.ptex \
    wood_beam03.ptex \
    boulder6.ptex \
    boulder6_normal.ptex \
    boulder6_desat.ptex \
    boulder5.ptex \
    boulder5_normal.ptex \
    boulder5_desat.ptex \
    radio_tower001.ptex \
    handrailcorner.ptex \
    boulder2.ptex \
    boulder2_normal.ptex \
    boulder2_desat.ptex \
    sawmill_wood.ptex \
    handrail_corner02.ptex \
    handrail_corner02_skin2.ptex \
    handrail_corner02_skin3.ptex \
    crane001.ptex \
    scaffolding1.ptex \
    truss008.ptex \
    sawmill_bolts.ptex \
    wall020.ptex \
    boulder1.ptex \
    boulder1_normal.ptex \
    boulder1_desat.ptex \
    boulder7.ptex \
    boulder7_normal.ptex \
    boulder7_desat.ptex \
    train_bumper_diffuse.ptex \
    w_rocket01.ptex \
    w_rocketlauncher01.ptex \
    wood_patch4.ptex \
    wood_patch4b.ptex \
    wood_patch4c.ptex \
    boulder4.ptex \
    boulder4_normal.ptex \
    boulder4_desat.ptex \
    boulder_pile1.ptex \
    boulder_pile1_normal.ptex \
    boulder_pile1_desat.ptex \
    wood_debris1.ptex \
    red_beam1.ptex \
    foliage1.ptex \
    corn_plant01.ptex \
    corn_plant02.ptex \
    grain_machinery_set3.ptex \
    hay_bale_round_skybox.ptex \
    fence_heads.ptex \
    conveyer_belt.ptex \
    conveyer_support.ptex \
    conveyer_belt_red.ptex \
    grain_elevator_pipes.ptex \
    sky_well_01_hdrbk.ptex \
    sky_well_01_hdrdn.ptex \
    sky_well_01_hdrft.ptex \
    sky_well_01_hdrlf.ptex \
    sky_well_01_hdrrt.ptex \
    sky_well_01_hdrup.ptex \
    sky_upward_hdrup.ptex \
    sky_upward_hdrdn.ptex \
    sky_upward_hdrside.ptex \
    sky_granary_01_hdrdn.ptex \
    sky_granary_01_hdrup.ptex \
    sky_granary_01_hdrlf.ptex \
    sky_granary_01_hdrrt.ptex \
    sky_granary_01_hdrft.ptex \
    sky_granary_01_hdrbk.ptex \
    spy_red.ptex \
    spy_normal.ptex \
    spy_blue.ptex \
    spy_head_red.ptex \
    spy_head_phongmask.ptex \
    spy_head_exponent.ptex \
    spy_head_blue.ptex \
    spy_hands_red.ptex \
    spy_hands_normal.ptex \
    spy_hands_blue.ptex \
    mask_demo.ptex \
    mask_spy.ptex \
    mask_engi.ptex \
    mask_heavy.ptex \
    mask_medic.ptex \
    mask_pyro.ptex \
    mask_scout.ptex \
    mask_sniper.ptex \
    mask_soldier.ptex \
    v_knife.ptex \
    w_revolver01.ptex \
    v_revolver.ptex \
    water_barrel.ptex \
    bridge_railing_red.ptex \
    bridge_railing_blue.ptex \
    water_machinery4.ptex \
    pine_tree_large.ptex \
    water_machinery1.ptex \
    water_machinery2.ptex \
    water_machinery3.ptex \
    barrel02.ptex \
    gorge_set1.ptex \
    gorge_handrails.ptex \
    gorge_set3.ptex \
    gorge_set4.ptex \
    gorge_set5.ptex \
    gorge_set2.ptex \
    tree_pine_stump01.ptex \
    radio_tower001_blue.ptex \
    sky_trainyard_01ft.ptex sky_trainyard_01bk.ptex \
    sky_trainyard_01lf.ptex sky_trainyard_01rt.ptex \
    sky_trainyard_01up.ptex sky_trainyard_01dn.ptex \
    toolsnodraw.ptex \
    concretefloor003.ptex \
    concretewall011.ptex \
    Ibeam002.ptex \
    Ibeam002_normal.ptex \
    red_wall1_bottom.ptex \
    blue_wall2_bottom.ptex \
    metaldoor01_96_noentry.ptex \
    metalstair001a.ptex \
    red_beam2_middle.ptex \
    wood_floor002.ptex \
    blue_wall1_middle.ptex \
    red_wall1_middle.ptex \
    metaldoor01_96.ptex \
    brickwall002c.ptex \
    brickwall002_height-ssbump.ptex \
    red_wall2_bottom.ptex \
    wall015g.ptex \
    wall015_bump-ssbump.ptex \
    wall007a.ptex \
    wall028.ptex \
    brickwall004d.ptex \
    brickwall004_height-ssbump.ptex \
    Imetal005.ptex \
    Imetal001_normal.ptex \
    toolsplayerclip.ptex \
    blue_wall2_middle.ptex \
    concretewall011c.ptex \
    dirtground003.ptex \
    dirtground006_height-ssbump.ptex \
    toolsskip.ptex \
    toolshint.ptex \
    computerwall003e.ptex \
    computerwall003c.ptex \
    red_wall2_middle_broken.ptex \
    red_wall4_middle.ptex \
    red_wall4_middle_broken.ptex \
    water_hydro_base.ptex \
    dx80_tfwater001_normal.ptex \
    red_wall2_middle.ptex \
    metaltrim01.ptex \
    wood_wall006.ptex \
    wood_wall006_bump_ssbump.ptex \
    floorplate01.ptex \
    computerwall003a.ptex \
    tile_ceiling_worn.ptex \
    Ibeam003b.ptex \
    floor_tile_006a.ptex \
    floor_tile_006a_normal.ptex \
    wall029b.ptex \
    wall029_height-ssbump.ptex \
    Imetal003.ptex \
    wall029.ptex \
    officedoor001.ptex \
    wall029a.ptex \
    red_wall1_middle_broken.ptex \
    concretewall011a.ptex \
    metalduct001a.ptex \
    metalduct001a_normal.ptex \
    toolsblocklight.ptex \
    toolsskybox.ptex \
    metaldoor01_192.ptex \
    metaltrim02.ptex \
    toolsblack.ptex \
    wall011d.ptex \
    wall011d_bump-ssbump.ptex \
    black_gradient.ptex \
    concretewall005.ptex \
    toolsblockbullets.ptex \
    metalgrate013a.ptex \
    glasswindow005a.ptex \
    Chicken_Wire001.ptex \
    metalchrome002.ptex \
    glasswindow002b.ptex \
    dust_gradient02.ptex \
    dust_gradient01.ptex \
    rockwall012.ptex \
    rockwall009_height-ssbump.ptex \
    dirtground010.ptex \
    rockwall001_normal.ptex \
    wall025.ptex \
    beach_dry.ptex \
    toolstrigger.ptex \
    toolsareaportal.ptex \
    toolsoccluder.ptex \
    Ibeam001.ptex \
    Ibeam001_normal.ptex \
    wall015.ptex \
    wall016_bump-ssbump.ptex \
    metaltrack001.ptex \
    Imetal001b.ptex \
    computerwall004.ptex \
    wall014.ptex \
    metaldoor001_normal.ptex \
    concretefloor007_height-ssbump.ptex \
    computerwall005c.ptex \
    plasticwall001a.ptex \
    plasticwall001a_normal.ptex \
    bridgebeam001.ptex \
    wall007c.ptex \
    concretewall011b.ptex \
    concretefloor007b.ptex \
    concretefloor007b_height-ssbump.ptex \
    concretewall001e.ptex \
    floor_tile_002a.ptex \
    floor_tile_001a_normal.ptex \
    concretewall001d.ptex \
    concretewall014b.ptex \
    glasswindow002a.ptex \
    concretewall002b.ptex \
    concretewall002_bump-ssbump.ptex \
    concretewall014a.ptex \
    hazard_yellow001.ptex \
    concretewall014.ptex \
    concretewall003b.ptex \
    Imetal006.ptex \
    concretewall014c.ptex \
    Ibeam003.ptex \
    Ibeam003_normal.ptex \
    officedoor002.ptex \
    wood_wall007a.ptex \
    glasswindow001b.ptex \
    metaltruss001.ptex \
    no_entry.ptex \
    wall016d.ptex \
    wall016d_bump-ssbump.ptex \
    demoman_blue_gib.ptex \
    demoman_red_gib.ptex \
    dirtground004.ptex \
    dirtground003_height-ssbump.ptex \
    rockwall001forest.ptex \
    beach_wet.ptex \
    engineer_red_gib.ptex \
    engineer_blue_gib.ptex \
    v_toolbox_red.ptex \
    v_toolbox_blue.ptex \
    toolbox_red.ptex \
    toolbox_blue.ptex \
    v_pda_engineer.ptex \
    v_builder.ptex \
    v_pda_engineer_screen.ptex \
    blueprint_build.ptex \
    blueprint_model.ptex \
    sentry_pulse_red.ptex \
    sentry_pulse_blue.ptex \
    sentry_pulse.ptex \
    sentry_pulse2.ptex \
    pilotlight.ptex \
    pilotlight_motion.ptex \
    c_flamethrower_exp.ptex \
    engineer_handR_blue.ptex \
    disp_blueprint_build.ptex \
    disp_blueprint_model.ptex \
    dispenser.ptex \
    dispenser_phongmask.ptex \
    dispenser_blue.ptex \
    dispenser_Gibs.ptex \
    dispenser_Gibs_blue.ptex \
    tp_sheet_red.ptex \
    tp_sheet_blue.ptex \
    teleporter_blueprint_enter.ptex \
    teleporter_blueprint_exit.ptex \
    teleporter_blueprint_model.ptex \
    teleportspin_red.ptex \
    teleportspin_blue.ptex \
    tp_direction.ptex \
    tp_direction1.ptex \
    teleporter_Gibs.ptex \
    teleporter_Gibs_Blue.ptex

#end install_tex

#begin install_mat
  #define SOURCES \
    concretefloor01.pmat \
    tutorial_battle_props_palette_4samlc_1.pmat \
    expl001.pmat expl002.pmat expl003.pmat expl004.pmat \
    expl005.pmat expl006.pmat expl007.pmat expl008.pmat \
    expl009.pmat expl010.pmat

#end install_mat
